### ISSUE TITLE
サーバーのログ出力形式をJSONにする

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#1006]
サーバーのログ出力形式をJSONにするとCloudWatchのInsightが効くようになるので運用がラクになるかも知れない。

**Comment by katsuNakajima** [comment]
確認です。
`2021-10-07 03:16:53,840 INFO  [atcoder_problems_backend::server::middleware] `のようなprefixを取り除き、
```
{
    "duration": 0.014,
    "method": "GET",
    "status": 200,
    "url": "..."
}
```
のようなログ出力にするという対応であってますでしょうか？

**Comment by kenkoooo** [comment]
はい、そうです

**Comment by kenkoooo** [comment]
お願いします！何か分からないことや詰まったことがあったらいつでも書いてください。

**Comment by kenkoooo** [comment]
フォーマットの融通がきく別の crate があればそれが一番良さそうです。無ければ自前実装が良さそうですが、コード量があまりに多くなるようならやらなくても良いかな、という感じです。

**Comment by katsuNakajima** [comment]
遅くなってしまいすいません。
[env_logger](https://docs.rs/env_logger/0.9.0/env_logger/#using-a-custom-format) crateの[Builder](https://docs.rs/env_logger/0.6.0/env_logger/struct.Builder.html)構造体に任意のログフォーマットが定義てきそうなので、これでの実装をしていきたいと思います。

**Comment by kenkoooo** [comment]
:+1: :+1:

**Comment by katsuNakajima** [comment]
ではPR投げますので、レビューお願いします。

**Comment by hotate29** [comment]
PRもマージされましたし、閉じても良さそうです？

**Comment by kenkoooo** [comment]
そうですね。閉じます。

**Comment by katsuNakajima** [comment]
ありがとうございました！
またできることがあれば協力させてください！！

**Comment by kenkoooo** [comment]
ぜひ！
