### ISSUE TITLE
バチャガチャのオプションに「xヶ月以内に解いていないもの」みたいなものが欲しい

### ISSUE THREAD

**Issue by k1832** [kenkoooo/AtCoderProblems#1008]
"Exclude already solved" に近いものとして、最近解いた問題を省く機能が欲しいです。
（逆にいえば、すでに解いている問題だとしても昔解いた問題は忘れているだろうし含めるという機能です。）
自分よりレートの低い人とバチャがしたいけど自分はそのあたりのDiffの問題をほぼ解いてしまっている場合など、この機能があったら嬉しいケースがある気がします。

xヶ月のxを固定するか、指定できるようにするかなど細かいところは全然考えていませんが、ご検討くださいませ。。

**Comment by k1832** [comment]
#532 にちょっと関連している気もします

**Comment by fukatani** [comment]
このイシューやってみたいです。
Recommendationと一緒で、ドロップダウンメニューで"Exclude problems solved in last XXX"をいくつか候補として選べるようにすればいいと思います。

**Comment by kenkoooo** [comment]
良さそうです。今あるチェックボックスをドロップダウンで置き換える感じですかね。

**Comment by fukatani** [comment]
そうですね、チェックボックスは不要になるのでドロップダウンで置き換えるつもりです。
