### ISSUE TITLE
バチャのスコアの挙動がおかしい。

### ISSUE THREAD

**Issue by nephrologist** [kenkoooo/AtCoderProblems#1011]
精進記録用として、長時間バチャを開催してくれている方が何名かいらっしゃるのですが、これらに参加してACしてもスコアが更新されません。
仕様上、仕方ない(長期間の結果の取得は難しいetc)のであれば、仕方がないのですが、ご対応いただけるようならお願いいたします。

一例としては、このバチャが参加者全員スコアレスになっているように見えます。
https://kenkoooo.com/atcoder/#/contest/show/f1fd5759-0b54-4365-974e-6681a3837443

(なれておらず、Issueの立て方が不適切なら削除いたします。)

**Comment by kenkoooo** [comment]
全ての提出から `(開催期間中の提出) && (バチャ参加者の提出) && (バチャで出題されている問題の提出)` で絞り込んでバチャの提出を抽出しているのですが、開催期間が長すぎてその件数が多すぎるのではないかと思います。サーバーが返す提出数の上限があるので、それを超えると正しい結果が表示されないかもしれません。

**Comment by nephrologist** [comment]
ありがとうございます。このツールのおかげで精進が捗っているのでいつも本当に感謝しております。

わがままな代替案として、他の人が開催したバチャをコピーして自分用に変更して使用する事ができれば、記録もできていいかなと思うのですが、そのような機能の実装は難しいでしょうか。

**Comment by kenkoooo** [comment]
一括でコピーコピーできるのは一見良さそうに見えますが、実際に解かれるかはよく分かっていなくて、もし本当に解く気があるならprivateでコンテストを作って、都度継ぎ足していくのでも良いような気がします（個人的な意見で特に強く否定するものではものではありません）

**Comment by nephrologist** [comment]
お返事ありがとうございます。
確かに問題ごとに5問ずつなどプライベートにやったほうが進捗管理としていい気もしました。
(立てるだけ立てて説かれないバチャのせいで、サーバー負荷かけるのも良くないですよね、とあとから思い至りました。)
ご検討ありがとうございました。
