### ISSUE TITLE
vjudge や luogubot を集計から除外する

### ISSUE THREAD

**Issue by fukatani** [kenkoooo/AtCoderProblems#1022]
streak_rankingなどのranking: APIではvjudgeを含んでいるがフロントエンドでは除外して改めてカウントしている
user/streak_rankなどのuser rank: vjudgeを含んだままの順位

そのため、両ランクが微妙に異なってしまう可能性がある。
また、さらに悪いことに、
https://github.com/kenkoooo/AtCoderProblems/pull/1012
以降、user rankを使ってページ最初のユーザーの順位を求めているが、これによってAC Rankiingなどのランキングページの分かれ目で順位が食い違ってしまう。

以下、ローカルでの結果。一枚目ではstreak4の人は14位だが、2ページ目からは16位になってしまっている。期待値はどちらも14位。

![Screenshot from 2021-07-22 18-19-52](https://user-images.githubusercontent.com/8858287/126616715-01ad9158-175a-4b6d-989d-f43d38188c31.png)
![Screenshot from 2021-07-22 18-20-03](https://user-images.githubusercontent.com/8858287/126616721-08ede350-2aaf-4629-b78e-5ccf4866b61d.png)

対策：APIの段階でvjudgeを除外？

**Comment by fukatani** [comment]
本番環境で見ても例えばac_rankの14ページと15ページの間でランキングの数字が飛んでしまっています。

**Comment by kenkoooo** [comment]
たしかに、バックエンドの集計から除外してしまう方が良いかもしれませんね。

**Comment by fukatani** [comment]
このイシュー、考えてみますね。

**Comment by fukatani** [comment]
@kenkoooo 
```
    async fn load_accepted_count_in_range(
        &self,
        rank_range: Range<usize>,
    ) -> Result<Vec<UserProblemCount>> {
        let count = sqlx::query(
            r"
            SELECT user_id, problem_count FROM accepted_count
            ORDER BY problem_count DESC, user_id ASC
            WHERE not user_id like 'vjudge%'
            OFFSET $1 LIMIT $2;
            ",
        )
```
のような感じで、SQL読み出しクエリの段階で、除外する形でどうでしょう？

**Comment by fukatani** [comment]
https://atcoder.jp/users/vjudge0
vjudge0なる中国人がいますが、諦めることになります。

**Comment by kenkoooo** [comment]
それはあまりにも失礼かと……

**Comment by kenkoooo** [comment]
先ほどのコメントは当人が見たら嫌な気持ちになってしまうので私の判断で削除しました。すみません。

**Comment by kenkoooo** [comment]
集計を担当している `delta_update` や `batch_update` が SQL に書き込む際に除外するユーザーのリストを、どこかのモジュールにハードコードしておく他なさそうです。これは手動の作業になってしまいますが、ユーザーを除外するのはかなり強い操作なので手動でも良いでしょう。

**Comment by fukatani** [comment]
いえ、私の不用意な発言でお手数をおかけしてすいません。対応してくださり、ありがとうございました。
kenkooooさんの提示していただいた方針で考えてみます。
