### ISSUE TITLE
AC数が0のユーザーのAC数APIやLongest StreakAPIを叩くと404になる

### ISSUE THREAD

**Issue by sacckey** [kenkoooo/AtCoderProblems#1024]
AC数が0のユーザーのAC数APIやLongest StreakAPIの返答が404になってしまいます。
例
- https://kenkoooo.com/atcoder/atcoder-api/v3/user/ac_rank?user=test
- https://kenkoooo.com/atcoder/atcoder-api/v3/user/streak_rank?user=test 

Submission APIでは提出が無いユーザー(存在しないユーザーも含む)の場合は空配列が返ってくるので、
そのような仕様にするのはどうでしょうか。

実装案は、accepted_countテーブルにレコードがない場合は、get_users_accepted_countの返り値を0にする感じです。

**Comment by kenkoooo** [comment]
どちらでも良いと思いますが、具体的にどのような用途で困っているのか気になります。

**Comment by sacckey** [comment]
AtCoderユーザーの最近の提出やコンテスト結果を表示するアプリを作っているのですが、
アプリのDBに保存されていないAtCoder Userが初めて検索された際に、AC数や最近の提出を取得したいと思っています。
その際にAC数が0のユーザーが検索されたときも同じ処理で取得できると嬉しいというぐらいで、特に困っているわけではないです。

どちらかというと、Submission APIと仕様が異なっている方が気になった感じです。

**Comment by kenkoooo** [comment]
なるほど、特に強い理由があるわけではないのですが、以下のような気持ちで考えていました。

- リストを返す関数は、返すものが存在しない時は空のリストを返す。
  - `vector<submission> get_submissions(string user_id) {}` みたいな感じです。
- 構造体を返す関数は、返すものが存在しない時は null を返す。
  - `optional<user> get_user_info(string user_id) {}` みたいな感じです。

なので個人的には今の方が自然かなぁという感じはします。

**Comment by sacckey** [comment]
ありがとうございます。
確かに現状の仕様の方が自然に思えてきました。

強い要望があるわけでなかったので、こちらcloseいたします。
