### ISSUE TITLE
ユーザーページのAC数ランクが表示されないことがある

### ISSUE THREAD

**Issue by cupro29** [kenkoooo/AtCoderProblems#1027]
ユーザーIDに英大文字が含まれるときにユーザーページのAC数ランクが表示されないようです。

![image](https://user-images.githubusercontent.com/63996969/126892570-9f09bf6e-9342-4bb4-9dc3-9389332a331c.png)

https://github.com/kenkoooo/AtCoderProblems/blob/0d85a32f257bcd54e1b220eb7bdc9716312205a0/atcoder-problems-backend/sql-client/src/streak.rs#L50-L56
と同じように、
https://github.com/kenkoooo/AtCoderProblems/blob/0d85a32f257bcd54e1b220eb7bdc9716312205a0/atcoder-problems-backend/sql-client/src/accepted_count.rs#L72-L78
で `WHERE LOWER(user_id) = LOWER($1)` とすれば解決できそうな気がします。

**Comment by kenkoooo** [comment]
> `WHERE LOWER(user_id) = LOWER($1)` とすれば解決できそうな気がします。

はい、これで良さそうです。
