### ISSUE TITLE
8問構成 ABC によりコンテスト問題毎の集計が不正

### ISSUE THREAD

**Issue by uesugi6111** [kenkoooo/AtCoderProblems#1035]
![image](https://user-images.githubusercontent.com/59960488/127744754-d1965cb0-9dfe-4b51-baa1-d993e25db14a.png)

ABC212 終了時点での A問題合計数が214となっている
増加したG, H が加算されている？

**Comment by kenkoooo** [comment]
@uesugi6111 もし興味があればやってみませんか？

**Comment by StorkKershaw** [comment]
横から失礼します。本 issue をやってみたいのですが良いでしょうか?

**Comment by kenkoooo** [comment]
@StorkKershaw お願いします！
