### ISSUE TITLE
問題テーブル(?)に表示されるペナルティーにCEが含まれている件について

### ISSUE THREAD

**Issue by krpsV** [kenkoooo/AtCoderProblems#1046]
![image](https://user-images.githubusercontent.com/88704502/128819257-523a1af5-4c1a-4b01-a68d-6ded64d26b99.png)
この画像のように、問題の右下に表示されるペナルティー数の部分にCEが含まれてしまっています。

**Comment by kenkoooo** [comment]
### この issue に取り組む人へ

バチャの順位表ページでは以下のように CE をフィルタリングしているのですが、それ以外の部分ではフィルタリングしていないのが原因です。
https://github.com/kenkoooo/AtCoderProblems/blob/0282bbde17f6b5628f3bb366fef2ac8cb2fca5f0/atcoder-problems-frontend/src/pages/Internal/VirtualContest/ShowContest/util.ts#L30

他のページでもCEは常に取り除いてもよいかと思ったのですが、世の中にはCEを解説ACマーキングとして使っている人もいるらしいので、このissueではTableのContest Result表示の挙動のみを更新したいです。

**Comment by UUGTech** [comment]
@kenkoooo こちらPRいたしましたので確認していただけると幸いです

**Comment by kenkoooo** [comment]
@UUGTech マージしてリリースしました！ありがとうございます！

@krpsV また何か見つけたらお願いします！
