### ISSUE TITLE
Difficultyのマークの色が微妙に欠けている

### ISSUE THREAD

**Issue by CKPCKP** [kenkoooo/AtCoderProblems#1049]
一部の問題のDifficultyにおいて、マーク？の下部の色が欠けています
![image](https://user-images.githubusercontent.com/61152961/130343402-4f3c9429-c9db-4d70-993f-43b3dd10bd08.png)

**Comment by southball** [comment]
ブラウザのバグではないかなと思って探したら下のバグが出てきて、2018年3月の Chrome で見てみたらこの問題はありませんでした。

https://bugs.chromium.org/p/chromium/issues/detail?id=1143698&q=linear-gradient&can=2

2018年3月の Chrome で取ったスクリーンショット
![image](https://user-images.githubusercontent.com/6523469/130389017-0c1b7133-2b39-4f82-a119-e8ec4e0b0563.png)

最新の Chrome で取ったスクリーンショット：
![image](https://user-images.githubusercontent.com/6523469/130389185-ec640570-5110-4fa6-b327-ec690962c53c.png)
