### ISSUE TITLE
スマホだとUser IDが入力しづらい

### ISSUE THREAD

**Issue by Eug1ena** [kenkoooo/AtCoderProblems#1054]
スマホの UI だと、User ID の入力欄や Table/List の切り替えボタンがかなり下の方にあって、使いづらいです。
メニューが表示されていないときも入力欄等を表示する仕様にしてはどうでしょうか？

<img width="392" alt="スクリーンショット 2021-09-01 15 46 26" src="https://user-images.githubusercontent.com/36365771/131625644-40143dcf-fd48-4763-8736-2455e3b1360c.png">

**Comment by kenkoooo** [comment]
アイディアとしてはかなり納得感があるのですが、実はかつてはユーザー ID 入力欄や Table/List/User を常に表示していました。1-2年くらい前に「スマホで見ると常に画面の一部が専有されていて邪魔」という意見があって現在の形になったと記憶しています。

**Comment by Eug1ena** [comment]
なるほど、そのような経緯があったのですね。
それでは、スマホでは User ID 入力欄や Table/List/User が上部に固定されないようにするのはどうでしょう？
あるいは、AtCoder のようにリボンを固定するかどうかをスイッチするというのはいかがでしょうか。

**Comment by kenkoooo** [comment]
どちらも良さそうです。僕はスマホ自体あまり使わないので、実際に使う人が使いやすい方法で良いと思います。
