### ISSUE TITLE
コンテストでの配点（あれば）を表示する

### ISSUE THREAD

**Issue by maspypy** [kenkoooo/AtCoderProblems#1079]
（得点を考える側の立場になることもあるという、やや個人的な事情からくる要望です。）

difficulty だけでなく、配点も見られると嬉しいです。ご検討よろしくお願いします。
イメージ画像を付けておきます。

![image](https://user-images.githubusercontent.com/45988013/142771310-a304ad3b-fd33-4103-9656-373a024b9faa.png)

**Comment by kenkoooo** [comment]
ListだけではなくTableにも表示したいということですかね？

**Comment by maspypy** [comment]
そうですね。この表の形で見えると嬉しいですね。

**Comment by maspypy** [comment]
いま、Colored by = Contest Result とすると、ここにかかった時間やペナ数が表示できます。
ひとつの案としては、Colored by = None のときに配点が表示されるというものです。

**Comment by Balut-moko** [comment]
こちらのissueを担当してもよろしいですか？

**Comment by kenkoooo** [comment]
@Balut-moko ぜひお願いします！

**Comment by maspypy** [comment]
ありがとうございましたー。
