### ISSUE TITLE
VirtualContest詳細ページをタブで管理する

### ISSUE THREAD

**Issue by MatsuTaku** [kenkoooo/AtCoderProblems#1087]
現在の`/contest/show/*`はProblemsとStandingsを同じページで表示していますが，問題数の多いコンテストではこのUIは適していません．

Problemsは右のトグルで畳めますが，Standingsとを行き来するのに適した機能ではありません．
Atcoderのように，タブで各種情報をナビゲーションするのが良いと思います．

実装方法としては，Problemsより上のUIは固定にし，ProblemsとStandingsをreactstrap/Tabsで(Userページのように)管理するのが自然だと思います．

### 関連Issue
#1077 #1083

**Comment by kenkoooo** [comment]
良さそうです。こちら #1083 にリンクしていますが、間に合わせる予定ですか？

**Comment by MatsuTaku** [comment]
そのつもりです．
ついでに #1077 も実装して良さそうに思いますが，如何でしょうか．

**Comment by kenkoooo** [comment]
一緒にやっていただいて構わないのですが、別のPRに分けられる気がするので分割して取り組んでいただけると助かります。

**Comment by MatsuTaku** [comment]
了解です．assignedしていただいて構いません．
