### ISSUE TITLE
TableのAGC-Like ContestでH問題がEx問題として扱われている

### ISSUE THREAD

**Issue by MtSaka** [kenkoooo/AtCoderProblems#1093]
TableのAGC-Like ContestでH問題がEx問題として扱われていて、I問題やJ問題の後に表示されています
おそらく #1089 の変更によって生じたバグだと思います
![スクリーンショット 2021-12-26 152025](https://user-images.githubusercontent.com/76619232/147412588-a30f299a-3860-463a-975c-cec43a833ec9.jpg)

**Comment by Michael172983** [comment]
I see

**Comment by MtSaka** [comment]
追記
ABC-Like ContestのH問題もEx表記になっています
