### ISSUE TITLE
バチャ順位表・問題切り替えタブのバグまとめ

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#1101]
https://twitter.com/mts1104_ml/status/1476494359181008897

**Comment by MatsuTaku** [comment]
- [ ] タブ切り替えで順位表のautoRefreshが切れるのは仕様通り。全体でautoRefreshのフラグを共通化するかどうかを検討
- [ ] 順位表が真っ白になる不具合はまだ再現できてない

**Comment by kenkoooo** [comment]
> タブ切り替えで順位表のautoRefreshが切れるのは仕様通り。
そうなんですか？

**Comment by MatsuTaku** [comment]
- AtCoderやcodeforcesの順位表はページ表示の度に自動更新はOFFになるので、同様の仕様のままにしています
- 実装の状況としては、useState でインスタンス化した変数なので、Standings コンポーネントの再表示の度に初期値falseにリセットされます

ページ内のタブで切り替えてるように見えるのにフラグが保存されてないので、違和感を感じるんだと思います。

仕様をどうするかの個人的意見ですが、tweet主のように両方をシームレスに確認したい人はブラウザのタブを分けるので、今の仕様のままでよいかなと思います。

**Comment by kenkoooo** [comment]
なるほど、了解です

**Comment by MatsuTaku** [comment]
タブ切り替えで順位表が真っ白になる不具合、ここでタブ連打してたら確認できました。
https://kenkoooo.com/atcoder/#/contest/show/20c1b9b6-8de8-4468-b01f-bdbc4df5e6e4?activeTab=Standings

**Comment by kenkoooo** [comment]
https://twitter.com/rian_tkb/status/1488127168916123655

**Comment by MatsuTaku** [comment]
検証して現状分かったことの整理
#### 検証時の操作
「コンテストページ(順位表画面)の表示から、`Problems`->`Standings`とタブを切り替え」
#### 現象
useUserSubmissionsに対して
1. タブを切り替えた際に、useUserSubmissionsのリクエストに対し空の(nullではない)submission.dataが返ってくる
2. 加えて、useUserSubmissionsのAPIコールが行われない**場合がある**

1.の発生により、空のデータが存在することでスピナーが正常に動作せず、空のテーブルが表示される状態になり、
2.も発生するとそのまま更新されない状態になる。

2.は素早くタブを切り替えると起こりやすい模様

**Comment by MatsuTaku** [comment]
#### useVirtualContestSubmissions内でのuseSWRDataの呼び出し方が特殊なことが原因

ここでのuseSWRData呼び出し時ののurlを"usevVirtualContestSubmission"という特殊キーで統一している。
ProblemsとStandingsはそれぞれuseVirtualContestSubmissionを呼び出しているが、タブ切り替えを高速に行うと、Standsingsの直前でProblemsで"usevVirtualContestSubmission"をurlキーとして呼び出したSWRがキャッシュとして返されてしまっている。

解決方法としては、上位階層でusevVirtualContestSubmissionのデータを共有するのがよさそう
