### ISSUE TITLE
atcoder problems の virtual contest の FA、なんか変？

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#1123]
https://twitter.com/rian_tkb/status/1494291309062148098

**Comment by cupro29** [comment]
コンテスト後にテストケースが追加された問題では、追加されたケース以外のケースのみ正答することによって、満点を取っているがACは取っていないという状態が発生します。
この状態になった後に、追加されたケースを含めてACして満点を取得しても、下記のコードでは点数が改善されたときのみAC状況が更新されるようになっているため、virtual contest の内部ではACしていないものと扱われます。
これによって、一度 after_contest  だけを落としてしまうと、正しい解法でACし直しても、内部ではACしていないとされてFAを取れないということになっているようです。
https://github.com/kenkoooo/AtCoderProblems/blob/281ba7988a941d558952d251713d752535e8a94a/atcoder-problems-frontend/src/pages/Internal/VirtualContest/ShowContest/ResultCalcUtil.ts#L46-L59
