### ISSUE TITLE
User IDs should be case-insensitive

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#113]
UserInfo API と Submission API の入力のuser IDの大文字小文字を区別しないようにしてほしいです。
エンドユーザにとって微妙に不便であり、API利用側にとっても「大文字小文字を間違えないように注意してね」のような注意を書かないといけないのは面倒だからです。

例えば https://atcoder.jp/users/KeNkOoOo などのURLが適切に表示されるのでAtCoder内部では大文字小文字は区別されておらず、このように変更しても不都合はないはずです。

**Comment by kmyk** [comment]
(Issue 建てておいた方がよい事項だなあと思ったのでとりあえず建てただけであり、優先度は高くないです。特にプルリクを投げる予定はありません。)

**Comment by kenkoooo** [comment]
バックエンドでは実装されたので、フロントエンドを実装する必要があります。

**Comment by kenkoooo** [comment]
とりあえず #841 の実装でokだと思います
