### ISSUE TITLE
バックエンドにもDependabotを

### ISSUE THREAD

**Issue by hotate29** [kenkoooo/AtCoderProblems#1147]
dependabotがフロントエンドにPRを投げている様子をたまに見かけるのですが、バックエンドにも投げさせる事でフロントエンドと同様のうれしさがあると思います。（バックエンドへのPRが無いので使用していないと勝手に決めつけていますが、もし使用してたらすみません…）

**Comment by hotate29** [comment]
PRを投げる条件はどのように設定されていますか？手元で試してみた（https://github.com/hotate29/AtCoderProblems/commit/c38766fb6893ecc8c5e3b4fd59a294f1b949f9e5 ）のですが、どうも動作が違うようです。

**Comment by kenkoooo** [comment]
実はdependabotを明示的に設定しているわけではなくて、セキュリティパッチについては何も設定していないのにGitHubが送ってきてくれている感じです。良い機会なので挙げていただいた様な感じで設定できればと思います。

**Comment by hotate29** [comment]
自動的に送ってくれるのは知りませんでした（便利～）。では、挙げた内容でPRを作成しようと思います。
