### ISSUE TITLE
Rated Point Ranking が表示されない

### ISSUE THREAD

**Issue by gmmtea** [kenkoooo/AtCoderProblems#1188]
https://kenkoooo.com/atcoder/#/sum
![スクリーンショット 2022-05-18 17 22 19](https://user-images.githubusercontent.com/47593304/168994783-ef8f58d7-3ebf-4aa4-9a62-a10037bbcbad.png)

ユーザーページで Rated Point Sum の順位は表示されるのでデータとしては持っていそうですが。。。

**Comment by hotate29** [comment]
F12でバックエンドから返される値（`v3/rated_point_sum_ranking?from=0&to=20`）を確認したのですが、受け取っているデータが`[{"user_id": "a", "point_sum": 1}, {"user_id": "b", ...]`という形式でした。

![image](https://user-images.githubusercontent.com/44938840/169089771-202737a7-2279-424d-85b2-505e9582ef4a.png)

<details>
<summary>生データ</summary>

`[{"user_id":"kmjp","point_sum":1106218},{"user_id":"mtsd","point_sum":1079500},{"user_id":"maspy","point_sum":1026823},{"user_id":"heno239","point_sum":1007500},{"user_id":"ygussany","point_sum":956000},{"user_id":"noimi","point_sum":949000},{"user_id":"solareenlo","point_sum":907400},{"user_id":"Rubikun","point_sum":882500},{"user_id":"tute7627","point_sum":837500},{"user_id":"olphe","point_sum":830000},{"user_id":"sumitacchan","point_sum":824800},{"user_id":"satashun","point_sum":823525},{"user_id":"smiken","point_sum":820700},{"user_id":"hitonanode","point_sum":820200},{"user_id":"sugarrr","point_sum":813900},{"user_id":"IH19980412","point_sum":812411},{"user_id":"crowdforces","point_sum":811518},{"user_id":"rniya","point_sum":805200},{"user_id":"tokusakurai","point_sum":804400},{"user_id":"chocorusk","point_sum":803300}]`

</details>

一方フロントエンドでは`[{"user_id": "a", "count": 1}, ...]`という形式のデータ（"user_id"と"count"を持っているデータ）をランキングのデータと認識するので、ここで弾かれてしまっているのではないかと思いました。

https://github.com/kenkoooo/AtCoderProblems/blob/054346a74c1667e7f89c151fe0388e4730a195e7/atcoder-problems-frontend/src/interfaces/RankingEntry.ts#L8-L10

TypeScriptは何も知らないので、間違えているかもしれませんが...

**Comment by hotate29** [comment]
ただ、バックエンドが返す値が違うというのは奇妙で、実際テストも通っているのになぜ…

https://github.com/kenkoooo/AtCoderProblems/blob/054346a74c1667e7f89c151fe0388e4730a195e7/atcoder-problems-backend/tests/test_server_e2e_rated_point_sum_ranking.rs#L29-L42

**Comment by kenkoooo** [comment]
デプロイパイプラインがコケてました…申し訳ない…
再デプロイしたので直っていると思います！

**Comment by gmmtea** [comment]
確認できました！
ありがとうございます！！

**Comment by kenkoooo** [comment]
@hotate29 さんの確認、メチャ助かりました！ありがとうございます…！ :pray:

**Comment by hotate29** [comment]
@kenkoooo お役に立ててよかったです！
