### ISSUE TITLE
AGC009 is disappeared

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#119]
AGC009が表から消えています。もしかしたらその他のコンテストにも消えてるものがあるかもしれません

https://twitter.com/gzlcp/status/1101034797810372609
https://twitter.com/Ichijyo_piyo/status/1100819526420029440

**Comment by kenkoooo** [comment]
今見たらあったので再生してますかね？

**Comment by kmyk** [comment]
再生してますね。よかった

**Comment by kmyk** [comment]
ところでなぜAGC009だけ消えたのかって予想付いてたりしますか？ 理由が気になるので知りたいです

**Comment by kenkoooo** [comment]
ユーザー名変更が AtCoder に入ったのに合わせて SQL 周りの動作を「重複したレコードは新しい情報で書き換える」というようにしたのが原因です。
これが提出以外のレコードにも適用されていて、 jrex2017 の問題をクロールすると agc009_* の属している先が jrex2017 に更新されてしまっているようです。

**Comment by kenkoooo** [comment]
問題のクロールは 1 時間おきに走るので、agc009_* たちは所属コンテスト 1 時間おきに jrex2017 になったり agc009 になったりしているみたいです。

**Comment by kenkoooo** [comment]
これは何とかしましょう…

**Comment by kmyk** [comment]
なるほど、ありがとうございます
