### ISSUE TITLE
ListページのProblem ListのDate欄にコンテストの開始時間と異なる日付が表示されるものがある

### ISSUE THREAD

**Issue by ccppjsrb** [kenkoooo/AtCoderProblems#1190]
常設コンテストのうち下記の3つのコンテストの問題で「1970-01-01」と表示されます。
・アルゴリズムと数学　演習問題集
・C++入門 AtCoder Programming Guide for beginners (APG4b)
・AtCoder Beginners Selection

下記の2つの常設コンテストの問題ではコンテストの開始時間が表示されます。
・AtCoder Library Practice Contest
・競プロ典型 90 問

**Comment by ccppjsrb** [comment]
ちょっと調べてみたところ、atcoder-problems-backend/atcoder-client/src/atcoder/contest.rsのscrape_permanent内の以下の部分でstart_epoch_secondが0で登録されるようになっているから常設コンテストはコンテストの開始時間が表示されるわけではなさそうでした。
```
Ok(AtCoderContest {
    id: contest_id.to_owned(),
    start_epoch_second: 0,
    duration_second: PERMANENT_CONTEST_DURATION_SECOND,
    title: contest_title.to_owned(),
    rate_change: rated.to_owned(),
})
```
下記の2つについては通常のコンテストとして開催された後に常設コンテストに移動になったから開始時間が表示されてるだけでした。
・AtCoder Library Practice Contest
・競プロ典型 90 問

「1970-01-01」と表示される箇所は空欄の方が適切かと思うので空欄で表示されるように修正したPRを投げてみますので時間あるときに確認してもらえれば幸いです。

**Comment by kenkoooo** [comment]
resolved in #1191
