### ISSUE TITLE
TEEの進捗グラフを追加する

### ISSUE THREAD

**Issue by HirokiYoshida837** [kenkoooo/AtCoderProblems#1192]
はじめまして、

#848 にて記載されている以下の項目ですが、Climbingと同様の形式で表示できるよう仮で実装してみました。

> effort のグラフに入れる

![image](https://user-images.githubusercontent.com/59611617/170874157-96405a53-d849-456d-818e-2208f4388fa7.png)

ひとまず実装してみましたが、懸念点としては、以下あたりを考えております。
- TEE Climbingというラベル名でよいか
- 表示位置は Climbingの次にするか
- Climbingとほぼ同じような形になるので、初心者の方が内容がわからず混乱するかもしれない
- マウスオーバーした際のTooltipでの表示値が、小数以下まで表示されており、やや見づらさがありそう

こちらのブランチで実装しています
https://github.com/HirokiYoshida837/AtCoderProblems/pull/1/files

（すみません、初めてのコントリビュートですので、なにか不足してる点などありましたらご指摘いただけると助かります！）

**Comment by kenkoooo** [comment]
プルリク送っていただければ手の空いたときに拝見します！

**Comment by HirokiYoshida837** [comment]
@kenkoooo さん、
プルリクの https://github.com/kenkoooo/AtCoderProblems/pull/1226  がマージされましたので、こちらのIssueをcloseしてしまってもよいでしょうか？

**Comment by kenkoooo** [comment]
お願いします！
