### ISSUE TITLE
A*C とA*C-like をくっつける機能が欲しい

### ISSUE THREAD

**Issue by hotman78** [kenkoooo/AtCoderProblems#1194]
A\*C とA\*C-like をくっつける機能が欲しいです。
最近の傾向だと両者で形式に関しても出題傾向に関しても差が殆ど存在しないので、一覧性やtabの選びやすさの観点からもくっつけるメリットが大きい気がしています。
UIとしては、
- 新しいtabを作成してそこに双方のコンテストを入れる
- トグルボタンを用意してそれをONにした時にA*C-likeをなくしてA*Cにいれる
の２つが思いついていますが、個人的には後者の実装だと嬉しいです。

**Comment by nebocco** [comment]
これ見て思ったんですけど、現在コンテスト形式の選択がラジオボタン的になっているのをチェックボックス的に複数できるようにするのはどうでしょう？（ABCとABC-likeをどちらも押せばマージされて表示される、など）
