### ISSUE TITLE
update_language_count() takes 20 minutes?

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#1195]

**Comment by ccppjsrb** [comment]
update_language_count()の中でsubmissionsの数だけ呼ばれているっぽいsimplify_languageで毎回Regex::new()しているのが怪しそうです。Rustを書いたことがないので間違っているかもしれませんが・・・
https://docs.rs/regex/latest/regex/#example-avoid-compiling-the-same-regex-in-a-loop
