### ISSUE TITLE
Crawling submissions in reverse order

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#124]
提出を逆順で見れば取得漏れは基本的に消えます。これはコンテスト終了後の反映速度を大きく改善する (無駄な取得が消えるのでほぼ理論限界を達成すると言っていいはず) なので、反映速度の改善の意図で #123 をしたのならこちらもおすすめです。

**Comment by kenkoooo** [comment]
ありがとうございます。次のアップデートで入れましょう。
