### ISSUE TITLE
AtCoder Typical Contest 002でAが抜けている

### ISSUE THREAD

**Issue by YIPG** [kenkoooo/AtCoderProblems#125]
![image](https://user-images.githubusercontent.com/19145527/54011249-278dc800-41b5-11e9-9858-4e02ff878c6b.png)

![image](https://user-images.githubusercontent.com/19145527/54011266-370d1100-41b5-11e9-9fec-08ac2bc7336f.png)

問題が抜けている報告です。

**Comment by kenkoooo** [comment]
その問題は ABC007C として出題された問題を再度出題したものです。現在の AtCoder Problems では問題とコンテストが1対1で対応するように管理されていて、複数のコンテストで同じ問題を出題することに対応できていません。

AtCoder Problems を作り始めた 4 年前には同じ問題が複数のコンテストで出題されることはほとんどありませんでしたが、現在は ABC と ARC で同じ問題が出題されるようになり、こういったケースが増えてきたので、DBの設計を見直したほうが良いかも知れません。

**Comment by YIPG** [comment]
そうなのですね。ありがとうございます。
