### ISSUE TITLE
backendをふたつに分けたい

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#127]
スクレイピングをする部分とAPIサーバとしての部分はまったく直交しているはずです。これらをきちんと独立させると、実装の把握が楽になるのでプルリクを投げたりしやすくなります。
単に「設計として綺麗で分かりやすい」という以上の意味はないので優先度は低いはずですが、大きな改修をする機会があればこれを検討してほしいです。

**Comment by kenkoooo** [comment]
いいアイディアだと思います。SQLClient を分割するなど、少しずつ進めているので、近いうちに実現できると思います。
