### ISSUE TITLE
オンサイトコンテストの問題へのリンクの不具合

### ISSUE THREAD

**Issue by maspypy** [kenkoooo/AtCoderProblems#1274]
Other Sponsored

- 「第三回日本最強プログラマー学生選手権 -決勝-」
- 「第三回日本最強プログラマー学生選手権 -決勝- (オープンコンテスト)」

各問題名からのリンク先が、すべて「オープン」側になっています。
コンテスト名からのリンクは適切になっているみたいです。
（その他の「オープンコンテスト」も同様の状況っぽいです）

これらは問題は同一ですし、Problems 上での AC 判定も同一ですが、順位表や提出の情報が異なるので、
正しくリンクされている方が親切かと思います。

**Comment by tatt61880** [comment]
* 「第三回日本最強プログラマー学生選手権 -決勝-」
* 「第三回日本最強プログラマー学生選手権 -決勝- (オープンコンテスト)」

少なくともこれらに関しては正しく修正されているようです。クローズして問題なさそうです。
