### ISSUE TITLE
鉄則本に対応してほしい

### ISSUE THREAD

**Issue by peroon** [kenkoooo/AtCoderProblems#1290]
コンテスト(?)ページはこちらです。
https://atcoder.jp/contests/tessoku-book

対応可能でしょうか？

**Comment by hotate29** [comment]
Table > Other Contestsの一番下にあるものは違いますか？
![IMG_9949](https://user-images.githubusercontent.com/44938840/196503065-a3b9cb19-84c4-46f2-bb2d-941ba5e8ed62.png)

**Comment by peroon** [comment]
Issue時は多分なかったはずですが、鉄則コンテストは常設化に途中で変更されたので、表示されるようになったのだと思います。

https://twitter.com/kenkoooo/status/1580968985251573760

教えてくれてありがとうございます。Issueを閉じます。
