### ISSUE TITLE
Bacha Gachaで含めるコンテスト種別を指定したい

### ISSUE THREAD

**Issue by 1st-vil** [kenkoooo/AtCoderProblems#1295]
Difficultyが同じでもコンテスト種別（ABC,ARC,AGC）によって体感難易度が大きく異なる、ということがよく起こると思います。例えば「ABCの問題だけを集めたバチャを行いたい」といった需要もあると思うのでそのような機能の追加を提案します。

今のところは「Difficultyの指定されている問題が存在するコンテスト種別（ABC,ARC,AGC,AxC-Like,Other Sponsored）それぞれについてinclude/excludeのボタンを設置する」という形を想定しています。

**Comment by Eagle-Konbu** [comment]
@kenkoooo 
やってみました．
プルリクエストご確認いただければ幸いです．
