### ISSUE TITLE
AtCoderのユーザー名を変えたのですが、今までにACした問題が半分ほどしか反映されていません。どうすれば良いですか？

### ISSUE THREAD

**Issue by moomian** [kenkoooo/AtCoderProblems#1329]

**Comment by kenkoooo** [comment]
https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/faq_ja.md#atcoder-%E4%B8%8A%E3%81%A7%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E5%90%8D%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%97%E3%81%9F%E3%81%9F%E3%82%81%E5%85%A8%E3%81%A6%E6%B6%88%E3%81%88%E3%81%BE%E3%81%97%E3%81%9F
