### ISSUE TITLE
Problems in ABC293 aren't shown

### ISSUE THREAD

**Issue by EarthMessenger** [kenkoooo/AtCoderProblems#1373]
![abc293](https://user-images.githubusercontent.com/49364506/224494183-699c9b59-8acd-44a7-a761-811422216b0c.png)

![submission in abc293](https://user-images.githubusercontent.com/49364506/224494353-e343871d-e4d6-46ec-9ec6-1a3f6424bf2c.png)

As shown, there is no problem in ABC293. And in the submission page, the submissions to these problems doesn't have names.

**Comment by kenkoooo** [comment]
Thank you for reporting it. Let me fix it.
