### ISSUE TITLE
The page is not reflecting my submission now.

### ISSUE THREAD

**Issue by luojiawhu** [kenkoooo/AtCoderProblems#1402]
Hi kenkoooo,

Thanks for your effort on maintaining this great app. 

However, I just found that the page stopped reflecting the submissions I submitted. FYI that it still worked yesterday. 

When I inpect the page, I don't see any obvious error showing up as well. 

Hopefully this helps. 

Thanks again!

**Comment by amylase** [comment]
probably because our crawler is rejected by AtCoder?

https://twitter.com/atcoder/status/1648939398241853440

> 【おしらせ】コンテストの提出一覧ページを閲覧する際にログインが必須となりました。ページが見られないなどの問題に遭遇した方はログインをお試しください。

my translation for the reference is as follows:

> [Notification] Now you must be logged in to view the list of all submissions of the contest. If you encounter any problem such as being unable to view the page, please try logging in.

**Comment by luojiawhu** [comment]
For those who may want to keep tracking like me before this issue can be fixed, the form on the website can be simply copy/paste into the Googlesheet while all the titles, background(indicating status of submission) and hyperlinks are still working as expected. 

Hopefully the website can be fixed, but no rush :) 

Thanks again.

**Comment by kenkoooo** [comment]
Hopefully resolved.
