### ISSUE TITLE
ABC307のC問題は300点、Gは550点では？

### ISSUE THREAD

**Issue by hiro1729** [kenkoooo/AtCoderProblems#1413]

**Comment by kenkoooo** [comment]
中身を見ていないので分からないのですが、どうも[C問題は400点](https://atcoder.jp/contests/abc307/submissions/42836966)、[Gは625点](https://atcoder.jp/contests/abc307/submissions/42754131)らしいです。

**Comment by hiro1729** [comment]
その提出はコンテスト前のやつですか？今は300と550だと思いますが…
https://atcoder.jp/contests/abc307/tasks/abc307_c
https://atcoder.jp/contests/abc307/tasks/abc307_g

**Comment by Rubikun** [comment]
その問題への提出の点数の最大値を、problems上での問題の点数としていたと記憶しているのですが、今回のように準備陣が配点を適当につけたまま提出したものが残っているとおかしくなってしまうのだと思います(307-Cの400点の提出は消えてますが、今のままだと309-CDFでも同様のことになると予想しています)。

過去にFAを決めるときもそのような問題が起こっていて、それはコンテスト開始以降の提出のみを考慮するように変更することで解決したという記憶があるので、今回も同様にしたら解決するのではないかと思っています。

**Comment by kenkoooo** [comment]
ありがとうございます！それが良さそうです。

**Comment by Rubikun** [comment]
やはり309の配点もおかしくなってますね。
すみませんが僕には修正厳しいのでどなたかにやっていただきたいですm(__)m
