### ISSUE TITLE
ABC314's problems aren't displayed on the home page

### ISSUE THREAD

**Issue by EarthMessenger** [kenkoooo/AtCoderProblems#1423]
On the home page, there are no problems in the contest ABC314. 

![图片](https://github.com/kenkoooo/AtCoderProblems/assets/49364506/066764be-40eb-4ecd-a167-2f27c83af2f7)

But on the submission page, the problems in that contest and their ratings are displayed correctly.

![图片](https://github.com/kenkoooo/AtCoderProblems/assets/49364506/c8d1b572-22e3-4125-9d40-75c6a34e455a)

**Comment by kenkoooo** [comment]
Looks like it's resolved. Ctrl-Shift-R will resolve your issue.
