### ISSUE TITLE
Languagesに"C++"と"C++ "(末尾に半角スペース)の2種類が存在している

### ISSUE THREAD

**Issue by dehachi** [kenkoooo/AtCoderProblems#1424]
# 概要
[https://kenkoooo.com/atcoder/atcoder-api/v3/language_list](https://kenkoooo.com/atcoder/atcoder-api/v3/language_list)に"C++"と"C++ "(末尾に半角スペース)の2種類が存在しています。

# 原因
[https://github.com/kenkoooo/AtCoderProblems/blob/5737038b54891f61956031809d2e5ee2c1409a19/atcoder-problems-frontend/src/utils/LanguageNormalizer.ts](https://github.com/kenkoooo/AtCoderProblems/blob/5737038b54891f61956031809d2e5ee2c1409a19/atcoder-problems-frontend/src/utils/LanguageNormalizer.ts)
AtCoderの言語アップデートにより、normalizeLanguageに不具合が生じています。具体的には、

```js
normalizeLanguage("C++ (GCC 9.2.1)") // 言語アップデート前
-> "C++"
normalizeLanguage("C++ 20 (gcc 12.2)") // 言語アップデート後
-> "C++ "
```

のようになっています。

# 解決策
- ```language.startsWith("C++")```の場合"C++"を返すようにする。
- ```language.replace(/\d*\s*\(.*\)$/, "")```を```language.replace(/\s*\d*\s*\(.*\)$/, "")```に変更する。

**Comment by hiro1729** [comment]
ついでにPythonとPyPyとCythonを合わせて欲しいです！

**Comment by hotate29** [comment]
@hiro1729 正直なところ、PythonとCythonは合わせるべきでないと思います。名前こそ似ていますが、Cの文法を取り入れた静的な型付けなど、言語としては別物だからです。
一方、AtCoderの新環境では”Python (Cython 0.29.34)”と表示されており、これはPythonと合わせる根拠になりえます。ただ、旧環境では”Cython (0.29.16)”と表示されているので扱いが難しいかもです。

**Comment by hiro1729** [comment]
確かにそうでしたね。PythonになくてCythonにある機能もあるので分けるべきでした
