### ISSUE TITLE
最新のコンテスト名のセルが緑に塗られている

### ISSUE THREAD

**Issue by VeyronSakai** [kenkoooo/AtCoderProblems#1426]
この画像のように「ABC319」のセルが緑に塗られていることを確認しました。

<img width="1510" alt="Screenshot 2023-09-10 at 1 47 45" src="https://github.com/kenkoooo/AtCoderProblems/assets/43900255/5c09804f-0f27-49c7-9715-9dae21a1a4f8">

**Comment by hiro1729** [comment]
コンテスト直後は毎週そのようになっていると思います。

**Comment by kenkoooo** [comment]
duplicated: https://github.com/kenkoooo/AtCoderProblems/issues/1427
