### ISSUE TITLE
AGC-Likeタブの先頭に現状存在しないコンテストが表示される

### ISSUE THREAD

**Issue by H20-DHMO** [kenkoooo/AtCoderProblems#1432]
[TIHO_SAMPLE_01](https://atcoder.jp/contests/tiho_sample_01)というコンテストが先頭に表示されていますがAtCoderのページには現在存在しません。

![AGC-Like](https://github.com/kenkoooo/AtCoderProblems/assets/51841084/be7ac880-aa87-47ae-b012-076da537c926)

**Comment by idat50me** [comment]
Googleのキャッシュに残っていました。
![image](https://github.com/kenkoooo/AtCoderProblems/assets/59227194/fbd2c63d-44fa-4675-8187-6841ff5ec4bd)

**Comment by kenkoooo** [comment]
消しといたので、そのうち良い感じになるはず

**Comment by idat50me** [comment]
やったぜ
![image](https://github.com/kenkoooo/AtCoderProblems/assets/59227194/d161f383-b3fc-4375-b418-6cfd014a4d45)

**Comment by H20-DHMO** [comment]
直ってますね。
ありがとうございます！
