### ISSUE TITLE
コンテスト開始前の提出（writer解など）が認識されないことがある

### ISSUE THREAD

**Issue by riano-17** [kenkoooo/AtCoderProblems#1433]
表題の通りですが、ARC164-Aのwriter解提出が認識されていないようです
（提出：https://atcoder.jp/contests/arc164/submissions/43299007 ）
提出を公開したのがコンテスト後でしたので、その影響かもしれませんが、
B以降もほぼ同じタイミングで公開したのでなぜAだけ認識されないかは不明です
![image](https://github.com/kenkoooo/AtCoderProblems/assets/76549863/78e7b53c-c45b-42c4-bde1-ad355b7e5d6d)

**Comment by kenkoooo** [comment]
クローラーは以下の3種類の実装が稼働中です。
1. 各コンテストの最新の提出をクロールして回る
2. 直近のコンテストの提出を根こそぎクロールして回る
4. 全てのコンテストの全ての提出をクロールして回る

おそらく公開したタイミングによって上2つに漏れたのではないかと思われるので、全てのコンテストの全ての提出をクロールするクローラーが見つけるのを待つ他ありませんが、現在 AtCoder にある提出が 45925222 件で、1ページに20件の提出があり、1秒で1ページクロールしていくとすると、全部見るのに26日くらいかかる計算になります。この26日のどこかでARC164を根こそぎクロールする時間があるはずですが、それがABCと被ったりすると、接続を切られたりとか色々あるので、もっと遅くなったりしそうです。

短期的な解決策: 信じて待つ
長期的な解決策: クローラーの実装を改良する

**Comment by riano-17** [comment]
ありがとうございます！一旦信じて待ちます
（あと、次があれば公開を忘れないように気をつけます）

**Comment by riano-17** [comment]
解消していました

**Comment by kenkoooo** [comment]
やったぜ
