### ISSUE TITLE
ユーザーページの`All`タブへのリンクが機能しない

### ISSUE THREAD

**Issue by your-diary** [kenkoooo/AtCoderProblems#1457]
ユーザーページの`Difficulty Pies`, `All`といったタブのURLを開いたとき、真っ白なページが表示されます

`Achievement`タブや`AtCoder Pie Charts`タブは正常に機能します

macOS版Firefox, Chromeで再現

前は確実に動いていて、おそらく3ヶ月前〜1ヶ月前から動かなくなっています

## 再現方法

1. 任意のユーザーの`All`タブのページにアクセス(例: https://kenkoooo.com/atcoder/#/user/YourDiary?userPageTab=All)

2. 真っ白なページが表示される

## Workaround

1. まず、`Achievement`タブのページにアクセス(例: https://kenkoooo.com/atcoder/#/user/YourDiary?userPageTab=Achievement)

2. `All`タブに手動で移動

3. ちなみに、ここでブラウザをリロードすると真っ白な画面になる(`Cmd+Shift+r`によるforce refreshでも同様)

**Comment by hotate29** [comment]
DifficultyPieChartコンポーネントでエラーが起きているようです。

内部では`contestMap = useContestMap()`という形で`contest.json`の情報を受け取っています。`useContestMap()`は`contest.json`を読み込んでいる間はundefinedを返すようになっており、`contestMap`がundefinedになる可能性があります。これを確認せずに`contestMap.get()`を呼び出してしまい、エラーが発生。という流れのようです。

https://github.com/kenkoooo/AtCoderProblems/blob/163bb9614c405540190e221df7bb10d753347290/atcoder-problems-frontend/src/pages/UserPage/DifficultyPieChart/index.tsx#L36-L45

対応としては、他のコンポーネント（MyAccountPageなど）の例に倣って読み込み中の表示を出すようにするとかでしょうか。

この処理は b49bac15b970cb613a734c063240be5711d12d57 で追加されたようです。PRのマージと発生時期が概ね一致していますね（デプロイまでの時間もあるので、即反映という事ではないとは思いますが）。

しかしこういうのってlintに引っかかったりしませんかね。手元のVSCodeでは警告が出たのですが、`yarn lint`しても何も出ませんでした。TypeScriptのlint事情はよく知らないのでちょっと調べてみます。

**Comment by kenkoooo** [comment]
@your-diary @hotate29 #1369 を一旦リバートしました！調査ありがとうございます！！！

**Comment by your-diary** [comment]
@hotate29 調査ありがとうございます！
@kenkoooo ご対応ありがとうございます！

リンクが機能するようになったことが確認できたため、close致します。
