### ISSUE TITLE
some data is not synchronized after the user name change

### ISSUE THREAD

**Issue by rainlycoris** [kenkoooo/AtCoderProblems#1461]
My guess is that recrawling the data will solve this problem.
Can you add a feature like this? Thanks.
My original atcoder account name was liudonglin_, now it is DaydreamWarrior.

**Comment by kenkoooo** [comment]
The recrawling feature has already been implemented. It continuously recrawls the submissions, but due to the enormous number of submissions, it takes 2-3 weeks to recrawl all of them. Please be patient.

**Comment by rainlycoris** [comment]
> The recrawling feature has already been implemented. It continuously recrawls the submissions, but due to the enormous number of submissions, it takes 2-3 weeks to recrawl all of them. Please be patient.

Thank you very much!!!
