### ISSUE TITLE
Rated Point Sum のバグ

### ISSUE THREAD

**Issue by sortA0329** [kenkoooo/AtCoderProblems#1464]
[僕のプロフィール](https://kenkoooo.com/atcoder/#/user/sortA)のRated Point Sumの値がとても大きな値(現在1509389050)になっています。Rated Point Rankingは正常なようです。

**Comment by hotate29** [comment]
`asprocon10_a`（37078900点）と`asprocon10_b`（1472090400点）の得点が足された結果かなと思います。

このissue（#1429）の問題がフロントエンドでも起きているようです。コンテストがAlgo Ratedかを判定する条件が変更され、バックエンド側のコードが更新されたのですが、フロントエンド側にあった同様の処理が漏れてしまったようです。これを修正したらとりあえず解決できそうです。

https://github.com/kenkoooo/AtCoderProblems/blob/37e64781e37e7b0332cc8fe54e99d38ff0229d3e/atcoder-problems-frontend/src/utils/ContestClassifier.ts#L23-L32

AchievementのタブでRated Point Sumを取得する処理では、`isRatedContest()`を使って自前で計算しています。

https://github.com/kenkoooo/AtCoderProblems/blob/37e64781e37e7b0332cc8fe54e99d38ff0229d3e/atcoder-problems-frontend/src/pages/UserPage/AchievementBlock/index.tsx#L77-L97

これとは別に、この部分でバックエンドからRated Point Sumの順位を取得しています。レスポンスにはRated Point Sumが含まれるので、こっちを使うようにしても良いかもしれません。

https://github.com/kenkoooo/AtCoderProblems/blob/37e64781e37e7b0332cc8fe54e99d38ff0229d3e/atcoder-problems-frontend/src/pages/UserPage/AchievementBlock/index.tsx#L98-L99

https://github.com/kenkoooo/AtCoderProblems/blob/37e64781e37e7b0332cc8fe54e99d38ff0229d3e/atcoder-problems-backend/src/server/ranking/rated_point_sum.rs#L32-L55
