### ISSUE TITLE
Python入門(APG4bPython)の提出結果が反映されない

### ISSUE THREAD

**Issue by your-diary** [kenkoooo/AtCoderProblems#1469]
[C++入門(APG4b)](https://atcoder.jp/contests/APG4b)の提出結果は反映されるのですが、[Python入門(APG4bPython)](https://atcoder.jp/contests/APG4bPython)の提出結果が反映されません。

ただし、以下のようなことを「反映されない」と言っています。

- `User`ページの`Submissions`タブに表示されない

- AC数にカウントされない

**Comment by hotate29** [comment]
AC数はわからないですが、Submissionタブには表示されているように見えます。

https://kenkoooo.com/atcoder/#/user/YourDiary?userPageTab=Submissions
