### ISSUE TITLE
コンテスト中と、コンテスト後にACした問題が、同一種類の緑色で塗られてしまう

### ISSUE THREAD

**Issue by AkihiroSasabe** [kenkoooo/AtCoderProblems#1472]
いつも大変お世話になっております。  
コンテスト中にACした問題も、コンテスト後にACした問題も、どちらも同一種類の緑色で塗られて、識別出来ないときがありますが、原因は分かりますでしょうか?  

例えば自分はABC352で、A-Dはコンテスト中にACしましたが、Eはコンテスト中にACすることが出来ずコンテスト後にACしました。  
正常に動作している場合、コンテスト中にACしたものは濃い緑色で、  
コンテスト後にACしたものは薄い緑色で表示されていたと思いますが、  
現在は下の画像のように、コンテスト中 or コンテスト後にACしたかに関係なく、単一の緑色で塗られています。   
ブラウザはChromeで現時点(2024-05-05)で以下の最新バージョンを使用しております。  
バージョン: 124.0.6367.119（Official Build） （64 ビット）  

![image](https://github.com/kenkoooo/AtCoderProblems/assets/34682532/3bc86c01-664e-4681-9654-eb8c02cc5e1f)    

また、ABC351, ABC352は、問題の配点がセルの右下に記載されていないのですが、こちらも原因は分かりますでしょうか。

お忙しいところ恐縮ですが、ご回答いただければ幸いです。何卒宜しくお願い致します。

**Comment by hotate29** [comment]
Color Byの部分は「Contest Result」に設定されていますか？

自分の環境では再現できておらず、どういう設定かなどの情報もいただけると嬉しいです。

（スマホでのスクリーンショットですが、概ね一緒なはず）
![IMG_7104](https://github.com/kenkoooo/AtCoderProblems/assets/44938840/16f7ae38-4b2e-4748-aa84-7f89446cc81b)

**Comment by AkihiroSasabe** [comment]
@hotate29 様  
早速ご回答いただき、どうもありがとうございます。  
自分の`Color By`の項目は、デフォルトのまま未設定でした。`Contest Result`に設定したところ、コンテスト中にACしたか否かが色の濃淡で識別できるようになりました。  
お陰様で大変助かりました。こちらの確認不足でお手数をお掛けしてしまい申し訳ございません。
