### ISSUE TITLE
Problem List の一部が更新されていない

### ISSUE THREAD

**Issue by potato167** [kenkoooo/AtCoderProblems#1473]
Problem List の solver 数や fastest 等が表示されていないもしくは更新されていない状態に見えます

**Comment by kenkoooo** [comment]
ありがとうございます！急ぎ確認します！

**Comment by kenkoooo** [comment]
今月の予算が尽きて集計をぶん回すジョブが止まってました！いったん追加課金したのでたぶん大丈夫になったと思うのですが、ちょい様子見です…

**Comment by kenkoooo** [comment]
直ったっぽいっすね！超助かりました！また何かあったら教えてください！
