### ISSUE TITLE
ABC356 の first AC が違う

### ISSUE THREAD

**Issue by potato167** [kenkoooo/AtCoderProblems#1474]
21:20:17 以降の提出の中で一番早いものが FA になっている気がしています。

**Comment by hotate29** [comment]
提出のクロール自体はできているようなので、batch_updateが止まっているかもです

**Comment by kenkoooo** [comment]
batch_update が動いていない問題は https://github.com/kenkoooo/AtCoderProblems/issues/1473 でなんとかしたので現在は動いているっぽく、原因は謎です…
とりあえずクラスタを再起動したので、祈り…（ダメそうだったらちゃんとデバッグします…）

**Comment by potato167** [comment]
今見たら直ってそうでした
ありがとうございます

**Comment by kenkoooo** [comment]
確認ありがとうございます！データの同期が失敗してたかもですね…
