### ISSUE TITLE
faviconが表示されない

### ISSUE THREAD

**Issue by Yang-33** [kenkoooo/AtCoderProblems#149]
https://kenkoooo.com/atcoder/favicon.ico が表示されていないと思います。
https://old.kenkoooo.com/atcoder/images/favicon.ico は表示されるので新verに移行する際に起きた事だと思います。

同様にhttps://kenkoooo.com/atcoder/apple-touch-icon.png も表示されていないように思います。

どうして表示されていないかはぱっと見よくわかりませんでした。

**Comment by kenkoooo** [comment]
ファイルが存在しないわけではないので、よくわかりませんでした。

**Comment by kmyk** [comment]
両方とも画像が壊れています。データの壊れ方 (特にPNGのmagic number) から推測すると、画像が無理矢理 UTF-8 としてエンコードあるいはデコードされてしまっているように見えます。

もう一度すべての画像を (テキストでなく) バイナリファイルとしてアップロードしなおすのと、間にはさまっているキャッシュサーバの確認が必要そうです。

**Comment by kenkoooo** [comment]
`https://kenkoooo.com/atcoder/{path}` へのアクセスは `http://kenkoooo.com.s3-website-ap-northeast-1.amazonaws.com/{path}` へのアクセスになります。これをやっているのは API Gateway というサービスです。http://kenkoooo.com.s3-website-ap-northeast-1.amazonaws.com/favicon.ico が生きていることから、保存されているファイルが壊れているのではなく、 API Gateway が無理やりテキストにしているのが原因っぽいです。

**Comment by kenkoooo** [comment]
では API Gateway をうまいこと設定すればよさそうなのですが、ドキュメントどおりに設定しても結果が変わらず、という感じです。

**Comment by kenkoooo** [comment]
`Use HTTP Proxy integration` をアンチェックして Integration Response を `Convert to binary` にしたら動きました。

**Comment by kenkoooo** [comment]
この方法だとリクエストヘッダに `Accept` がない場合は正しく動かないらしいです。うーん…

**Comment by kenkoooo** [comment]
https://9txzgx8cl0.execute-api.ap-northeast-1.amazonaws.com/atcoder-problems-2/atcoder/apple-touch-icon.png
が API Gateway を通したあとのアドレスなのですが、 `Accept` をリクエストヘッダに入れればちゃんと表示されるので、それを使って解決したいです。

**Comment by kenkoooo** [comment]
icon 用に別のエンドポイントを切ったら行けました。
