### ISSUE TITLE
バトルがバグってる

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#21]
https://twitter.com/Kazuki_Ashiya

**Comment by kenkoooo** [comment]
https://twitter.com/koyumeishi_/status/757694363807854592

**Comment by koyumeishi** [comment]
そのページで比較してるのはリニューアル後の rated なコンテストだけなので完全な代替ではないですよー
例えば ARC063 はすぎむさん参加してるけどレーティング変動対象外なので表示されてないです（そのうち修正したくはあるけど……

**Comment by kenkoooo** [comment]
ありがとうございます！（まさか見ていただけるとは・・・）

**Comment by kenkoooo** [comment]
これを直取りしに行くのが楽そう
http://code-festival-2016-quala.contest.atcoder.jp/standings/json
