### ISSUE TITLE
日本以外のタイムゾーンからだと現地時間に合わないユーザ記録となる

### ISSUE THREAD

**Issue by solzard** [kenkoooo/AtCoderProblems#228]
[Force JST in the streak counting · Issue \#223](https://github.com/kenkoooo/AtCoderProblems/issues/223)の修正により、日本国外からのアクセスであっても、submissionsのエポック秒が強制的にJSTでの時刻として解釈されるようになりました。
それにより、現地時間では毎日ACしていたとしてもAtCoder Problemsの記録上はACしなかった日があると判断されることがあります。(下図参照)
```
o: ACのエポック秒
|: そのタイムゾーンでの00:00(日付変更)
-------------------------------------
   o   o o     o o   o   o     o  o
| 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | (Another time zone)
  | 1 | 2 | 0 | 2 | 1 | 1 | 0 | 2 |   (JST)

JSTではAC数がゼロの日があると見做される
```
[DateUtil\.ts](https://github.com/kenkoooo/AtCoderProblems/blob/0bac38c5b7b75215e767c49d0569c5e9ee0ad726/atcoder-problems-frontend/src/utils/DateUtil.ts)で定義されている`JST_OFFSET`がparseSecond, parseDateLabel関数に使われ、それらが他のコードで日毎のAC数やcurrent streakの判定に使われているようです。
タイムゾーンを定数として固定せず、ユーザの現在のタイムゾーンを`CURRENT_OFFSET`のように取得し、それをJSTの代わりに使えば改善されるのではないかと考えます。
TypeScriptもJavaScriptも基本的な文法しか知らないので、間違っていたらすみません。

**Comment by kenkoooo** [comment]
海外ユーザーが非常に少ないので、貴重なフィードバックありがたいです。タイムゾーンをJSTに矯正していたのですが、これはブラウザのタイムゾーンに任せてしまったほうが良いですかね？

**Comment by solzard** [comment]
そのほうが良いとも思います。
Streakが現地時間で適切に感じられてモチベーションが保てるので、ユーザの時間に合わせていただいたほうが個人的にも嬉しいです。

**Comment by kenkoooo** [comment]
:+1:

**Comment by solzard** [comment]
👍
