### ISSUE TITLE
複数ライバルの比較が動いていない

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#24]
トップページの `ライバル:` のtextboxのplaceholderに `User ID,User ID,User ID,...` とあり複数比較ができるように見えるのですが、動作しません。
ライバルの欄を空白(あるいは存在しないユーザを入れたとき)と同様の挙動をします。
例: http://kenkoooo.com/atcoder/?name=kimiyuki&rivals=kenkoooo%2Cchokudai&kind=index

(元々未実装でなくて) バグならば修正をお願いしたいです。

**Comment by kenkoooo** [comment]
resolved

**Comment by kmyk** [comment]
betaの方で動いてるの確認しました。ありがとうございます。
