### ISSUE TITLE
/info/merged-problems が 500 してる

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#241]
https://kenkoooo.com/atcoder/atcoder-api/info/merged-problems が `{"message": "Internal server error"}` を返します。
現状は endpoint としては `merged-problems.json` が推奨のようですが、API の破壊的変更があったにしても 404 でなくて 500 なのはなにか変です。なにか設定ミスがあったりしないか確認してほしいです。

**Comment by kenkoooo** [comment]
fixed
