### ISSUE TITLE
Limited recommendations

### ISSUE THREAD

**Issue by FMota0** [kenkoooo/AtCoderProblems#267]
Eventually the user recommendations sections become equal, so there is no difference between easy, moderate and difficult. Could this be handled in such a way that the user receive more recommendations in this case ?

You can see this happening on my recommendations https://kenkoooo.com/atcoder#/user/FMota

**Comment by FMota0** [comment]
@kenkoooo I propose to have a dynamic `recommendingProbability` on https://github.com/kenkoooo/AtCoderProblems/blob/961d535b9fd424372033224e73280cbba0ae780c/atcoder-problems-frontend/src/pages/UserPage/Recommendations.tsx#L80 by default we initially desire by this values, but we also consider the respective quartiles of `predictedSolveProbability` and take the minimum of them. What do you think about it ?

**Comment by kenkoooo** [comment]
Thank you for the suggestion. In my opinion, it's better not to use quartiles to choose the problems to solve, because most of users of our service didn't solve so many problems and the value is not useful for them. If we can set the value of the probability dynamically, that can be useful for some people. But we don't need to do so, since it's more important for us to keep our service easy to use.

**Comment by FMota0** [comment]
Yeah, I see it now, I didn't thought from this point of view

**Comment by FMota0** [comment]
![Captura de Tela 2019-10-02 às 12 26 58](https://user-images.githubusercontent.com/29783962/66058049-12d99e80-e510-11e9-941c-17f9b1190964.png)
What do you think about this ? I though about just using the table pagination, but it would change how to keep the elements sorted.

**Comment by kenkoooo** [comment]
> ![Captura de Tela 2019-10-02 às 12 26 58](https://user-images.githubusercontent.com/29783962/66058049-12d99e80-e510-11e9-941c-17f9b1190964.png)
> What do you think about this ? I though about just using the table pagination, but it would change how to keep the elements sorted.

Yeah, that's the thing I thought. 
But anyway, the recommendation of unsolved problems is not useful for the heavy-users, who already solved almost all the Easy & Moderate recommended problems...

**Comment by kenkoooo** [comment]
Resolved in  #269
