### ISSUE TITLE
KUPC が ◉ になってる

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#295]
AtCoder 側の更新の影響でコンテストタイトルの取得に失敗し ていそうです。

<img width="1052" alt="Annotation 2019-10-14 202732" src="https://user-images.githubusercontent.com/2203128/66748044-192d2a80-eec1-11e9-89ea-73dbf0dc9ee9.png">

**Comment by kenkoooo** [comment]
https://github.com/kenkoooo/algorithm-problem-client/pull/2 これの変更を取り込んだ変更が反映されたので直りました。
