### ISSUE TITLE
高速化されてほしい

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#298]
普通にトップページにアクセスすると、表示までが遅くてつらいです。
更新ボタンを連打して RDB のデータをすべて RAM に乗せた状態で 3 秒程度、[魔法のURL](https://kenkoooo.com/atcoder/#/table/kmjp/beet/ei13333/Pulmn/E869120/latte0119/tozangezan/smiken/TangentDay/kobae964)にアクセスしてサーバ上のキャッシュ状況をリセットした直後だと 20 秒以上かかります。

明らかに提出数 N に対し O(N) 時間がかかっています。O(1) か O(log N) ぐらいでやってほしさがあります。

<img width="671" alt="Annotation 2019-10-15 023211" src="https://user-images.githubusercontent.com/2203128/66771110-53fc8600-eef4-11e9-906d-d9b77abb841e.png">

**Comment by kmyk** [comment]
@kenkoooo 改善手法の選択肢は主に以下の 4 つのはずです。やるとすればどれがよいと考えていますか？
(4.) は Problems に依存する他サービス (例: AtCoder Scores) とかがつらくなるのでよくないはず。個人的には設計として適切な (1.) か (3.) がおすすめです。

1. テーブルの各行に最終更新時刻を持ってそれを ETag とすると O(log N) ぐらい
1. ETag を乱数にしてそれ用のテーブルに保存しておき、新しいデータが見つかるたびに更新すると O(1)
1. ETag を乱数にして Redis サーバを建ててそこに入れておき、新しいデータが見つかるたびに削除/更新すると O(1)
1. Time-based Submission API を使うようにして results を使わない

**Comment by kenkoooo** [comment]
すみません、確認なのですが ETag の計算に時間がかかっていそうなので何とかした方が良いという話ですか？

**Comment by kmyk** [comment]
はい
(その部分を書き忘れていました :bow:  304 が返ってきているのに遅いので ETag だと判断しています。)

**Comment by kenkoooo** [comment]
ありがとうございます。個人的には DynamoDB 使ってみたさがあるので 3 をやってみたいなぁと考えています。

**Comment by kmyk** [comment]
ところで Amazon DynamoDB とかなり似たサービスとして Amazon ElastiCache があり、こちらも検討してみてください。おそらくどちらでも目的は達成できますが、料金は違うはずです。

**Comment by kenkoooo** [comment]
結局 SQL に提出数カウント用のテーブルを1つ追加することで解決しました。

**Comment by kmyk** [comment]
ちゃんと速くなってました。ありがとうございました。
