### ISSUE TITLE
Layout for phones is ugly

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#302]
![Screen Shot 2019-10-18 at 13 26 49](https://user-images.githubusercontent.com/9150073/67065887-f9408400-f1aa-11e9-9dc7-cd8cc0309bc1.png)

**Comment by garasubo** [comment]
bodyのpaddingに70px持って行かれているのと、そもそもコンテストの問題名を横に並べようとするのが無理があると思われます。
mobileのユーザーエージェントに対して全く違うJSを返すことでUIを変えるとかしたほうがいいと思います
