### ISSUE TITLE
レーティングシステムが導入される前の問題の難易度推定

### ISSUE THREAD

**Issue by amylase** [kenkoooo/AtCoderProblems#317]
現在はAtCoder公式の内部レーティングを使って難易度推定をしているので、レーティングシステムが導入される前の問題には難易度がついていません。
サービス開始時点からレーティングシステムがあったものとしてレーティング変化を手元で再現すると、その結果を用いて古い問題にも難易度が推定できると考えられます。

**Comment by kenkoooo** [comment]
Resolved in #318
