### ISSUE TITLE
ARC086F や ARC066F などに難易度の円が付いてないのはなぜですか？

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#350]
もしこれが「データが足りなくて推定ができない」のような理由なら :warning: とか :grey_question: とかなんでもよいのでなにか表示しておいてほしいです (なにも表示がないとバグっぽく見えて不安な気持ちになるので)
もしこれがバグなら、バグです

**Comment by amylase** [comment]
それらの問題はコンテスト中に誰も解いてないので難易度が推定できなくなっています。ほかにも、そもそもコンテスト参加者数が少ない場合や、推定アルゴリズムの出力が怪しい（たとえばレーティングが上がるほど正解確率が下がるなど）ときは推定難易度はつけていません。

一般にこういった理由で難易度がついてないときにそれをアナウンスするのはよいアイデアですね。
