### ISSUE TITLE
旧ARC/ABCの難易度推定で部分点が何かに使われている

### ISSUE THREAD

**Issue by tozangezan** [kenkoooo/AtCoderProblems#360]
例 スプリンクラー(difficulty: 3797): https://atcoder.jp/contests/arc022/standings

**Comment by amylase** [comment]
難易度推定では満点の人だけをACとするようにしているのですが、実は問題の満点を取得する手段がないので、一番点数が高い人の点数を満点としていることによります。ARC022-Dの場合は60点の難易度が推定されてしまっています。つまりバグです。
