### ISSUE TITLE
ABC110 A、ABC126 A,B などに難易度の円が付いてないのはなぜですか？

### ISSUE THREAD

**Issue by tozangezan** [kenkoooo/AtCoderProblems#361]
difficultyが負数になったんじゃないかとふんでいる

**Comment by tozangezan** [comment]
ん、なんか　「推定アルゴリズムの出力が怪しい（たとえばレーティングが上がるほど正解確率が下がるなど）」な気も。

**Comment by kenkoooo** [comment]
そうですね。 #350 と同じだと思います。ちなみに difficulty は実際のコンテストのパフォーマンスと同じように負にならないように補正が入っています。

**Comment by amylase** [comment]
あまりに正解者数が不正解者数に比べて多くても推定アルゴリズムの挙動が安定しなくて死にます。したがって、これも #350 と同じです。

**Comment by kenkoooo** [comment]
#350 を残してこれは閉じますね
