### ISSUE TITLE
ログインしているときにユーザーページの導線があるとうれしい

### ISSUE THREAD

**Issue by garasubo** [kenkoooo/AtCoderProblems#380]
ログインしてかつアカウントIDが登録されている状態の場合、ワンクリックでユーザーページに飛べる導線があると嬉しいなと思いました。
#/login/user以下のタブにユーザーページを追加するか、トップバーのユーザーIDのデフォルト値が埋まっている（#374）とよさそう？

**Comment by kenkoooo** [comment]
Resolved in #404
