### ISSUE TITLE
difficulty、Chromeだとクリックしないとポップアップされないことがあるみたいです。前はマウスオーバーでも出てた気がするんですが。

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#384]
https://twitter.com/hotpepsi/status/1212645583409729539

**Comment by firewood** [comment]
関係あるかわからないですが、試しにアイコンを大きくしてみたら動きました。あとなぜかdeveloper consoleを開いた状態だと動きます。
