### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by vvataarne** [kenkoooo/AtCoderProblems#39]
# 問題
別オリジンからAPIにXHRを送るとSame-Origin Policyに引っかかってデータを取得することができません

# 解決策
サーバーサイドで任意のオリジンからのアクセスを許可するようにCORS関連のhttpヘッダーを設定してくださるとありがたいです

**Comment by kenkoooo** [comment]
レスポンスヘッダに `Access-Control-Allow-Origin: *` を入れるので事足りますか？

**Comment by vvataarne** [comment]
はい、それを入れるだけでデータを取得することができるようになると思われます。

**Comment by kenkoooo** [comment]
了解です。次のデプロイで対応します。

**Comment by kenkoooo** [comment]
ちなみに、もし急ぐようでしたら、プルリクを送っていただいても構いません。
Akka-HTTP で実装されていて、 `JsonApi.scala` を変更するだけで実装できそうです。
https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-backend/src/main/scala/com/kenkoooo/atcoder/api/JsonApi.scala

**Comment by kenkoooo** [comment]
デプロイ完了です

**Comment by vvataarne** [comment]
データを取得できることを確認しました。対応ありがとうございます。
