### ISSUE TITLE
デフォルトユーザーIDの時に UserPage に遷移しても提出をfetchしない

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#405]
#404 で入った機能が動いていない

**Comment by kmyk** [comment]
これってどこがまずかったですか？

**Comment by kenkoooo** [comment]
NavigationBar の `updateUserIds` にも userId を渡さないと動かない仕様でした。これは NavigationBar が崩壊しているのが良くないので、そのうち直します……

**Comment by kmyk** [comment]
なるほど。それで #406 なんですね
