### ISSUE TITLE
言語フィルタの需要について

### ISSUE THREAD

**Issue by n4o847** [kenkoooo/AtCoderProblems#414]
指定した言語で AC した問題に色を付けるという拡張機能を作っています。

https://greasyfork.org/ja/scripts/375857-atcoder-problems-language-filter

一部の人には需要があるようですが、公式の機能としての需要はあるでしょうか？

![image](https://user-images.githubusercontent.com/22975590/73132364-7490bc00-405d-11ea-8705-85c0a865ea20.png)

**Comment by kenkoooo** [comment]
一部の人には需要はあると思います。デフォルトの機能として搭載されているべきかどうかは分かりませんが、そういったことを特に考えずに自分が欲しい機能を全部入れているようなアプリケーションなので、個人的にはあまり気にしなくて良いと思います。

**Comment by kenkoooo** [comment]
https://twitter.com/ninoinui/status/1224809073234759680

**Comment by n4o847** [comment]
ありがとうございます。
とりあえずの実装をしてみたのでそちらに移行して、ここは close します。
