### ISSUE TITLE
Table 表示時の Colorful Mode が分かりにくい

### ISSUE THREAD

**Issue by Pro-ktmr** [kenkoooo/AtCoderProblems#428]
Table 表示時に使用可能な機能 Colorful Mode ですが、何か派手な装飾でもされるのかな？と思いつつ、ポチポチしても画面内に変化が現れません。
スクロールしてみてようやく、コンテストに実際に参加した際のタイムが表示される機能であることが分かりました。長らくコンテストに出ていないと、何の機能なのか分かりにくいように思います。

これについて、下記 2 点の提案があります。
・ヘルプをつける
Show Difficulty と同様に、何についての機能なのかを確認できるようにすることで、この問題は解決されます。
・名称を変更する
Show Contest Result といった、別の分かりやすい名称に変更することでも、この問題は解決されます。ただし、その名前が分かりやすいかは人それぞれだと思います。

**Comment by kenkoooo** [comment]
Show Contest Result いい名前だと思います
