### ISSUE TITLE
バチャ時のパフォーマンス計算について

### ISSUE THREAD

**Issue by nanigasi-san** [kenkoooo/AtCoderProblems#455]
バチャ時の推定パフォーマンスについてなのですが、もしかしたらコンテストの開始時間ではなくて初提出時からの計算になっている気がします(31分400点より35分400のほうがパフォが高くなっている)

該当コードがわからなかったのであやふやで申し訳ないのですが、できれば対応よろしくお願いします。

#### 画像
![image](https://user-images.githubusercontent.com/44631106/75235370-776b0200-57ff-11ea-9577-46a2ef93d5be.png)

#### 該当バチャ
https://kenkoooo.com/atcoder/#/contest/show/609b678a-3d81-45fc-af86-fbb8baff4718

**Comment by kenkoooo** [comment]
1つ前の問題を解き終わった時刻からの時間で計算しています。なので、潜伏して一気に提出したりすると跳ね上がります。

**Comment by nanigasi-san** [comment]
なるほど、そういうシステムなんですね
個人的にはバチャ開始時間からの計算のほうが嬉しいな～と思うのですが、その方式に切り替える、あるいは選べるようにする予定などはありますか？

**Comment by kenkoooo** [comment]
ここでの問題は「最終的に問題を解き終わった時刻が遅いユーザーの方が推定パフォが高くなることがある」ということだと思いますが、各問題についてコンテスト開始時からの経過時間を使っても、これは解決しないかと思います。

**Comment by amylase** [comment]
レーティング推定に使う統計モデルを「解いた問題とかかった時間の合計」のみに依存するように変えることは理屈の上では可能ですが、私には具体的にどうすればいいかすぐにはわからないです。
解いた問題全てに対する解答時間予測モデルを組み合わせて和の分布を計算すればそこからレーティングを最尤推定できるように思います。しかし、その解答時間予測モデルが対数正規分布でその和の分布は解析的には書けない（たぶん）ので何かしらのテクが必要になると思います。

**Comment by nanigasi-san** [comment]
なるほど...

現状で
> レーティング推定に使う統計モデルを「解いた問題とかかった時間の合計」のみに依存するように
なっているのだと誤解していました。


個人的にバチャをしていて気になってissueにしたのですが、バグではないなら仕様として使わせていただきたいと思います

ご丁寧にありがとうございました。

**Comment by amylase** [comment]
貼っていただいたスクショのケースは実際違和感がありますし、提案していただいたように合計時間のみを使うようにすると潜伏で推定パフォーマンスがおかしくなる問題を直せるので、この issue 自体は意味あるものだと思います。Open のままにしておいて、いい方法を思いついたら fix するといいのではないかと考えます。

**Comment by nanigasi-san** [comment]
はい。
技術力が無く開発自体のお手伝いは全くできないのですが、issue自体はこのままopenさせていただきます。

**Comment by amylase** [comment]
#539 でこれが治りました、Closeできますか？ @kenkoooo

**Comment by kenkoooo** [comment]
🙏 🙏 🙏
