### ISSUE TITLE
FAQページを作る

### ISSUE THREAD

**Issue by amylase** [kenkoooo/AtCoderProblems#460]
twitterを見ていると AtCoder Problems について結構同じような疑問が聞かれていて、今の所 @kenkoooo さんのスーパーエゴサパワーで解決していますが（私もスーパーエゴサパワーで様子を眺めています）、公式のわかりやすい場所にまとまっていてもいいかなと思いました。結構いろんな機能が追加されてきましたし。言語は日本語と英語があればいいでしょう。
よく見る質問は以下のとおりです
* 反映に時間がかかってる？ -> コンテスト終了後は遅れますが普段はすぐです or バックエンドが落ちています
* 難易度の丸の読み方がわからない -> 公式の色になんとなく対応してます。満ち欠けについては、TopCoderって知ってる？　私は知っています。ちなみにマウスオーバーすると具体的な値がわかります
* 難易度の値の意味がわからない -> 50%の確率で解けるレーティングです。
* バチャの作り方/参加の仕方 -> 実は GitHub のアカウントが要ります

**Comment by kenkoooo** [comment]
まずは markdown で書いて github に置く感じで、そのうちやります

**Comment by amylase** [comment]
* Median Solve Time って誰にとっての値ですか？ https://twitter.com/beet_aizu/status/1238755134961627136

**Comment by kenkoooo** [comment]
とりあえず作りました。少しずつ内容を増やしていきましょう。
