### ISSUE TITLE
Statistics are not correct after the user name is updated

### ISSUE THREAD

**Issue by 1CH1GO** [kenkoooo/AtCoderProblems#462]
I changed my AtCoder username recently and the statistics shown on the page are not complete. Please look into this.

**Comment by kenkoooo** [comment]
All your submissions will be crawled again automatically. But it takes a few weeks, since the crawler needs to found the updated submissions from millions of submissions. I can update the database manually, so please ask me to do that if it's hurry.

**Comment by 1CH1GO** [comment]
No problem I can wait. Thanks for your reply :+1:
