### ISSUE TITLE
Other Rated Contestsの問題の難易度推定の円にマウスオーバーすると高速で点滅します

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#463]
https://twitter.com/trineutron/status/1236884760368017409

**Comment by trineutron** [comment]
#384 と同じバグかもしれません。問題名が2段になるとこのバグは発生しません。

**Comment by c-yan** [comment]
日立2020のA問題のサークルにカーソルを持っていくと、A問題だけでなく 、D, E, F問題が点滅する不思議.
デバッガだと、focusin してすぐに focusout しているように見えますね.
