### ISSUE TITLE
解ける確率を List にも入れる

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#469]
https://twitter.com/medo_program05/status/1238788786210783234

**Comment by MatsuTaku** [comment]
Userを基準に計算した予測回答確率を元に、ユーザに対する問題の難易度アイコンを作ってみました。

 - (1-解答確率)を問題に対するUserの相対難易度と解釈して、３色([Easy, Moderate, Difficult], 両側1/3を境界)のバーで表現
 - マウスオーバーでユーザの予測回答確率が確認可能

![2020-06-27 (4)](https://user-images.githubusercontent.com/8394202/85918017-08c7af00-b89a-11ea-961c-0d61ac3f12ef.png)
![screenshot-localhost-3000-atcoder-1593245138308](https://user-images.githubusercontent.com/8394202/85917980-ca31f480-b899-11ea-9b7a-dcf90af03a19.png)
![screenshot-localhost-3000-atcoder-1593245182050](https://user-images.githubusercontent.com/8394202/85917981-caca8b00-b899-11ea-98b2-80103fb936c7.png)

### 関連Issue
#643

**Comment by amylase** [comment]
これいいですね！ #643 との比較で言えば正解率が解釈しやすい値なのがわかりやすさに効いていると思います。

これはやや好みの話ですが、Tip で正解確率を出しているので下のバーでも統一して正解確率が高いほうが長いほうが直感に合いそうです。あと、一本のバーの中で複数の色があると混乱する（私はしました）ので、色を長さで変えるのはわかりやすくてよいのですが1本のバーの中では一つの色を使うようにしたほうがよくなると思いました。

**Comment by MatsuTaku** [comment]
>あと、一本のバーの中で複数の色があると混乱する（私はしました）ので、色を長さで変えるのはわかりやすくてよいのですが1本のバーの中では一つの色を使うようにしたほうがよくなると思いました。

![combine_images](https://user-images.githubusercontent.com/8394202/85927917-1c980300-b8e4-11ea-8a69-258d45b89605.png)
![combine_images (1)](https://user-images.githubusercontent.com/8394202/85927919-1efa5d00-b8e4-11ea-9ab0-b9f10067667d.png)

難易度ごとに色を統一し，長さはそれぞれの区間内での位置に合わせました．（難易度アイコンと同じ感じ）
難易度感が直観的にわかりやすくなったと思います．


> これはやや好みの話ですが、Tip で正解確率を出しているので下のバーでも統一して正解確率が高いほうが長いほうが直感に合いそうです。

解答確率をそのまま表示するということですね．
私が相対難易度（１－解答確率）で表示した理由は，解答確率を元にアイコン表示すると，簡単な（解答確率の高い）問題が目立ち，難しい（解答確率の低い）問題が目立たなくなってしまうのはユーザーにとってうれしくないのではないかと考えたからです．
難易度アイコンも難しい問題ほど面積が大きくなっていますので，それとも直感を揃えたいと思いました．

議論のポイントは
1.  ユーザーが最も欲しい情報は何か
2.  欲しい情報に適したデザインは何か

**Comment by MatsuTaku** [comment]
難易度区分は調整したほうがいいかも。
現在: 上下33%
提案: 上下25%

**Comment by MatsuTaku** [comment]
区間は上記に変更しました．

とりあえず3パターン試し

### 1
アイコニックなバー．
個性強め．
細かい改善で良くなる可能性もある．
![2020-07-04 (9)](https://user-images.githubusercontent.com/8394202/86507972-273c2600-be17-11ea-8c22-96c75d922624.png)
![2020-07-04 (10)](https://user-images.githubusercontent.com/8394202/86507973-27d4bc80-be17-11ea-8abc-8b033b9bfaa7.png)
### 2
セルのボトムに合わせたバー．
主張は強いが直観的にわかりやすい．
しいて言うならよくありそうなデザイン．
![2020-07-04 (11)](https://user-images.githubusercontent.com/8394202/86507974-286d5300-be17-11ea-8825-feffb60239cf.png)
![2020-07-04 (12)](https://user-images.githubusercontent.com/8394202/86507975-286d5300-be17-11ea-8208-685b910b3b5d.png)
### 3
セルの縦に合わせたバージョン．
こちらも直観的に認識しやすいが，横とくっつくので見づらい人もいるかもしれない．
![2020-07-04 (13)](https://user-images.githubusercontent.com/8394202/86507976-2905e980-be17-11ea-83c0-b6e6bb46db1a.png)
![2020-07-04 (14)](https://user-images.githubusercontent.com/8394202/86507970-26a38f80-be17-11ea-897c-1fb7e875b236.png)

**Comment by southball** [comment]
パターン２は確かに読みやすいですね。

**Comment by koyumeishi** [comment]
新たに表示する機能を追加するのではなくて #401 + List ページのテーブルに確率カラムを追加 ではダメですかね？
discrimination が小さいやつは超低難度か超高難度の問題がほとんどであまりあてになりませんし、difficulty+200程度のレーティングを持つ人なら 60-70% の確率、 difficulty+400 程度なら 70-90%、+800 なら 90% 以上の確率で解ける (と予測される) 問題がほとんどです。 difficulty 自体厳密な難易度判定ではないですし、自分の色から1-2色下の問題を意識して解くようにすればそれでいいような気がします。

discrimination のヒストグラムと delta=(Rating - Difficulty) のときの予測正解率 - 0.5 の雰囲気
![Figure_1](https://user-images.githubusercontent.com/11204237/87610898-9c75f800-c741-11ea-88a3-e3c891a16642.png)

個人的にはダークモードのパターン3なんかとてもカッコいいと思うんですが、 予測正解率は difficulty との相関が強いので多分玉の方だけで機能としては足りていて、視覚に強く訴える割には冗長な情報かと思います。
Recommends 以外の場所でも目安として知りたい気持ちは分かるので、上述の #401 + List ページのテーブルに確率カラムを追加 は欲しいと思います。

**Comment by MatsuTaku** [comment]
#401 + List ページのテーブルに確率カラムを追加
は良さそうですね。
すでにRecommendationで実装されている情報ですから、Tableで弊害がないなら表示してもいいと思います。

予測正解率の情報が冗長かどうかは主観にもよる部分があると思います。
確かに予測正解率はdifficultyと相関がありますが、discriminationによる補正は直感に対し無視できない影響があると私は考えています。

ToolTipによる予測正解率表示は問題ごとの情報の提示としての要件は満たしますが、一覧性がありません。
それに対し、提案した３色表示は概ね実力相当の問題がどれであるかを視認する一覧性に長けているので、意味がある表示だと私は思います。

**Comment by kenkoooo** [comment]
個人的にはレコメンドと得られる情報が変わらない気もするので必要性を感じていませんが、これは個人の感想で、欲しい人がいれば入れた方が良いと思います。どんなユーザーを想定していますか？

**Comment by MatsuTaku** [comment]
まず、難易度メータというアイデアは、「推定正解率を表示する機能」のリッチな拡張であることは明らかにしておきます。

メインの目的は、単純に問題の難しさを知りたいということです。
**AtCoder Problems で今日のコンテストの問題のdiffを確認する楽しみ方をしているユーザも多いと思いますが、そういった楽しみ方の一つになるのではないかと思います。**
「問題に対して難易度を提供する」という機能は一般的に理解しやすく需要の高い情報だと思いますが、このアイデアはよりユーザに最適化した情報を提供するという立場になります。
またこの情報は、アイコニックな表示で直感的に理解できることや、一覧性によって他の問題との比較ができることでより価値が上がるものだと考えています。
ときに、「思ってたよりもdiffが低い（高い）」という印象の問題はしばしば判別度(discrimination)が低いという状況もありますが、difficultyだけでは得られない情報で補足されるのは私は嬉しいです。(#643)

これはデザイン依存の楽しみ方になるかもしれませんが、例えば
- メーターのModerate(黄色)相当は確実に解ける用になっておきたい
- レートが上がったら前は難しかった問題がModerateになって嬉しい

といったことも想定できそうです。
これに関しては、現状より色分けを工夫してユーザーが注目しやすい問題に適した表示に改良できれば良いなと考えています。

**Comment by koyumeishi** [comment]
Table のページは既に色で表現している情報が多量にあって、ここに更に3色を追加するとなると視認性が悪化するような気がします。 (要するにごちゃごちゃしちゃう)
私は https://github.com/kenkoooo/AtCoderProblems/issues/469#issuecomment-659079129 で述べたように、ほとんどの問題に関しては discrimination はある程度の範囲に収まっているので難易度の表現としては difficulty の値だけで事足りていると思っていて、少数の問題に対して difficulty + α の情報を視覚的に提供するためだけに全体の視認性を阻害するのはUX的に良くない、というスタンスです。 (というか、問題の"真の難易度"を算出すること自体が現実的に不可能なのでこの +α の情報にもそんなに意味はないと思っています)

difficulty による色表示を予測正答率で代替すれば表示上はスッキリするかなと思いましたが、当人のレーティング周辺の difficulty の問題以外に対しては情報量ゼロになってしまって、結局劣化 difficulty にしかならなそうです。 何より現在ユーザー間では "赤diff" "青diff" のような言い回しでコンセンサスが取れているので個人依存の指標に基づく色分けは混乱の元になりそうです。

**Comment by MatsuTaku** [comment]
UIがシンプルな方がいいのは同意します。
仮に実装するとしてもできるだけシンプルでわかりやすい物がいいですし、改善はしていくべきです。

それははそれとして、
**必要な表示を選択する自由**は"チェックボックスによる切り替え機能"で担保されているということにはならないでしょうか。

**Comment by MatsuTaku** [comment]
難易度メータは独立したアイデアとして別にIssue切っても良さそうな気がしてきました。

**Comment by koyumeishi** [comment]
そうですね、はじめは optional な機能として実装してみてユーザーの反応をうかがってみるのも良いかもしれません。 デザインの改善案なんかもユーザーから出てきそうです。

まだマージされていないのでどうなるか分かりませんが、 #691 で \<DifficultyCircle\>, \<ProblemLink\> に ProblemModel, RatingInfo プロパティを追加しました。 予測正答確率の計算がこれらのコンポーネント上でできるようになるので、コンポーネントの一部としてメーターが実装されると Table 以外のページでも表示できて嬉しいかもしれません。 デザイン上の制限は生まれますが…。

**Comment by MatsuTaku** [comment]
ありがとうございます。

承知しました。
競合しそうなので対応しておきます。

メーターは独立したコンポーネントにしておいたほうが表示非表示の切り替えが楽でいいかなと思ってます。

**Comment by MatsuTaku** [comment]
このIssueの本来の目的は #401 に近いものであり、 #691 で達成されそうなので、
難易度メーターは別Issue #693 にしました

**Comment by kenkoooo** [comment]
done in #691
