### ISSUE TITLE
バチャでtourist出ししたらパフォーマンスがバグった

### ISSUE THREAD

**Issue by leafirby** [kenkoooo/AtCoderProblems#476]
https://kenkoooo.com/atcoder/#/contest/show/f50f0e21-8944-431c-9db4-04c6e83e8ad3
https://twitter.com/leafirby/status/1242488908404801536
の通りです
もしかしたらJOIのせいかも

**Comment by tatt61880** [comment]
#455 に「1つ前の問題を解き終わった時刻からの時間で計算しています。なので、潜伏して一気に提出したりすると跳ね上がります。」と書かれています。

**Comment by leafirby** [comment]
https://github.com/kenkoooo/AtCoderProblems/issues/455
と同じ件みたいなのでcloseします
