### ISSUE TITLE
APIを使うとVirtual Contestの問題を開始前に見れてしまう

### ISSUE THREAD

**Issue by satoooon8888** [kenkoooo/AtCoderProblems#496]
`https://kenkoooo.com/atcoder/internal-api/contest/get/{contest_id}`
上記のAPIをコンテスト開始時刻の前に使うとコンテストで出題される問題を事前に確認できてしまいます。
下の画像はChromeの開発者ツールで確認した画面です。
この画面のコンテストは開始済みで、開始後に出題された問題のidとAPIで事前に確認したidが一致したことをこちらで確認しています。
![before_contest](https://user-images.githubusercontent.com/56899143/78985509-ee681a00-7b63-11ea-9668-4c7c31490561.png)

**Comment by kenkoooo** [comment]
既出の問題しか出ない virtual contest で api のレスポンスを見てまで勝ちたい人は、もう勝ちで良いんじゃないですか……

**Comment by satoooon8888** [comment]
考えてみるとしょうもない問題ですね...
コンテストが開始していないのにAPIが呼ばれ、出題が見えてしまうことに違和感を感じたので、本来の機能に反するバグとして報告した次第です。
もしこれをする人がいないか、したところで問題ないと考えるのであれば修正は必要ないかもしれません。

**Comment by kenkoooo** [comment]
:ok_hand:
