### ISSUE TITLE
BootCampのように、既に解いたか解いていないかを区別できて、達成率もひと目で確認できるようなAtCoderの問題セットを自作できる機能があったら最高だな〜

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#502]
https://twitter.com/lorent_kyopro/status/1251478507164626944

**Comment by makutamoto** [comment]
方針としてはProblem Listを改良していく感じで、
- AC状態やDifficultyを表示。
- BootCampのようにAC率の円グラフをつける。
- スワップ機能を追加。
みたいな感じでしょうか。

また、
- UIとしてみつけやすい位置に持ってくる。
- お気に入り機能をつける。
などするとUXが向上すると思います。

**Comment by kenkoooo** [comment]
バチャ作成画面がなんか進化してるので何とかなってそう
