### ISSUE TITLE
修行バチャ用のUIほしい

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#505]
こういうのなんとかしたい
https://kenkoooo.com/atcoder/#/contest/show/e4a536de-c13d-4a4a-b939-76bf6b27b124

考えているもの
- 参加者は複数名（〜20名）
- 問題数が多い（〜100問）
- モードとして追加する
  - Normal, Lockout に加えて新しく作る
- 各自の解いた問題数が可視化される感じ
  - 棒グラフとか？

**Comment by southball** [comment]
クライアントサイドで生成したトレーニングコースはどうですか。

![image](https://user-images.githubusercontent.com/6523469/82190161-31679b00-9923-11ea-8579-015c2b0a4689.png)

**Comment by southball** [comment]
これならどう思いますか。（モードは同じですけど…）

![image](https://user-images.githubusercontent.com/6523469/86510365-9880d680-be21-11ea-9cb0-0e92b9b4f7ae.png)

**Comment by kenkoooo** [comment]
最高だと思います……

**Comment by kenkoooo** [comment]
問題リンクをクリックするのが難しい（tooltipが消える前にサッとカーソルを移動させないといけない）ので、Cellをクリックしたら問題に飛べると良さそうです。
=> #663
