### ISSUE TITLE
Virtual ContestでRatedコンテストを丸ごと入れた時のEstimated Performance

### ISSUE THREAD

**Issue by polyomino-24** [kenkoooo/AtCoderProblems#509]
いつもお世話になっております。こういう意見もあるという程度に捉えて欲しいのですが、ABCなどのRatedコンテストを1セット丸ごと追加した時にはEstimated Performanceは実際のコンテストに基づくものと一致していると便利だと思いました。一致とまでいかなくても、バチャコンの順位表とEstimated Performanceの順序は一致して欲しい気持ちがあります。

**Comment by kenkoooo** [comment]
ご意見ありがとうございます。現時点では技術的に難しいですが、将来的に可能になるといいですね。

**Comment by kenkoooo** [comment]
https://github.com/kenkoooo/AtCoderProblems/issues/455 に詳しい議論があります。

**Comment by kenkoooo** [comment]
これは公式の virtual participation 機能とは何が違いますか？

**Comment by polyomino-24** [comment]
背景としては、公式の機能では複数人参加が面倒(順位表,時間管理など)だったためproblemsを利用しました。
公式の機能ではパフォーマンスは表示されません(調べればいいというのはそうですが)

**Comment by kenkoooo** [comment]
:+1:

**Comment by amylase** [comment]
これですが、#539 で順位とEstimated Performanceの順序が一致するようになりましたね。実際のコンテストのPerformanceとはまだ乖離がある気がしますが、場合によっては close できるかもしれません。

**Comment by polyomino-24** [comment]
ありがとうございます！僕が感じていた違和感は解消されたようなのでcloseして頂いて構わないです
