### ISSUE TITLE
よく使われているimport文のリストと、それが使用されている問題の列挙

### ISSUE THREAD

**Issue by mimikakikowai** [kenkoooo/AtCoderProblems#512]
pythonを想定して書いています

AC回答から'import'が含まれる行を拾い集めて集計してほしいです。
パッケージ毎に集約する等の必要はないと思っています(しない方がうれしい)。
集計は一度実行すればアップデートしなくても十分うれしいです。

１.使ったことないパッケージがないか簡単に探せる
２.それが必要となる問題をすぐに見つけて練習ができる
ということです。

class名もあるとよいのかも(最近覚えたのですがunion find - ABC157Dとか出て来て欲しい)

**Comment by kenkoooo** [comment]
現在 AtCoder Problems では集計情報のみを収集していて、提出コード本体は収集していません。
