### ISSUE TITLE
推定したDifficultyが一部消えている

### ISSUE THREAD

**Issue by Yang-33** [kenkoooo/AtCoderProblems#538]
https://kenkoooo.com/atcoder/resources/problem-models.json に
ABC163A、ABC163B、ABC150A、ABC150Bのような問題のDifficultyが消えているのを見つけました。（他にもいくつかありました）
どうしてなのかは分かりません！

**Comment by kenkoooo** [comment]
#361 ですね！

**Comment by Yang-33** [comment]
久しぶりに見たので知りませんでした…　すいません🙇

**Comment by kenkoooo** [comment]
いえいえ、また何か気付いたことがあったらお気軽にどうぞ！
