### ISSUE TITLE
Streakの定義を修正(新しい問題を解いた連続日数→ACした連続日数)&既存ユーザの救済

### ISSUE THREAD

**Issue by Kota-Y** [kenkoooo/AtCoderProblems#540]
## 概要
1. Streakの定義を修正
以下の定義に修正する。
```
現在の定義: まだ解いていない問題を新しく解いた連続日数
修正後定義: すでに解いている問題を含めた問題を解いた連続日数
```

2. 既存ユーザの救済
すでに現在の定義のために`Current Streak`を切らしたユーザを救済する。
そのために、修正後の定義に則ってStreakを計算し直す。

## 背景
現在の定義を知らずに悲しい思いをしているユーザが発生している。
そういった思いをしたユーザに救いの手を与える。

【上記のような思いをしたユーザの例(原文引用)】
- ユーザ1
```
え・・・
同じ問題ACだとStreak続かないの・・・？
死んだ
競プロ始めてからStreak続けてたのにモチベが。。。
```
[https://twitter.com/kota0501_orca/status/1260242324136722432](https://twitter.com/kota0501_orca/status/1260242324136722432)

- ユーザ2
```
新規acじゃないとstreak切れるの知らんくて前切れたの痛い
```
[https://twitter.com/astr_86/status/1233705710057246720](https://twitter.com/astr_86/status/1233705710057246720)

## 備考
いつも利用させていただきありがとうございます。
AtCoder Problemsは、すでに競技プログラミング界隈のインフラとなっていると感じております。
実際にCurrent Streakを切らさないように毎日競技プログラミングに勤しんでいる人たちは大勢います。もちろん私もその一人です。
毎日コードを書く、つまり**Write Code Every Day**。jQueryの作者、John Resigさんの言葉です。
[https://johnresig.com/blog/write-code-every-day](https://johnresig.com/blog/write-code-every-day)
Write Code Every Dayをすることは私生活含め多方面に良い影響を与えます。
その良い影響づくりを手助けしているこのサイトは、日本の競技プログラミング界、さしては日本のIT業界に多大な影響を与えていると思います。
そのためどうかCurrent Streakの定義を修正&救済を行い、さらなる発展に手をかけてはいただけないでしょうか。
どうかご検討の程よろしくお願いいたします。

**Comment by iilj** [comment]
- streak の定義がわかりやすいように `<HelpBadgeTooltip>` を付ける
- Unique AC Streak と All AC Streak に分ける

のいずれか程度が落とし所ではないかと個人的には思います．

仕様を知らずに streak を切らした人たちを救済するということは，これまでに streak のために積み重ねられてきた unique AC の価値を相対的に下げるということでもあります．そのまま streak の定義をごっそり入れ替えるというのでは，納得しない人の割合が多いのではないかと考えられます．

**Comment by Kota-Y** [comment]
これいいですね！Tipについてはどちらにせよ付与したら分かりやすいと感じました！
> - streak の定義がわかりやすいように `<HelpBadgeTooltip> `を付ける
> - Unique AC Streak と All AC Streak に分ける

そうですね。unique ACの価値は相対的に少なからず下がってしまうと思います。
また同じACコードを毎日提出し、Current Streakを切らさないということもできてしまいます。

しかし、Current Streakには他者との競争というより、自己満足による競技プログラミングに対する勉学促進の意味合いの方が強いと考えております。
Streak Rankingなるものは存在しますが、Current Streakの大目的はここにあると感じています。(完全な私個人の考えです。作者さんやContributorさんの考えもお聞きしたいです。)
そのためunique ACではなくとも、Streakにカウントしても良いのではないかと私は考えました。

自己満足のためなら自身でカウントしておけば良いかもしれませんが、それだと上記のような促進効果は得られないと思っています。これだけ使われているプラットフォームでカウントされているからこそ意味があるものになるんだと強く考えています。

**Comment by kenkoooo** [comment]
今の Streak のシステムでやりこんでいる人が結構いるので、これを別のものに置き換える予定はありません。とりあえず使っている人がいる機能は廃止しない方針でやりたいです。

@iilj さんの streak の定義を tooltip で載せる案は良さそうです。[FAQ](https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/faq_ja.md) に書いても良いと思います。

Streak Ranking のためにやっている人もいると思っていて、競技 Streak 勢向け機能の Streak Ranking と自己満足勢向け機能の Heatmap という住み分けがあると思っています。

**Comment by Kota-Y** [comment]
なるほどです。
ご回答ありがとうございました！
