### ISSUE TITLE
chore(frontend): TSLint → ESLint

### ISSUE THREAD

**Issue by rdrgn** [kenkoooo/AtCoderProblems#541]
https://github.com/palantir/tslint にあるようにTSLintは非推奨となり、TypeScriptにも対応したESLintが推奨されています。

**Comment by rdrgn** [comment]
PRを投げようかと思っていたのですがルールどうするのかという話になりそうで保留中。

今考えている対応方法
- [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config)を利用して今の`tslint.json`のルールを変換して引き継ぐ
  - `.eslintrc.json`が長くなるかも (未確認)
- `tslint.json`の再現はせず`eslint:recommended`などを入れながら妥当なルールを書き直す
  - 以前のルールと互換性がなくなる

**Comment by kenkoooo** [comment]
今のルールに全然こだわりは無いので、書き直しちゃって良いと思います

**Comment by rdrgn** [comment]
ありがとうございます🌮 

と、ここまで書いておいて何なのですが、まず最初にtslint-to-eslint-configで変換して単にTSLintをESLintに置き換えるだけのPRを出してから、次にルールを整理するのが妥当な気がしてきました。

**Comment by kenkoooo** [comment]
🙆‍♀️
