### ISSUE TITLE
build(frontend): 一部のdependenciesをdevDependenciesに変更

### ISSUE THREAD

**Issue by rdrgn** [kenkoooo/AtCoderProblems#542]
dependenciesである必要のないパッケージをdevDependenciesに変更するべきだと考えました。

- 型定義のパッケージ (`@types/*`)
- `typescript`などビルド時のみ必要なパッケージ

**Comment by kenkoooo** [comment]
これが npm のパッケージとして publish されることは無いので、そんなに気にしてなかったのですが、何か他に理由ってあったりしますか？

**Comment by rdrgn** [comment]
私のようにこれからコードを読もうと試みている者の立場ですと、`package.json`を見て各パッケージの使われ方が大まかに理解できる利点があると考えています。

（僭越ながらProblemsのフロントエンド開発に貢献したいと考えてコードを眺め始めた次第です）

**Comment by kenkoooo** [comment]
なるほど、ありがとうございます。
