### ISSUE TITLE
Show Acceptedが機能していない

### ISSUE THREAD

**Issue by hirata0517masato** [kenkoooo/AtCoderProblems#544]
table内のチェックボックス「Show Accepted」が機能していない

・Google Chrome
チェックの有無にかかわらず常に「チェックあり」状態

・Microsoft Edge
チェックの有無にかかわらず常に「チェックなし」状態

**Comment by kenkoooo** [comment]
お使いのブラウザのバージョンを書いていただいても良いですか？
手元の Google Chrome Version 81.0.4044.138 (Official Build) (64-bit) と Firefox 76.0.1 (64-bit) では正しく動作しました。

**Comment by hirata0517masato** [comment]
確認環境は以下のバージョンです
 
Google Chrome：バージョン: 81.0.4044.138（Official Build） （64 ビット）
Microsoft Edge： 44.18362.449.0

**Comment by kenkoooo** [comment]
その現象が起こる URL を貼ってもらっても良いですか？
ここでは動作しました: https://kenkoooo.com/atcoder/#/table/kenkoooo

**Comment by kenkoooo** [comment]
Edge は Version 81.0.416.72 が最新のようですが、アップデートするとどうなりますか？

**Comment by hirata0517masato** [comment]
確認したURLです
https://kenkoooo.com/atcoder/#/table/hirata0517masato

**Comment by kenkoooo** [comment]
理解しました。

https://kenkoooo.com/atcoder/#/table/kenkoooo 
このページで Show Accepted の動作を理解していただいても良いですか？

**Comment by hirata0517masato** [comment]
すいません。動作を勘違いしていました。
正しくは、全ての問題をACした回を表示するかどうかの選択だと理解しました。
そして、私の手元で発生している問題は別であるとわかりましたの。
Edgeを最新版に更新した後、再発したら別のissueを立てさせてもらいます。

**Comment by kenkoooo** [comment]
👍
