### ISSUE TITLE
スマートフォンで閲覧すると、ヘッダが大きくスペースを占有してしまいます

### ISSUE THREAD

**Issue by CKPCKP** [kenkoooo/AtCoderProblems#560]
https://twitter.com/d9et/status/1261919358537752578

**Comment by rdrgn** [comment]
デスクトップ向け表示はそのままで、モバイル向け表示では次のいずれかに修正することを考えています。
- 固定せずページの最上部に表示する
  - 最上部まで行くのが面倒そう
- 上のナビゲーションバーと一緒に折り畳む
  - 従来のナビゲーションバーに近い動線になる

**Comment by rdrgn** [comment]
自分用の覚書
https://getbootstrap.com/docs/4.5/layout/overview/#containers

**Comment by southball** [comment]
これはどうですか。

```diff
-      <Nav navbar>
-        <Form inline>
+      <Nav navbar style={{ overflowX: "auto" }}>
+        <Form inline style={{ flexWrap: "nowrap" }}>
```

![image](https://user-images.githubusercontent.com/6523469/82154559-47cd1280-98a1-11ea-9e05-6eee58fae7d1.png)

ビデオはここ：https://twitter.com/southball02/status/1262062048944349184

**Comment by rdrgn** [comment]
あー確かに、そういうのもよさそうですね(๑>﹏<๑｀)

モバイルで2段目のナビゲーションバーが常に見えているべきかという観点から、折り畳む案と迷っています。

**Comment by CKPCKP** [comment]
どちらかというと折りたたむ方が良さそうな気がしますが、好みの範疇だと思います。

**Comment by southball** [comment]
折りたたむバージョンも作ってみました。
これも `flexWrap: "nowrap"` と `overflowX: "auto"` と一緒に使えます。

![preview](https://user-images.githubusercontent.com/6523469/82212736-9d5afb00-9945-11ea-8034-255a33c6507e.gif)

**Comment by CKPCKP** [comment]
私はこちらのほうが好みです！！

**Comment by kenkoooo** [comment]
https://twitter.com/affine_space/status/1262989185071243264

**Comment by southball** [comment]
> 
> 
> これはどうですか。
> 
> ```diff
> -      <Nav navbar>
> -        <Form inline>
> +      <Nav navbar style={{ overflowX: "auto" }}>
> +        <Form inline style={{ flexWrap: "nowrap" }}>
> ```
> 
> ![image](https://user-images.githubusercontent.com/6523469/82154559-47cd1280-98a1-11ea-9e05-6eee58fae7d1.png)
> 
> ビデオはここ：https://twitter.com/southball02/status/1262062048944349184

このバージョンを作りますか...
けどユーザーはどのバージョンが欲しいかはわからないですね。

**Comment by kenkoooo** [comment]
ユーザーは1人ではなくて、各人欲しいものは違うので……
本当にやろうと思ったら、A/Bテストをやったりログを取ったりしないといけないと思いますが、今のところそこまでやるつもりはないので、自分が使いやすければ良いと思います。

**Comment by southball** [comment]
A/B テストは考えたことあるけどやっぱり簡単にできないことですね。
新しい PR でのバージョンは携帯に少ないスペースを占有しているし使いやすいと思うし、たぶんいいんでしょう。
