### ISSUE TITLE
Progress ChartsのClimbingで色ごとの推移を出せませんか？

### ISSUE THREAD

**Issue by nabenabe0928** [kenkoooo/AtCoderProblems#568]
現在，Climbingは解いた問題の総数のみの表示になっていますが，本質的に重要なのは問題数ではないので，色ごとのAC数の推移をみたいです．

**Comment by nabenabe0928** [comment]
ご対応いただきありがとうございました．
色は昇順・降順の両方に対応していただけるとさらに利便性が増すかと思います．

**Comment by kenkoooo** [comment]
>  色は昇順・降順の両方に対応していただけるとさらに利便性が増すかと思います．

UIが複雑になってしまって利便性が損なわれそうな気がしますがどうなんでしょう。

**Comment by nabenabe0928** [comment]
UIやUX周りに関してはあまり詳しくないので，私の方からは詳細な言及はできないですが，灰色Diffはコンテストに参加するたびにかなりの量増えてしまうので，難易度の高い問題の累積数を見たい場合は色の位置を反転させる必要があるかと思いました．

**Comment by iilj** [comment]
本件，issueになっていたんですね．

ちょっと前に，[yukicoder problems](https://iilj.github.io/yukicoder-problems/#/user/name/iiljj) に色の順序を反転するオプションを付けたのですが，この程度のオプション数であれば，UIはさほど複雑ではないように感じます．
![image](https://user-images.githubusercontent.com/59337901/83670472-2e042d00-a60e-11ea-9771-4308bff88b5a.png)

もしかしたら，ヒートマップの切替ボタンと同じ画面に入ると，ちょっとうるさいUIに見えるということはあるかもしれません．
とはいえ，色順序反転は他にも提案している方がいらっしゃったので，機能自体に需要はありそうです．

**Comment by nabenabe0928** [comment]
こちらの反映内容，個人的にはかなり好印象なのですが，結局お蔵入りしそうな雰囲気ですかね？（使用を始めて1ヶ月近く経ちましたが，グレーのAC数に押しつぶされて他色の視認性が悪いです．）

任意の色をグラフから抜くオプションでも解決可能ですが，色反転の方がUI的にも実装的にも負荷が軽いですよね．．．？

**Comment by kenkoooo** [comment]
@nabenabe0928 プルリクきたらマージします。来てないのでなんとも…

**Comment by kenkoooo** [comment]
#626 で解決したっぽいですかね
