### ISSUE TITLE
テーブルページのShow Accepted，Show Difficultyのボタン化

### ISSUE THREAD

**Issue by y-oksaku** [kenkoooo/AtCoderProblems#577]
この2つがチェックボックスで，周りがボタンなのには違和感があります．

ボタンにするとこんな感じになります．
<img width="798" alt="screen_shot" src="https://user-images.githubusercontent.com/43719835/82268934-21939980-99ab-11ea-9f49-49ddd316ad75.png">

**Comment by kenkoooo** [comment]
強いこだわりがあるわけではないのですが、トグルスイッチをボタンにすると、onなのかoffなのか分かりにくくないですか？

**Comment by y-oksaku** [comment]
確かにわかりにくいですね．

下のボタンも含めてこのようにするのはどうでしょうか?

<img width="785" alt="shot" src="https://user-images.githubusercontent.com/43719835/82281880-70522b00-99cd-11ea-8ec4-1bb1c5b194fa.png">

**Comment by southball** [comment]
ボタンを使ったら、スイッチはどうですか。

![image](https://user-images.githubusercontent.com/6523469/82296915-815a6680-99e4-11ea-8e6e-2c1ac01087f8.png)
![image](https://user-images.githubusercontent.com/6523469/82297035-a9e26080-99e4-11ea-8828-54d6e35c54e0.png)

**Comment by rdrgn** [comment]
2値を切り替えるものをチェックボックスにするのは意味的に正しくて、違和感の本質は、現状のチェックボックスの見た目が弱いことにあると想像しています。

他所でもチェックボックスを使いうることを考えると、チェックボックスにスタイルを当てる選択肢も検討してみてはいかがでしょうか。

他方で、southball さんの案も、チェックボックスでは得られない利点（ユーザが得たい表示とクリックすべき箇所が一対一に結び付く）がありよいと思っています。

**Comment by y-oksaku** [comment]
>違和感の本質は、現状のチェックボックスの見た目が弱い（あるいは小さくて押しづらい）ことにあると想像しています。

その通りです．言語化するとわかりやすいですね，ありがとうございます．

このようにするとチェックの状態がわかるので良いかもしれません．

<img width="381" alt="スクリーンショット 2020-05-19 17 59 08" src="https://user-images.githubusercontent.com/43719835/82307354-3566ec00-99fb-11ea-9cd9-8825b8afd801.png">

**Comment by southball** [comment]
> 
> 
> > 違和感の本質は、現状のチェックボックスの見た目が弱い（あるいは小さくて押しづらい）ことにあると想像しています。
> 
> その通りです．言語化するとわかりやすいですね，ありがとうございます．
> 
> このようにするとチェックの状態がわかるので良いかもしれません．
> 
> <img alt="スクリーンショット 2020-05-19 17 59 08" width="381" src="https://user-images.githubusercontent.com/43719835/82307354-3566ec00-99fb-11ea-9cd9-8825b8afd801.png">

![image](https://user-images.githubusercontent.com/6523469/82312577-db195b80-99f9-11ea-9427-5718dc4cb761.png)

（画像のボタンの色は正しくない）
ところで、ボタンにすれば、ボタンを囲んでいる Container をなくしませんか？

**Comment by MatsuTaku** [comment]
BootstrapのFormsにスイッチがあるのですが，いかがですか？
https://getbootstrap.com/docs/4.5/components/forms/#switches

<img width="262" alt="スクリーンショット 2020-07-21 21 15 30" src="https://user-images.githubusercontent.com/8394202/88053825-68626300-cb97-11ea-853e-28cf510cf0fa.png">
<img width="258" alt="スクリーンショット 2020-07-21 21 15 37" src="https://user-images.githubusercontent.com/8394202/88053832-6a2c2680-cb97-11ea-9985-95950970fb3b.png">

**Comment by MatsuTaku** [comment]
![2020-07-22](https://user-images.githubusercontent.com/8394202/88147572-5e447100-cc38-11ea-87c8-1a89b054a733.png)

**Comment by kenkoooo** [comment]
> ![2020-07-22 (1)](https://user-images.githubusercontent.com/8394202/88147759-9f3c8580-cc38-11ea-9aa2-8e724a6a39c8.png)

これ良さそうなので、これでやってみます。

**Comment by sirogamichandayo** [comment]
これやってもいいですか?

**Comment by kenkoooo** [comment]
@sirogamichandayo たぶん3行くらいの変更で本当に初めてやる人にお願いしようと思っているので、他のをやってもらっても良いですか？

**Comment by sirogamichandayo** [comment]
@kenkooo 了解です

**Comment by ysakanaka** [comment]
@sirogamichandayo すみません。譲っていただいてありがとうございます。
