### ISSUE TITLE
Submissionでepoch secondで絞り込みたい

### ISSUE THREAD

**Issue by odanado** [kenkoooo/AtCoderProblems#58]
あるepoch secondより新しいsubmitだけを返す仕様だと嬉しいです(ある種のページネーション)

**Comment by kenkoooo** [comment]
@odanado こんな感じでどうですか？
https://beta.kenkoooo.com/atcoder/atcoder-api/results?from=1553526000

**Comment by odanado** [comment]
ありがとうございます！試してみます
