### ISSUE TITLE
Virtual Contestでペナルティを設定したい

### ISSUE THREAD

**Issue by takytank** [kenkoooo/AtCoderProblems#582]
Virtual Contest中にWA等を出した場合、ペナルティ数の表示はされるものの、それによる順位の変動がありません。
現状、ペナルティは一律0分になっているそうです。

最近のAtCoderのABCやAGCでは、ペナルティが5分のコンテストが大半であるため、Virtual Contestでも同様のペナルティを設定出来るようにして欲しいです。

**Comment by kenkoooo** [comment]
データベースに新しいフィールドを追加するのが良くて、これをやる人は https://github.com/kenkoooo/AtCoderProblems/issues/550 も一緒にやると良いと思います。

**Comment by kenkoooo** [comment]
> データベースに新しいフィールドを追加するのが良くて、これをやる人は #550 も一緒にやると良いと思います。

#550 が想像よりだいぶ面倒だったので、別々にやっています。
