### ISSUE TITLE
フロントエンドのテストを追加する

### ISSUE THREAD

**Issue by blue-jam** [kenkoooo/AtCoderProblems#587]
フロントエンドの変更を加えていると、別の機能を破壊していないか不安になることが多々あるので、テストが欲しいなと思っています。

具体的には、

* [enzyme](https://enzymejs.github.io/enzyme/) を使ったコンポーネント毎のテスト
* [cypress](https://www.cypress.io) を使ったend-to-endテスト

を追加したいと考えていますがどうでしょうか？

**Comment by kenkoooo** [comment]
👍

**Comment by blue-jam** [comment]
よっしゃ！じゃあ、cypressのテストからちまちま書いていきますね。（理由は楽しそうだから）

**Comment by kenkoooo** [comment]
:pray:
