### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by mayankbist45** [kenkoooo/AtCoderProblems#591]
As I use the website a lot. It becomes harder to look at bright screen for long. I tried some tampermonkey scripts to make the screen dark but then it don't show me the problems I have already solved and all the other color markers like the yellow one(Atttempted).

**Comment by kenkoooo** [comment]
Could you explain why?

**Comment by mayankbist45** [comment]
I updated the previous comment.Thanks

**Comment by kenkoooo** [comment]
Thanks! That is helpful for the contributor to work on this issue.

**Comment by kenkoooo** [comment]
I feel like it's good to start using https://styled-components.com/

**Comment by southball** [comment]
Can we close this issue as we have the dark theme implemented (although it is still in beta)?

**Comment by kenkoooo** [comment]
It seems to be resolved. Let me close it.
