### ISSUE TITLE
Fetching information for a few handles not working

### ISSUE THREAD

**Issue by raj454raj** [kenkoooo/AtCoderProblems#594]
This might be because of the change in handles on AtCoder itself.

Examples:
* ankitcode99
* hardikb09

They have 0 submissions on the AtCoderProblems website but non-0 on AtCoder. Can we do some workaround for this? Also in such cases can we return some different response on the `atcoder-api/results?user=<user_handle>` to effectively communicate the state.

**Comment by kenkoooo** [comment]
AtCoderProblems will update existing data, but it takes a few days or more. Meanwhile, you can get the submissions, that are not updated, with the old handle.

**Comment by kenkoooo** [comment]
> Also in such cases can we return some different response on the atcoder-api/results?user=<user_handle> to effectively communicate the state.

Since it's not an official service, we don't know which handle is changed.
