### ISSUE TITLE
Submit済みの問題数をPie Chartsに反映するオプション

### ISSUE THREAD

**Issue by shuu0914** [kenkoooo/AtCoderProblems#601]
WAやCEなど、問題に取り組んだ痕跡がある場合、
Pie Chartにオレンジ色などで反映するオプションが欲しいです。
(ある点数帯に、まだ見たことが無い問題が残っているのか、
それとも解けていないだけなのかを判別したいです。)

**Comment by garasubo** [comment]
着手します

**Comment by kenkoooo** [comment]
> 着手します

ありがとうございます！

**Comment by kenkoooo** [comment]
https://twitter.com/Rubikun_pro/status/1276508580946931712?s=19
