### ISSUE TITLE
Table view の ABC / ARC / AGC 分類基準を Rated range ベースにする

### ISSUE THREAD

**Issue by amylase** [kenkoooo/AtCoderProblems#603]
~2000 Rated や ~2800 Rated が Sponsored ABC / ARC と認知されていて、AtCoderとしても[そういう姿勢](https://twitter.com/chokudai/status/1113123937959858176)なので、公式に合わせて Other Rated Contest にいる人達を適宜 ABC / ARC / AGC に振り分けてよい気がします。

**Comment by kenkoooo** [comment]
そういう姿勢だったんですね…

**Comment by kenkoooo** [comment]
ABC/ARC は太古の unrated も含んでいて rated の ABC 相当などを混ぜるといよいよ謎なので、ABC-like, ARC-like, AGC-like みたいなタブを作ってもよいのかなと思っています。
