### ISSUE TITLE
Please Add Problem Score in Problems Information

### ISSUE THREAD

**Issue by kajebiii** [kenkoooo/AtCoderProblems#62]
Hello, I am using your API in my software.

I want problem score data in problems information.

For example,
{"id":"agc001_a","contest_id":"agc001","title":"A. BBQ Easy"}
to
{"id":"agc001_a","contest_id":"agc001","title":"A. BBQ Easy", "score":"200"}

Thank you.

**Comment by kajebiii** [comment]
Sorry, I found point data in "http://kenkoooo.com/atcoder/atcoder-api/info/merged-problems"

**Comment by kenkoooo** [comment]
No worries. I'm glad that you are interested in my project. As you found, API's endpoints are separated by historical reasons. It will be merged next big update.
