### ISSUE TITLE
atcoder problemsのRockout、なんか理不尽な上書きが怒ってウケた(全部自分が得する方向だったのでホクホク)

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#623]
https://twitter.com/pachicobue/status/1273926651852648451

当該URL:
https://kenkoooo.com/atcoder/#/contest/show/2e8a7b2f-d804-4536-8fee-e2aade8ba323

**Comment by southball** [comment]
`submissions` は `Submission[]` ではなく、`List<Submission>` です。直してみます。
