### ISSUE TITLE
ダークモードで青字が見えにくい

### ISSUE THREAD

**Issue by psmf1** [kenkoooo/AtCoderProblems#628]
ディスプレイをナイトモードにするともっと見えにくいです。

**Comment by southball** [comment]
#627 によって直したはずと思います。

![image](https://user-images.githubusercontent.com/6523469/85225856-a2104480-b406-11ea-9813-4169490fe1f2.png)

ちょっと早いですが、ここの青字はちゃんと見えますか（また見にくいなら PR に色が変えます）

**Comment by psmf1** [comment]
ご対応ありがとうございます。
画像の色はきれいに見えます。

いつも快適に使わせていただいております。ありがとうございます。

**Comment by kenkoooo** [comment]
resolved by #627
