### ISSUE TITLE
3500AC Trophy

### ISSUE THREAD

**Issue by tozangezan** [kenkoooo/AtCoderProblems#636]
あってもいいかも(とはいえ、問題数を定期的にカウントしてある閾値を越え次第その都度当該のトロフィー追加をするのもめんどくさそう...)

**Comment by tozangezan** [comment]
(今AtCoder Problems上には3550問くらいあります)

**Comment by kenkoooo** [comment]
追加するの自体はすごく簡単なのであっても良さそうですね。kmjp さんと tozangezan さんしか達成しなそうですが…

**Comment by kenkoooo** [comment]
@DAyamaCTF さんにお願いします
