### ISSUE TITLE
難易度と判別度を加味した問題アイコン

### ISSUE THREAD

**Issue by MatsuTaku** [kenkoooo/AtCoderProblems#643]
AtcoderProblemsでの問題推定は、項目反応理論に基づくロジスティック回帰で[difficulty(回答率５０％の推定レート)]と[discrimination(判別度)]を算出していますよね。
しかし現在の問題の特徴表示にはdifficultyの情報のみが用いられています。
これは一見の問題難易度の分かりやすさをより重視した結論だと思いますが、しばしば判別度の小さい（コーディングでミスが起こりやすい。数学的要素が強い。etc.）問題で直観とずれた様な認識をされる場合があります
(e.g. ABC169-C, ABC171-C, AGC046-B)。

## 提案
問題のdifficulty+discriminationを考慮したデザインを考えたい。

## 具体案
difficulty+discriminationを考慮した問題アイコンとして以下のようなデザインを考えました。
基本的な考え方は、回答率10%~90%のレーティング分布をアイコンに収めることです。

<img width="997" alt="AtcoderProblems-ProblemHamburger" src="https://user-images.githubusercontent.com/8394202/85772329-b0889400-b757-11ea-9a63-daa61e68fe41.png">

![screenshot-localhost-3000-atcoder-1593102356336](https://user-images.githubusercontent.com/8394202/85769852-58e92900-b755-11ea-97dd-96f29a3b94b9.png)
![screenshot-localhost-3000-atcoder-1593102483386](https://user-images.githubusercontent.com/8394202/85770125-8e8e1200-b755-11ea-84f4-df71a81a2abd.png)
![screenshot-localhost-3000-atcoder-1593102434919](https://user-images.githubusercontent.com/8394202/85769876-5daddd00-b755-11ea-8de2-f6488afe91a8.png)

### 利点
- 難易度と判別度の情報が得られる ⇒難易度が低くても、アイコン内に上位色が入っていれば難易度感が修正できる。

### 欠点
- 情報量が多く、一見で認識しづらい。

## 議論
- 例示した具体案は選択肢の一つではあるが、デザインは改善が必要かもしれない（円を大きくする、表示区間を調整するなどで簡単な改善は可能）。
- 以前のアイコンの代替になるものではないので、併用するなら設計も考慮しなければならない。

あくまで判別度の情報も使ったUIが欲しいという提案です。
検討いただけると幸いです。

## 関連Issue
#469

**Comment by amylase** [comment]
判別力をいまのところ隠しているのは、おっしゃるとおりわかりやすさ重視というのもありますし、適したUIを思いつかないというのもあります。
そもそも判別力自体が解釈の難しい値なので、雑に提供して混乱を生むくらいならという感じです。

これは単なるアイデアなのですが、50%の色に対応する色だけ残して他の色の部分は透明にするのはどうでしょう？　帯の位置で色内での難易度の位置づけがおおよそわかって、幅が判別力を表現するはずです。

他の選択肢としてはユーザーのレーティングが得られる状況では正解確率が計算できて、これは難易度と判別力に依存するので難易度をすでに見せていることを合わせれば間接的に判別力の情報になります。つまり #469 をやるということですね。

**Comment by MatsuTaku** [comment]
確かに#469 を素直に実装するのは明快かつ満足度が高そうですね。
もう少し検討してみます。

**Comment by MatsuTaku** [comment]
> これは単なるアイデアなのですが、50%の色に対応する色だけ残して他の色の部分は透明にするのはどうでしょう？　帯の位置で色内での難易度の位置づけがおおよそわかって、幅が判別力を表現するはずです。

![problem-ingredients-agc](https://user-images.githubusercontent.com/8394202/85858904-550de300-b7f7-11ea-8143-4d3903dac273.png)

単に意味を理解しづらいかもしれませんね。
理解した上で使うなら悪くない気もしますが、ユーザーに理解を前提するデザインになっていそうです。

**Comment by amylase** [comment]
早速試していただいてありがとうございます！　たしかにまだ説明が必要な感じが否めないですね。
#469 の実装のほうがいい感じがします。

**Comment by kenkoooo** [comment]
#693 に統合してこちらは閉じますね。
