### ISSUE TITLE
TableViewでウィンドウ幅を小さくしたときもユーザ検索バーは表示されるようにしてほしい

### ISSUE THREAD

**Issue by sitRyo** [kenkoooo/AtCoderProblems#656]
エディタをウィンドウの半分に表示しながらAtCoder Problemsをもう半分で開くことが良くがあるのですが、ユーザ検索バーが上部のtoggleボタンに隠れてしまいUserページの遷移やTableViewの表示に少し時間がかかります。

個人的にはかなり頻繁に使用する項目なのでウィンドウ幅が変わっても表示する使用に変更するのはどうでしょうか？

<br>

この表示を

![Screenshot from 2020-07-03 13-47-41](https://user-images.githubusercontent.com/37650565/86432787-e5867f00-bd33-11ea-8a0b-bd108c589d82.png)

バーが出るように変更

![Screenshot from 2020-07-03 13-48-22](https://user-images.githubusercontent.com/37650565/86432819-fd5e0300-bd33-11ea-9014-5c28175d2a49.png)

**Comment by kenkoooo** [comment]
良さそうです。スマホで表示した時に隠れるように工夫する必要がありそうです。
