### ISSUE TITLE
相対難易度メーター

### ISSUE THREAD

**Issue by MatsuTaku** [kenkoooo/AtCoderProblems#693]
Discussion #469 #643 
Implementation #681

![2020-07-18 (3)](https://user-images.githubusercontent.com/8394202/87805456-4f546c00-c890-11ea-92c8-7acb92eaec2f.png)
![2020-07-18 (4)](https://user-images.githubusercontent.com/8394202/87805458-50859900-c890-11ea-9de9-e73b2eeb286e.png)

## コンセプト
問題に対し難易度情報を提供するという機能は、一般的で理解しやすく、需要の高い機能である。
本機能は、ユーザーの実力に基づいた難易度を提供するUIアイデアの一つである。

具体的には、**相対難易度 = 1-推定正解率** を指標とし、メーター表示でユーザーに対する問題の難易度を表示した。
また、難易度で区分を作ることで問題を大まかに分類し、色によって視覚的に問題の難易度感を視認しやすくした。

### 難易度区分
| 色 | 推定正解率 |
| --- | --- |
| 緑 | 100 ~ 75% |
| 黄 | 75 ~ 25% |
| 赤 | 25 ~ 0% |

### デザイン代案 
https://github.com/kenkoooo/AtCoderProblems/issues/469#issuecomment-653736209 (メーターの長さの仕様が異なる)

## 付録
相対難易度 = 1-推定正解率 = 
![7243fd9f5580d6c06b68ee97a5746298](https://user-images.githubusercontent.com/8394202/87807656-7b252100-c893-11ea-92f4-988c1c409432.png)

**Comment by MatsuTaku** [comment]
色分けを以下のように見直しました。
|色|推定正解率|
|-|-|
|緑|1~3/4|
|黃|3/4~1/3|
|橙|1/3~1/6|
|赤|1/6~0|

AtCoderのレーティングを上げることを目的として問題を解くユーザーは、実力の向上に最も寄与する問題を選んでときたいと考えるのは自然です。
しかし[amylaseさんの記事](http://pepsin-amylase.hatenablog.com/entry/atcoder-problems-difficulty)の**未解決問題**でも言及されているように、どういった問題が精進に向いているかの判断は簡単ではなく、理論的な保証も十分ではありません。

そのため、主観的は判断ではありますが、橙相当を精進向けの難易度になるように色表示を工夫してみました。

![2020-07-18 (9)](https://user-images.githubusercontent.com/8394202/87813588-25557680-c89d-11ea-8431-6a0077a8efb0.png)
![2020-07-18 (10)](https://user-images.githubusercontent.com/8394202/87813600-2dadb180-c89d-11ea-87b0-6a8c4623f79c.png)

**Comment by MatsuTaku** [comment]
ややこしいことせずに単に５色ぐらいに分けるのも良さそう。

**Comment by MatsuTaku** [comment]
- 現在の区分の仕様
https://github.com/kenkoooo/AtCoderProblems/pull/681#issuecomment-660456902

- 表示切り替えチェックボックスや,ToolTipの仕様
https://github.com/kenkoooo/AtCoderProblems/pull/681#issuecomment-662162406

**Comment by kenkoooo** [comment]
https://github.com/kenkoooo/AtCoderProblems/pull/681#discussion_r460390372

**Comment by MatsuTaku** [comment]
> 相対難易度は分かりにくく感じたので、普通に solve probability をそのまま表示するので良さそうです。
https://github.com/kenkoooo/AtCoderProblems/pull/681#discussion_r460390372

なんらかの課題を提供するUIで、難易度を表示するというのは一般的な方法だと認識してます。
[google images](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Fae%2Fba%2F7b%2Faeba7b19d8c597ac0b8920e475dad7fb.png&imgrefurl=https%3A%2F%2Fwww.pinterest.com.au%2Fpin%2F487796203364835633%2F&docid=xbiWro_5x04aoM&tbnid=n5deyIqkhx7N5M&vet=1&w=400&h=300&itg=1&hl=en&bih=975&biw=1920&ved=2ahUKEwihu_GAm-jqAhUSyIsBHQpLBnQQxiAoAXoECAEQGQ&iact=c&ictx=1)
現在の仕様におけるsolve probabilityの立場は、これはそれを提供するUIではなく、あくまで暗黙的な情報として使っているに過ぎないです。
(推定正解率そのものの情報は#691 で達成されていて十分だと思っています)
また、solve probabilityをメータにした場合、簡単すぎる問題ばかりが見た目に目立つ形になり、個人的に気持ちのいいUIではないと感じます。


**もしくは**、色情報だけにして(バーの長さの情報を排除して)、UI要素自体はもう少し目立たない形にする（ https://upsolve.me , https://github.com/kenkoooo/AtCoderProblems/issues/469#issuecomment-653736209 の3みたいに）のも案かなとおもいます
細かい情報は失われますが自然かもしれません。

**Comment by kenkoooo** [comment]
たしかにバーの長さの情報は無くてもいいかもしれないですね。僕は簡単な問題が目立った方が気持ちがいいので。

**Comment by MatsuTaku** [comment]
とりあえずいくつかui作ってみますね。

**Comment by kenkoooo** [comment]
> とりあえずいくつかui作ってみますね。

ありがとうございます。やはり難易度の色と混じってかなり見づらく感じてしまい、現状のUIはどうしても疲れてしまうので、新しく作っていただけるのは大変ありがたいです。よろしくお願いします。

**Comment by MatsuTaku** [comment]
とりあえずバーの長さを変えたもの

## A. 1 - _solve-prob_ (current)
![2020-07-26 (2)](https://user-images.githubusercontent.com/8394202/88460695-037d7480-ced9-11ea-9525-14728dc428c2.png)
![2020-07-26 (3)](https://user-images.githubusercontent.com/8394202/88460696-04160b00-ced9-11ea-865b-86dbcb46a101.png)

## B. _solve-prob_
![2020-07-25h](https://user-images.githubusercontent.com/8394202/88460699-05473800-ced9-11ea-8dad-06009adeac72.png)
![2020-07-25 (1)](https://user-images.githubusercontent.com/8394202/88460698-04aea180-ced9-11ea-9898-3e4d99143895.png)

## C. filled
![2020-07-26](https://user-images.githubusercontent.com/8394202/88460694-02e4de00-ced9-11ea-999d-435a194e66c8.png)
![2020-07-26 (1)](https://user-images.githubusercontent.com/8394202/88460697-04160b00-ced9-11ea-9d96-8e6bc0548c53.png)

**Comment by MatsuTaku** [comment]
簡単に実装できるのはこんなところです。
filledは無難に良いですね。

## D. filled - vertical - left-aligned
![2020-07-26 (6)](https://user-images.githubusercontent.com/8394202/88461090-c6ff4800-cedb-11ea-9a94-de3d2c31b824.png)
![2020-07-26 (7)](https://user-images.githubusercontent.com/8394202/88461088-c5ce1b00-cedb-11ea-9a0c-1692d246903f.png)

**Comment by kenkoooo** [comment]
ありがとうございます。シンプルで見やすくなったと思います。ただどうしても Table だとすでに Difficulty の色があってかなり疲れてしまうので、List など別のページに表示するのはいかがでしょう？

**Comment by MatsuTaku** [comment]
Tableで実装したのは、
- トップページとしてとりあえず
- **ユーザに表示選択の自由がある**
- 最も一覧性の高い画面である
が理由です。

当然List等でも可能なら実装したいですが、他画面は現時点だと表示選択の自由がないので、
どこで使うかについては、後に別Issueで相談した方が良いかなと考えてました。

新ページで相対難易度でまとめた一覧画面を作るなら、なおさら別Issueのほうが良いかなと。

**Comment by kenkoooo** [comment]
了解です。では一旦この issue は close して別の issue を立てますか？

**Comment by MatsuTaku** [comment]
Tableの採用を却下して、Listへの実装で立てるということでしょうか。

**Comment by MatsuTaku** [comment]
## D+. Off: Show Difficulty
![2020-07-26 (10)](https://user-images.githubusercontent.com/8394202/88462669-24999180-cee8-11ea-97ab-c60abafe8be1.png)
![2020-07-26 (11)](https://user-images.githubusercontent.com/8394202/88462667-2400fb00-cee8-11ea-9a19-f8266ce16399.png)

**Comment by kenkoooo** [comment]
> Tableの採用を却下して、Listへの実装で立てるということでしょうか。

はい。今のデザインでは Table に入れるのは厳しいです。僕の思いつく限りではListのProbabilityのカラムを加工するか、別ページを作るかが良いかと思います。

**Comment by MatsuTaku** [comment]
では#681は取り下げます。

List画面のためだけに表示するUIとしては過剰だと思われますので（カラムも存在するので）、Tableで採用されないのであればListへの提案もいたしません。

**Comment by MatsuTaku** [comment]
また新たな一覧画面のアイデアができましたらIssueにしようと思います。
