### ISSUE TITLE
Virtual ContestのCreate Contestで時刻選択時、01~09時が反映されない

### ISSUE THREAD

**Issue by hm90079007** [kenkoooo/AtCoderProblems#696]
確認端末：MacOS Catalina 10.15.5
ブラウザ：Chrome Version 83.0.4103.116

一週間ほど前から、Virtual ContestのCreate Contestで時刻選択時に、01~09をプルダウン上で選択しても、入力ボックスに反映されなくなったと思います。safariやAndroidのChromeでも同じ現象です。一度ご確認頂けないでしょうか。
日付や分は問題なく、時刻でも10時以降は選択可能です。
<img width="718" alt="Screen Shot 2020-07-20 at 19 02 48" src="https://user-images.githubusercontent.com/32905178/87926404-9f177b00-cabc-11ea-9eac-f52eb4cb7f4b.png">

**Comment by kenkoooo** [comment]
ありがとうございます。修正がマージされたので今週中にリリースします。

**Comment by hm90079007** [comment]
ご連絡ありがとうございます。
毎日利用させてもらっています。
引き続きよろしくお願いします

2020年7月21日(火) 1:32 kenkoooo <notifications@github.com>:
