### ISSUE TITLE
Replace diesel with sqlx

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#701]
https://github.com/launchbadge/sqlx

**Comment by kenkoooo** [comment]
現状ではアプリケーションの色んなところにSQLクエリがあってやや厳しい気持ちになっているので、サブクレート（？）っぽい感じでSQLとのやりとりだけをやるクライアントを作りたい気持ちがあります（これが良い設計なのかはあまり自信がないですが…）。

**Comment by kenkoooo** [comment]
> 現状ではアプリケーションの色んなところにSQLクエリがあってやや厳しい気持ちになっているので、サブクレート（？）っぽい感じでSQLとのやりとりだけをやるクライアントを作りたい気持ちがあります（これが良い設計なのかはあまり自信がないですが…）。

この方法を取る場合、実際の進め方としては、
1. sql ラッパー実装
2. diesel を使っているところを少しずつ置き換え
3. diesel 削除

って感じになると思います。

**Comment by magurotuna** [comment]
@kenkoooo 
sql ラッパーというのがあまり理解できておらず確認したいのですが、「SQLとのやりとりだけをやるクライアント」というのは、現状すでにある `src/sql` ディレクトリ以下のもの（[simple_client.rs](https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-backend/src/sql/simple_client.rs) など）とは別のものを作りたい、ということでしょうか？
まだAtCoderProblemsのコードの一部しか読めていないので、的外れな質問だったらすみません。

インクリメンタルに置き換えをしていきたいというのは同意です。ただ sqlx にすると async fn にしないといけないので既存のトレイトをそのまま使い回せないというのが若干厄介かなと想像しています。↓のようにasync版のトレイトを作って、完全に置き換えが完了するまでは共存させる必要がありそう…？

```rust
// 既存のトレイト
pub trait SimpleClient {
    fn insert_contests(&self, values: &[Contest]) -> Result<usize>;
    fn insert_problems(&self, values: &[Problem]) -> Result<usize>;

    fn load_problems(&self) -> Result<Vec<Problem>>;
    fn load_contests(&self) -> Result<Vec<Contest>>;
}

// async をつけたトレイト
#[async_trait]
pub trait AsyncSimpleClient {
    async fn insert_contests(&self, values: &[Contest]) -> Result<usize>;
    async fn insert_problems(&self, values: &[Problem]) -> Result<usize>;

    async fn load_problems(&self) -> Result<Vec<Problem>>;
    async fn load_contests(&self) -> Result<Vec<Contest>>;
}

**Comment by kenkoooo** [comment]
https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
こんな感じで、`atcoder-problems-backend` の中に `sql-client` みたいなクレートを作って、それが `sqlx` への dependency を持つ感じです。`atcoder-problems-backend` は `sql-client` を通じて SQL にアクセスするようになります。

**Comment by magurotuna** [comment]
なるほど、ありがとうございます。
SQLにアクセスする部分の処理と、`sqlx` への依存については `sql-client` 内に閉じ込めるようにしたい、っていう感じですかね。

`sql-client` 内に書く実装の内容は `src/sql` ディレクトリ以下とほぼ同じような感じ、っていう解釈で良いでしょうか。

**Comment by kenkoooo** [comment]
> なるほど、ありがとうございます。
> SQLにアクセスする部分の処理と、`sqlx` への依存については `sql-client` 内に閉じ込めるようにしたい、っていう感じですかね。
> 
> `sql-client` 内に書く実装の内容は `src/sql` ディレクトリ以下とほぼ同じような感じ、っていう解釈で良いでしょうか。

はい、そう考えています

**Comment by magurotuna** [comment]
了解です。やってみようと思います。

**Comment by kenkoooo** [comment]
@magurotuna では一緒にやっていきましょう。無言で巨大プルリクを突然投げるのは怖いのでやめてくださいね。

#706 に sqlx を入れてマージする予定なので、マージしたら sql-client の中に少しずつ作っていき、ある程度できてきたら並行して本体からの呼び出しを少しずつ増やしていく、という感じで進めましょう。

**Comment by magurotuna** [comment]
すみません、癖でとりあえず実装し始めたものを雑にdraftで出してしまってました。気をつけます。
進め方了解です。

**Comment by kenkoooo** [comment]
はい、お願いします。

実装については今の実装と同じく役割ごとに trait を作って `PgPool` について impl していくことを考えています。この実装がベストかは分からないので、もし別の best practice みたいなのがあったら教えてください。

プルリクは trait 単位かそれより小さい単位で作っていくのが良いと思います。これは単純に僕のキャパシティの上限です。

**Comment by magurotuna** [comment]
> 実装については今の実装と同じく役割ごとに trait を作って PgPool について impl していくことを考えています。この実装がベストかは分からないので、もし別の best practice みたいなのがあったら教えてください。

異議なしです。この設計で問題ないように思います。

> プルリクは trait 単位かそれより小さい単位で作っていくのが良いと思います。これは単純に僕のキャパシティの上限です。

了解です:+1:

**Comment by magurotuna** [comment]
@kenkoooo 
レビューとマージありがとうございました。

このあとは、トレイト単位で「これやります」と宣言してから着手する感じで大丈夫でしょうか。問題なければ、ProgressResetManager をやっていこうと思います。

- [x] ProblemListManager
- [ ] ProgressResetManager
- [ ] UserManager
- [ ] VirtualContestManager
- [ ] AcceptedCountClient
- [ ] ContestProblemClient
- [ ] LanguageCountClient
- [ ] ProblemInfoUpdater
- [ ] ProblemsSubmissionUpdater
- [ ] RatedPointSumClient
- [ ] SimpleClient
- [ ] StreakUpdater
- [ ] SubmissionClient

**Comment by kenkoooo** [comment]
そうですね、そんな感じでやっていきましょう。
> このあとは、トレイト単位で「これやります」と宣言してから着手する感じで大丈夫でしょうか。問題なければ、ProgressResetManager をやっていこうと思います。

**Comment by magurotuna** [comment]
続いて `UserManager` に着手します。

**Comment by magurotuna** [comment]
`VirtualContestManager` やります。

**Comment by magurotuna** [comment]
`AcceptedCountClient` やります。

**Comment by magurotuna** [comment]
ContestProblemClient やります。

**Comment by magurotuna** [comment]
LanguageCountClient やります。

**Comment by magurotuna** [comment]
ProblemsSubmissionUpdater やります。

**Comment by magurotuna** [comment]
RatedPointSumClient やります。

**Comment by magurotuna** [comment]
StreakUpdater やります。

**Comment by kenkoooo** [comment]
乙でした…！
