### ISSUE TITLE
Problem List のDifficulty From/To でdiff「-」を抽出できるようにして欲しい

### ISSUE THREAD

**Issue by taoll3** [kenkoooo/AtCoderProblems#702]
はい

**Comment by kenkoooo** [comment]
unset できるようにしたいということ？

**Comment by taoll3** [comment]
「unsetする」という言葉の意味がちょっとわかっていなくて申し訳ないのですが、
現状ですとDifficulty fromあるいは toをどう選択しても「-」の問題を抽出するということが出来ないので、
それが出来るようになると嬉しいです。

**Comment by kenkoooo** [comment]
なるほど、理解しました。Difficultyがついていない問題を抽出したいということですね。具体的な使用シーンをお聞きしても良いですか？

**Comment by taoll3** [comment]
ご理解ありがとうございます。
ちょっと変な使い方をしているかもしれませんが、なるべくSolversが多い問題から解くという精進をしておりまして、
その際にdiffが高い(or低い)問題を省くためにフィルターをかけると、diffがついていない問題が抽出されないことに気付いたためです。
もちろん、Solversでソートした状態の問題リストから、一つずつdiffを目視確認すれば済む話ではありますが、
けっこう手間だと感じたものでして・・・

**Comment by kenkoooo** [comment]
どういうデザインにするのが良さそうですかね？

**Comment by taoll3** [comment]
あまりセンスがいい案が思いつきませんでした。
Difficulty From/To の隣に「Diffucultyが付いていない問題を強制的に含める」のようなチェックボックスを設置するというのはいかがでしょうか。
Difficultyが付いている問題に対してDifficultyが高いわけでも低いわけでもないので、フィルター選択肢に加えるのは不自然かなと考えました。
