### ISSUE TITLE
is the file test-db.sql fully updated?

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#71]
現在の [test-db.sql](https://github.com/kenkoooo/AtCoderProblems/blob/cfe858872c1f6f237fb90632be36fa051013a852/atcoder-problems-backend/src/test/resources/test-db.sql) は本番DBのschemaとどれくらい一致していますか？
こちらにはindexが張られていませんが、本番のDBもそうなっていますか？

**Comment by kenkoooo** [comment]
たぶん反映されていないです。反映します。

**Comment by kenkoooo** [comment]
本番DBも同じスキーマでした。かつてはindexを張っていたと思いますが、DBサーバーを移行してからは張られていなかったぽいです。

**Comment by kmyk** [comment]
確認ありがとうございます。

となるといくつか貼るべきindexがあるはずなので調べて見つけたら報告します。

**Comment by kenkoooo** [comment]
:pray: :bowing_man: :pray:
