### ISSUE TITLE
fronted: Extended user name views like Topcoder

### ISSUE THREAD

**Issue by MatsuTaku** [kenkoooo/AtCoderProblems#718]
Userページでユーザ名がレーティングで装飾されていたら、
モチベーション上がる気がするのですがどうでしょう。

![2020-07-29 (6)](https://user-images.githubusercontent.com/8394202/88725742-861b6380-d167-11ea-9d53-b0375449d307.png)
![2020-07-29 (7)](https://user-images.githubusercontent.com/8394202/88725746-887dbd80-d167-11ea-8903-2730c787da48.png)
![2020-07-29 (8)](https://user-images.githubusercontent.com/8394202/88725745-87e52700-d167-11ea-8534-a0ada0d6b8c0.png)
![2020-07-29 (9)](https://user-images.githubusercontent.com/8394202/88725744-87e52700-d167-11ea-8cda-d0c71587685d.png)
![2020-07-29 (10)](https://user-images.githubusercontent.com/8394202/88725743-874c9080-d167-11ea-8b57-ccd3be22b74b.png)

ユーザのレーティング変化による成功体験はユーザのモチベーション維持にとって重要な要素であり、
レーティングの変化をより機敏に感じられるデザイン案についてはchokudaiさんもいくつかコメントを残されています。
https://twitter.com/chokudai/status/1282615424891289601
TopCoderのレートアイコンはchokudaiさんも高く評価していて、
https://twitter.com/chokudai/status/1282621144206581760
AtCoderでは権利の問題で難しいとのことですが、Problemsでならやってもいいのではないでしょうか。
(すでに問題diffに使っていますが笑)

### Implementation
https://github.com/kenkoooo/AtCoderProblems/compare/master...MatsuTaku:user-rating-circle

**Comment by kenkoooo** [comment]
良さそうですね。現状のDark だと茶色と橙色が見分けづらいという問題があって、Difficultyに関しては問題にならない（AGC-Cが茶でないことは問題を読まなくてもわかるので）のですが、ユーザーに関しては問題になるかもしれません（ならないかもしれません）。

**Comment by MatsuTaku** [comment]
Dark themeを手動で対応する場合、色の使い方を工夫しないと見づらいというのはあるあるですね。

メインカラーの明度を上げることで見やすくするというのはよく使われるテクニックです。
文字色は現状でもいいかもしれませんが、アイコンカラーはもう少し彩度高めにしてもいいかもしれません。

**Comment by MatsuTaku** [comment]
Userページに関してはあまり問題なさそうです。
利用する上で全く知らないUserIDのページを見ることもないでしょから。

順位表や提出一覧で使うなら問題になるかもしれません。

**Comment by kenkoooo** [comment]
:+1:
