### ISSUE TITLE
Dark theme でレート色（茶-橙）が見分けづらい

### ISSUE THREAD

**Issue by MatsuTaku** [kenkoooo/AtCoderProblems#720]
https://github.com/kenkoooo/AtCoderProblems/issues/718#issuecomment-665421368
https://twitter.com/search?q=Atcoder%20Problems%20%E6%A9%99%20%E8%8C%B6&src=typed_query

### Related
#363

**Comment by MatsuTaku** [comment]
> https://github.com/kenkoooo/AtCoderProblems/issues/718#issuecomment-665619413
> Dark themeを手動で対応する場合、色の使い方を工夫しないと見づらいというのはあるあるですね。
> 
> メインカラーの明度を上げることで見やすくするというのはよく使われるテクニックです。
> 文字色は現状でもいいかもしれませんが、アイコンカラーはもう少し彩度高めにしてもいいかもしれません。

**Comment by southball** [comment]
![image](https://user-images.githubusercontent.com/6523469/88884672-aaf7ff80-d269-11ea-848b-dd9348aa2008.png)

このような色はどうですか。

**Comment by MatsuTaku** [comment]
主観ですが
Orangeとても見やすいです。
Brownはもう少し灰と区別できるといいと思います。

**Comment by southball** [comment]
@MatsuTaku これはどうですか。（`#B08C56`）

![image](https://user-images.githubusercontent.com/6523469/89016806-eff46280-d34b-11ea-8082-d2a30a9241db.png)

読みやすさと見分けやすさのバランスが難しいですね…

**Comment by MatsuTaku** [comment]
@southball 
いいと思います！
