### ISSUE TITLE
Suggestion: Show Public/Private Contest in My Contests

### ISSUE THREAD

**Issue by southball** [kenkoooo/AtCoderProblems#733]
My Contest のページのテーブルに、コンテストは Private か Public かを表示したいと思っています。

しかし、Virtual Contests のページで表示する理由はないそうです。すべてが Public ですから。

この機能が使いたい人があるかないかを聞きたいです。

![image](https://user-images.githubusercontent.com/6523469/89129622-3c4cc780-d531-11ea-8043-eb34bb0b7bc7.png)

**Comment by kenkoooo** [comment]
良いと思います。カラムを作っても良いとは思いますが、My Contests と Recent Contests で Table を分けるのは面倒なので、Title のところに badge をつけるとかで良いと思います。

**Comment by southball** [comment]
![image](https://user-images.githubusercontent.com/6523469/89150359-f7587d80-d590-11ea-9ab5-944aa56cb2e9.png)
![image](https://user-images.githubusercontent.com/6523469/89150383-02aba900-d591-11ea-9e5a-c9db282ccdc2.png)

Recent Contests にも Badge を付けますか？それとも Props を作って、Recent Contests に付けないようにしますか？

**Comment by kenkoooo** [comment]
Privateバチャ機能の存在を知らしめる良い機会になると思うので、Recent Contests にもつけておいて良いと思います。
