### ISSUE TITLE
Climbingのチェックボックスについて

### ISSUE THREAD

**Issue by sirogamichandayo** [kenkoooo/AtCoderProblems#748]
![image](https://user-images.githubusercontent.com/47171414/89702848-5ac32080-d980-11ea-9f69-3f3854d575d3.png)
ここもtoggle switchにしませんか？

**Comment by kenkoooo** [comment]
あとColered じゃないときは非表示にしてほしいですね。

**Comment by sirogamichandayo** [comment]
ありがとうございます。分かりました。
