### ISSUE TITLE
バチャのユーザー名にレート色をつける。

### ISSUE THREAD

**Issue by makutamoto** [kenkoooo/AtCoderProblems#753]
AtCoderのランキングのようにバチャのユーザー名にもレート色をつけると、どのくらいのレベルの人が参加しているのかが分かって良いと思いました。
ただどのくらいのレベルの人が参加しているのかがひと目でわかることにより、バチャ参加への心理的ハードルが上がる可能性があるのでOnOff機能をつけておくと良いと思います。

**Comment by makutamoto** [comment]
![image](https://user-images.githubusercontent.com/34860673/89713531-3e9c9f00-d9d3-11ea-8212-10d3ebaa969f.png)
このように、名前が長いと改行されて見栄えが悪いです。
そのためユーザー名の欄を大きくしたいのですが、方法がわからないため保留します。

**Comment by southball** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/34860673/89713531-3e9c9f00-d9d3-11ea-8212-10d3ebaa969f.png)
> このように、名前が長いと改行されて見栄えが悪いです。
> そのためユーザー名の欄を大きくしたいのですが、方法がわからないため保留します。

いい方法かはわからないけど、`white-space: nowrap;` で解決できますか？

**Comment by makutamoto** [comment]
解決しました。ありがとうございます！！！

**Comment by makutamoto** [comment]
@kenkoooo
UserNameLabelにレート取得機能を統合してしまっても良いでしょうか？
レート付きのユーザーラベルは結構使いどころは多いと思います。
ただ、Componentにネットワークにアクセスする機能をつけたくないのもわかりますが…

**Comment by kenkoooo** [comment]
> @kenkoooo
> UserNameLabelにレート取得機能を統合してしまっても良いでしょうか？
> レート付きのユーザーラベルは結構使いどころは多いと思います。
> ただ、Componentにネットワークにアクセスする機能をつけたくないのもわかりますが…

今の AtCoder を proxy してるAPI だと1回のアクセスで1人分のレートしか取得できないですよね。これは料金が高いので、例えばバチャで毎回5-10回のアクセスが来るようになると破産してしまいます。何か良い方法を考えたいですね。

**Comment by makutamoto** [comment]
> > @kenkoooo
> > UserNameLabelにレート取得機能を統合してしまっても良いでしょうか？
> > レート付きのユーザーラベルは結構使いどころは多いと思います。
> > ただ、Componentにネットワークにアクセスする機能をつけたくないのもわかりますが…
> 
> 今の AtCoder を proxy してるAPI だと1回のアクセスで1人分のレートしか取得できないですよね。これは料金が高いので、例えばバチャで毎回5-10回のアクセスが来るようになると破産してしまいます。何か良い方法を考えたいですね。

日付が変わるまでLocalStorageにキャッシュしておくとかいった感じでしょうか。
それとも、そもそも一人ずつ取得しなければならないことに問題がありますか？
だったら、参加者がJoinボタンを押した時点で参加者リストにレート情報も登録といった感じが良いんでしょうか…

**Comment by kenkoooo** [comment]
大丈夫かもしれないです。今のレート取得は横着して https://atcoder.jp/users/kenkoooo/history/json をプロキシして叩いていて、これには最新レート以外の情報も含まれていて結構重い印象があったのですが、意外に大したことないサイズだったので、とりあえずやってみても大丈夫かもしれないです。

最初に考えていたのは、以下のような感じのやつです。とりあえず上記の方針でやってみて、やっぱり料金が大変なことになったら以下の方針に切り替えたら良いと思います。
- ユーザーのレートを格納したDBテーブルを作る
- 週に1回くらいレート一覧をクロールしてDBに保存
- ユーザーのリストを渡すとレートのリストを返すAPIを作る

**Comment by makutamoto** [comment]
わかりました。やってみます！

**Comment by makutamoto** [comment]
![image](https://user-images.githubusercontent.com/34860673/89760110-a0215280-db26-11ea-9161-8a2e05621b63.png)
とりあえず動くようになりました。
オンオフできるようにします。

**Comment by makutamoto** [comment]
![image](https://user-images.githubusercontent.com/34860673/89768157-36a94000-db36-11ea-9add-70673064c885.png)
![image](https://user-images.githubusercontent.com/34860673/89768203-44f75c00-db36-11ea-906b-d707fa26093c.png)
オンオフ機能をつけました（デフォルトで無効）

**Comment by makutamoto** [comment]
@kenkoooo
https://github.com/kenkoooo/AtCoderProblems/blob/362b9b4c2ca29bb9ce320c3e67702d8a0bd04293/atcoder-problems-frontend/src/utils/CachedApiClient.ts#L392-L401
これなんですがMapがImmutableMapになっているのは仕様ですか？
これではキャッシュとしての機能を果たしていないように見えます。
実際DevToolsでも、同じリクエストが何度か飛んでいました。

**Comment by makutamoto** [comment]
```typescript
let RATING_INFO_MAP = Map<string, Promise<RatingInfo>>();
export const cachedRatingInfo = (user: string): Promise<RatingInfo> => {
  const info = RATING_INFO_MAP.get(user);
  if (info) {
    return info;
  }
  const p = fetchRatingInfo(user);
  RATING_INFO_MAP = RATING_INFO_MAP.set(user, p);
  return p;
};
```
とりあえずこうしておきました。
