### ISSUE TITLE
バチャ生成のときのデフォルト設定(Public State)について

### ISSUE THREAD

**Issue by sirogamichandayo** [kenkoooo/AtCoderProblems#755]
![image](https://user-images.githubusercontent.com/47171414/89737279-b093e780-daaa-11ea-8fb5-7026a9ba66eb.png)
現状デフォでは`private`ですが、
`public`にしたほうがいいのではないでしょうか

個人的にはバチャを`private`で立てるのは相当限られているのではないかと思います。
意見お願いします。

**Comment by MatsuTaku** [comment]
バチャの使い方は個人差があると思いますので，
LocalStorageに保存しておくのが良いかもしれません．

default を`public`にするのは一般的な気がします.

**Comment by sirogamichandayo** [comment]
助言ありがとうございます。実装してみました。
