### ISSUE TITLE
Virtual Contest の順位表を見やすくする

### ISSUE THREAD

**Issue by MatsuTaku** [kenkoooo/AtCoderProblems#761]
現時点でのVirtual Contestの順位表は、以下の理由により見づらいと感じます。

- [ ] A. table headerに問題タイトルを表示しており、タイトルが改行されるのと、cell幅が間延びしている

- [x] B. cellの余白が大きく、一覧性が低い
Resolved by #762

**Comment by MatsuTaku** [comment]
# 改善案
## A
(問題番号, タイトル)を別テーブルで表示し、順位表headerは問題番号のみを表示する。

## B
cellの`<p>`要素のmarginを0にする

#### Before
![2020-08-12](https://user-images.githubusercontent.com/8394202/89941478-0953b380-dc56-11ea-8529-0e659f5f1ec8.png)

#### After
![2020-08-12 (1)](https://user-images.githubusercontent.com/8394202/89941494-0e186780-dc56-11ea-82cf-41393fa7c39a.png)

Atcoderの順位表はもっと切り詰めてるので、cellのpaddingを小さくしても問題ないかもしれません。

**Comment by MatsuTaku** [comment]
@kenkoooo 
Aは未実装なので、openにしていただけないでしょうか。

**Comment by MatsuTaku** [comment]
Aの改善はこんな感じでどうでしょうか。

![2020-08-14 (1)](https://user-images.githubusercontent.com/8394202/90224618-e3dbcb00-de4a-11ea-83bd-406e1e774e6b.png)

## 仕様
- 問題タイトルを別で持つメリットが有るのはコンテストModeが`Normal`のときなので、`Normal`の場合のみ問題テーブルを表示

## 変更点
- コンテンツタイトル"Problems", "Standings"を追加
- `Switch`の位置を"Standings"の右に移動
- 順位表
  - ヘッダの問題欄は問題番号のみ表示
  - 可読性のため、borderを追加（これは自分の好みです。カラムが多いのでこちらのほうが良いと思いました。）

## その他の修正
- "Remaining"が２箇所で表示されていたため、左側テーブルの"Remaining"を削除

## 未解決
- 問題ごとのScore(`VirtualContestItem.point`)が`undefined`のときのスコア取得方法

**Comment by MatsuTaku** [comment]
Table border なし
![2020-08-14 (2)](https://user-images.githubusercontent.com/8394202/90226966-cd377300-de4e-11ea-83dd-620a015d5dfe.png)

**Comment by MatsuTaku** [comment]
> * "Remaining"が２箇所で表示されていたため、左側テーブルの"Remaining"を削除

#766 で修正されました

**Comment by MatsuTaku** [comment]
> ## 未解決
> * 問題ごとのScore(`VirtualContestItem.point`)が`null`のときのスコア取得方法

現在のスコアを管理しているフロントのデータは
- `VirtualContestItem.point`: バチャ生成時のユーザ設定のスコア。未定義なら`null`
- `Submission.point`: ユーザの投稿に対するスコア

の２つで、フロントでのスコア表示時は、`VirtualContestItem.point`がsetならスコアを上書きする仕様になっていると思われます(あってますか)。

これは、バチャ生成時に任意のスコアが設定されていなければ、バチャのProblemsのpointにあらかじめ問題のデフォルトのスコアを入れておくのが良いと思いますが、如何でしょうか。

この方針で行く場合、APIの仕様をいじる可能性があるので、ご意見をお願いします。

**Comment by kenkoooo** [comment]
すみません、何が問題になっているのか理解していませんが、たぶん合ってると思います。何も理解しないで書いておくと、部分点の扱いやマラソン問題の扱いが難しそうです。

**Comment by MatsuTaku** [comment]
### 手動でスコアが設定されているコンテスト
![2020-08-15 (6)](https://user-images.githubusercontent.com/8394202/90310211-84ed8300-df2a-11ea-8207-a0758bf08362.png)
### されていないコンテスト
![2020-08-15 (7)](https://user-images.githubusercontent.com/8394202/90310210-8454ec80-df2a-11ea-91a5-204cb6de180d.png)


前者は`VirtualContestItem.point`を使っていて、
`null`の場合に適切なスコアを取得するためのデータがフロントにないという問題です。

この問題は今回の実装で新たに発生したわけではなく、もともとあったものです。

**Comment by MatsuTaku** [comment]
一応、コンテストはスコアを競うゲームである以上、問題ごとの配点が予め公開されていることは重要ではあります。
ただ暫定的にスコア配点提示機能をなしのままでよいのであれば、とりあえず上記フロント改修でPRにします。

**Comment by kenkoooo** [comment]
なるほど、問題一覧に配点を表示したいということだったんですね。マラソンや部分点の処理が難しいですし、そもそも[AtCoder の問題の配点を見極めるのは非常に難しい](https://atcoder.jp/contests/dwacon5th-prelims/tasks/dwacon5th_prelims_b)ので、現状の通り設定された配点が null ならば提出に基づいて点数が決まるというので良いと思います。

**Comment by MatsuTaku** [comment]
了解です。ではこのままの仕様でいきます(same as origin とか表示しておきます)

一つだけ改修してPRにします。
使っていて、問題数が多い場合に順位表がスクロールしないと見えないのは不便なので、"Problems"と"Standings"はタブで分けようと思います。
