### ISSUE TITLE
Listビューのソートカラムをクエリパラメータで表現できるようになってほしい

### ISSUE THREAD

**Issue by uechoco** [kenkoooo/AtCoderProblems#786]
AtCoderProblemsのおかげで学習がとても捗っております。

表題の機能要望です。

私は特定のdifficulty(e.g. 茶色)の問題をdifficultyの小さい順に解くような学習方法を取っています。
例えば `https://kenkoooo.com/atcoder/#/list/{userID}?fromDiff=500&toDiff=799` のようなURLを常用しております。

ところが、このURLを更新をしてしまうと、
Problem Listのソート順がリセットされてします。（おそらくDate降順で表示し直される？）
Difficultyの昇順になるようにカラムをクリックするのが少し手間です。
できれば、何度開き直してもDifficulty昇順で開けるようになっていてほしいです。

例えば、URLクエリパラメータに `&sortBy={data-field}&sortOrder=asc` というようなものをつけて、
そのパラメータでListビューのソートカラムの初期設定が決まり、描画されるような状態になっていると嬉しいです。

よろしくおねがいします。

**Comment by t-mangoe** [comment]
クエリパラメータではないですが、localStorageにソートのキーを保存するようにして、
ソート順がリセットされないようにしてみました。
プルリクを投げてみますので、レビューをお願いします。
