### ISSUE TITLE
バーチャルコンテストにおける点数表示に関するバグ報告

### ISSUE THREAD

**Issue by eS-eF** [kenkoooo/AtCoderProblems#790]
【バグ報告】
- https://kenkoooo.com/atcoder/#/contest/show/f1fd5759-0b54-4365-974e-6681a3837443 において、一度解いて反映されていた点数が再び未提出の状態に戻る現象がありました。

- 確認したのは私(eSeF)の点数表示で、17〜20、22〜24問目がコンテスト時間内に提出・ACしているのですが表示がありません。１度、少なくとも開始から311:03:27時点で表示があったことは確認しています。（他の参加者については未検証です）

- 参加者・問題数が非常に多いのでそれが原因かもしれません

**Comment by kenkoooo** [comment]
データ転送料金とデータ読み出し料金を抑えるために1つのバチャで取得できる提出数の上限を2000件にしていて、その上限を超えているのが原因のようです。せっかく参加者がたくさんいるので何か良い方法を考えていですが、お金もそんなに無いので、難しいところですね……

**Comment by kenkoooo** [comment]
パッと考えつくのは
- データベースから読み出す件数の上限を緩和する
  - これはどこまで緩和して良いのかは謎
  - Burst Credit を使い切ると数分間サービスが落ちる
- バチャ専用のエンドポイントを作り、提出一覧ではなく、それを aggregate した後の standings を返す
  - フロントエンドはそれを表示するだけになる

**Comment by southball** [comment]
専用のエンドポイントで aggregate した後の standings を返し、それをキャッシュ（1分間？）したらデータ転送・読み出し料金とサーバーロードも抑えますか？

**Comment by kenkoooo** [comment]
たしかに、どのくらい抑えられるかは分かりませんが、サーバーサイドでキャッシュするのは良いですね。

**Comment by kenkoooo** [comment]
いよいよこれをやるときが来た for #1083

**Comment by kenkoooo** [comment]
とりあえずDBをprovisionedにして、リクエストを分割してAPIを叩きまくることで表示はできるようになった…
