### ISSUE TITLE
Tableの(ABC/ARC)-Likeのテーブルはカラムそろえていいのでは

### ISSUE THREAD

**Issue by MatsuTaku** [kenkoooo/AtCoderProblems#793]
つまり、
`ContestTable -> AtcoderRegularTable`
にしてしまっていいと思います。

**Comment by t-mangoe** [comment]
簡単に実装してみました。こんな感じでしょうか。

![スクリーンショット 2020-10-03 10 27 16](https://user-images.githubusercontent.com/22494246/94980305-73584d00-0563-11eb-9be0-7cfa4691230e.png)

**Comment by MatsuTaku** [comment]
いいと思います

**Comment by t-mangoe** [comment]
ありがとうございます。プルリク投げてみます。
