### ISSUE TITLE
自分の言語別提出順位が見たい！

### ISSUE THREAD

**Issue by RheoTommy** [kenkoooo/AtCoderProblems#795]
例
greedy_imosはRustでn番目に提出が多い（n位）

みたいなのお願いします！！！

**Comment by kenkoooo** [comment]
できなくはないんですけど、そんなに需要がないので、組み込むまではしなくてもいいかなと思います。

一応全データは公開しているので、自分で集計しようと思えばできます。
https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/api.md#datasets

**Comment by kenkoooo** [comment]
一旦閉じますが、もし追加で何かあればいつでも reopen してください
