### ISSUE TITLE
バチャの開始時刻カウントダウンがほしい

### ISSUE THREAD

**Issue by w0mbat-kyopro** [kenkoooo/AtCoderProblems#799]
機能要望でいきなりissueを作っても大丈夫でしょうか？ 公式コンテストのような開始時刻カウントダウン表示がほしいです。
現状では2分前くらいからPCの時計をにらみつけて、時間になったらえいやっと更新ボタンを押しています。

厳密さを求めてサーバーと時刻を同期しないといけないとすると、言葉で言うほど簡単ではないのかもしれません。
ローカル時刻だけでカウントダウンするのでも十分うれしいです。

**Comment by kenkoooo** [comment]
> 機能要望でいきなりissueを作っても大丈夫でしょうか？ 

大丈夫です！

**Comment by w0mbat-kyopro** [comment]
やったー対応ありがとうございます！
