### ISSUE TITLE
Completed problems not highlighted

### ISSUE THREAD

**Issue by hoke-t** [kenkoooo/AtCoderProblems#806]
Hi, none of my completed AtCoder problems are highlighting. I did not change my username recently or ever, and I confirmed with someone else that their completed problems are not highlighting either.

**Comment by kenkoooo** [comment]
Thank you for using my service. Could you let me know your username and the version of your browser? Since I only tested with the latest browsers, I guess your browser is not up-to-date.

**Comment by hoke-t** [comment]
Hi, I am on Firefox 81.0.1

**Comment by kenkoooo** [comment]
Thanks. I confirmed it's highlighted with your username.
How does the following look like?
https://kenkoooo.com/atcoder/#/table/hoke_t

**Comment by hoke-t** [comment]
That looks as expected (the problems are highlighted). I guess it only happens when I am logged in and looking at the table at https://kenkoooo.com/atcoder/#/table/

**Comment by kenkoooo** [comment]
I see. To highlight the problems, you don't need to log in. You just need to put your username into the text box on the top left. Since it's really confusing, let me fix it in the future.

**Comment by hoke-t** [comment]
Oh, cool! Thank you.

**Comment by kenkoooo** [comment]
It should be improved by #760 .
