### ISSUE TITLE
Proposal: withdrawal of v2 API; It may be better to let clients call results API multiple times

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#81]
resultsの新APIが `/v2/results?users=wata,iwiwi,chokudai` という形をしていますが、 `/v3/results/wata` `/v3/results/iwiwi` `/v3/results/chokudai` と3回叩かせた方が適切かもしれません。前者ではキャッシュさせたり静的ファイルに落としたりするのが難しいですが、後者ならなんとかなりそうです (ただし未検証で、接続回数が増える分で前者が有利の可能性もあります)。

他のAPIについてはキャッシュや静的ファイルを用いる (#76) ことになるでしょうし、ひとまずそれをしてみてresultsにも適用できるかの様子を見てから新APIの仕様を固定するのが良いと思います。後からでもv3としてendpointは足せますが、もしv1 v2 v3と3種並ぶことになるとつらそうです。なのでひとまず `/v2/results` の保留を提案します。どうでしょうか？

**Comment by kenkoooo** [comment]
現状の `results` のデザインは悪くて、例えば `user1`, `user2`, `user3` の提出をまとめて取得したい時、 `results?rivals=user1,user2,user3` を1回叩くことで得られますが、多くのクライアントは `results?user=user1`, `results?user=user2`, `results?user=user3` をそれぞれ同時に叩いています。これによって瞬間的にサーバーに強い負荷がかかることがあるので、できれば `/v2/results` は入れたいです。

**Comment by kmyk** [comment]
`results?user=user1&rivals=user2,user3` というデザインが分かりにくいというのは理解しています。
「これによって瞬間的にサーバーに強い負荷がかかることがある」は昨日までは実際に正しかったのですが、実は #78 で張ったindexによりほぼ解決されています。
その上で「`results?user=wata` や `results/wata` という形の方がさらなる最適化がしやすい」というのが主張です。

---

indexにより解決されたというのは例えば下のようなコマンドをそれぞれ実行してみてもらえば分かると思います。以前であれば前者は後者のちょうど7倍遅かったはずですが、現在では鯖の調子によりますがほぼ変わらないか大きくても3倍程度でしかないはずです。

-   `time ( for user in wata iwiwi chokudai kimiyuki kenkoooo kmjp beet ; do curl 'https://kenkoooo.com/atcoder/atcoder-api/results?user='$user ; done > /dev/null )`
-   `time curl 'https://kenkoooo.com/atcoder/atcoder-api/results?user=wata&rivals=iwiwi,chokudai,kimiyuki,kenkoooo,kmjp,beet' > /dev/null`

データベースの気持ちになっていきましょう。
indexが張られる前は以下のような雰囲気の処理をしていたのでusersの個数に依らずが何であれ O(全提出数) かかっていたので、まとめた方が得でした。

``` c++
vector<Submission> results(set<string> users) {
    for (auto row : submissions) {
        if (users.count(row.user_id)) ...
    }
}
```

indexが張られたことにより以下のような O(結果に含まれる提出数) の処理に高速化されています。なので呼び出し回数には依らず全体での取得内容が同じなら速度はだいたい同じです。

``` c++
vector<Submission> results(set<string> users) {
    for (string user_id : users) {
        auto l = submissions.lower_bound(user_id);
        auto r = submissions.upper_bound(user_id);
        for (auto it = l; it != r; ++ ir) ...
    }
}
```

---

しかし今でも `results?user=kimiyuki` は0.6 ~ 1秒ぐらいかかっています。これは単純にデータ量が多い (その人の提出の量にもよるが私の場合は 65KB) ためです。通信環境によりますが鯖上での処理に平均0.3秒かかり通信に平均0.4秒かかってます。

これを解決するにはキャッシュをするしかありません。
HTTPには `Cache-Control` や `If-Modified-Since` というheaderがあり、これら適切に設定すれば、前回の通信時刻から結果から変化がなければクライアント側でキャッシュしておいた結果を思い出すだけになり、2回目以降のAPI呼出がすべてが省略されて実質0秒で終わるようになります。
サーバ側でも結果のjsonを静的ファイルとして一時的に保存しておくことでさらに高速化ができます。

そして、これをするときに `/v2/results?users=wata,iwiwi,chokudai` という形だと `/v2/results?users=wata` や `/v2/results?users=wata,chokudai,iwiwi` と別のAPI呼出の扱いになってしまい、キャッシュの利用ができません。となると現状で性能が頭打ちになってしまい悲しいです。

---

以上のような理由で `/v2/results` の保留を提案しています。よろしくお願いします。

**Comment by kenkoooo** [comment]
なるほど理解しました。そうしましょう。

**Comment by kmyk** [comment]
ありがとうございます。
