### ISSUE TITLE
Fix the ARC Pie chart to fit the table

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#827]
Table では ARC の A-D 問題を大量に C-F にずらしましたが、Pie Chart 上ではずらしていないので、こちらもずらしたほうが良さそうです。
![image](https://user-images.githubusercontent.com/9150073/102163065-b9b81980-3ecd-11eb-8a15-49e082659711.png)
![image](https://user-images.githubusercontent.com/9150073/102163118-df452300-3ecd-11eb-80e7-14ba6d330def.png)

**Comment by netyo715** [comment]
A~Fのどの問題であるかは問題のタイトルの一文字目で判定すれば良いですか？
