### ISSUE TITLE
https://kenkoooo.com/atcoder/proxy を使ってもいいですか？

### ISSUE THREAD

**Issue by tamuhey** [kenkoooo/AtCoderProblems#836]
自作ツール（公開していない）で proxy APIを使いたいのですが、使っても良いでしょうか？
ユーザのレートを取得するために使いたいと思っております。

**Comment by kenkoooo** [comment]
データ転送料が課金されるので、使わないでいただけますと大変ありがたいです。URLを書き換えるだけで全く同じデータが得られます。

例)
https://atcoder.jp/users/kenkoooo/history/json

**Comment by tamuhey** [comment]
ありがとうございます。それではatcoder.jpの方のURLを使用することに致します。
