### ISSUE TITLE
Recommendationにコンテストの種類を絞る機能を

### ISSUE THREAD

**Issue by monhime** [kenkoooo/AtCoderProblems#837]
「ABCの過去問に絞ってdiff順に解きたい」というときに便利になると思います。
ProblemsのページにあるようなABC、ARC、AGC、ABC-like....という分類だけでなく、Rated対象による分類でも絞れるようになると良いと思います。

**Comment by kenkoooo** [comment]
現状の List のフィルタリング昨日が強いので、それでなんとかなりませんかね？

**Comment by monhime** [comment]
確かに今のままでも、Rated対象の級による○の色ですぐ分かりますし、なんとかなりそうです。
