### ISSUE TITLE
Perl6がRakuに改名されたことについて

### ISSUE THREAD

**Issue by kotatsugame** [kenkoooo/AtCoderProblems#839]
以前 #51 と #52 でPerlとPerl6を区別しましたが、このPerl6は現行環境のRakuと同じ言語を指します。
また、すでに言語名がPerl6の状態で提出することは不可能なので、以前の提出も含めて名称をRakuに統一するのがよいと考えています。

ちょっとわかりにくくなるかもしれませんが、そもそもユーザが少ない言語なので、あまり影響はないと思います。どうでしょうか。
よさそうだったらプルリクエストの作成も行いたいです。

**Comment by kenkoooo** [comment]
いいと思います。現状の `Perl` と `Perl6` を区別している箇所で `Perl6` を `Raku` に置き換えるようにすれば良さそうです。
