### ISSUE TITLE
Let clients cache contents

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#84]
クライアントが「前回は5分前にAPI呼出したんですがなにか更新ありました？あったら新しいやつください。なかったら前回の結果を再利用するので処理はいらないです」みたいな感じでAPI呼出をしてくれると嬉しいと思うんですが、実は適切にHTTP response headerを設定することでこれをしてくれます。
これをやるとさらに高速になるのでやるとよいと思います。

特に `results` のAPIに対してきちんとこれができると、表示の完了までが今の2倍速になり、サーバへの負荷がかなり減ります。

nginxなどreverse proxyのサーバ上の設定ファイルをいじる必要があるので私は手伝えません。
とりあえず参考資料だけ挙げておきます。

-   https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=ja
-   https://developer.mozilla.org/ja/docs/Web/HTTP/Caching

**Comment by kenkoooo** [comment]
一応 EntityTag を見て更新時刻が前と同じだったら 304 になるような適当な実装が `JsonApi.scala` にあるにはあります。ほとんど手付かずなのでまともに動いているとは言い難いですが、これをまともに実装していくという方針もありかもしれません。

**Comment by kmyk** [comment]
#90 をしたので閉じます。
