### ISSUE TITLE
Accepted や Rated Point Sum よりも高難易度の AC が反映されやすい指標を Achievement に追加したい

### ISSUE THREAD

**Issue by fairy-lettuce** [kenkoooo/AtCoderProblems#842]
いつもありがとうございます。機能要望の Issue で申し訳ありません。

精進の量として適切な指標についてはたびたび議論があり、Accepted  数や Rated Point Sum では実力への直接的な影響の少ない簡単な問題が多く反映されてしまうことがよく指摘されています。その解決方法としても様々な方法が提案されていますが、Rated Point の二乗和のほうがより高難易度の AC を反映した値として言及されることが多いように感じます。

そこで、User ページの Achievement の一覧に、Accepted や Rated Point Sum と並べて Rated Point の二乗和 (英語にするなら Squared Rated Point Sum といったところでしょうか) を表示してはいかがでしょうか。

ただ、Achievement の欄には既に縦 2 x 横 4 の 8 種類の情報が表示されており、デザインを多少変える必要があるかもしれません。

**Comment by kenkoooo** [comment]
実装自体は難しくないと思いますが、そもそもなんで2乗なのか理解していないので、詳しく書いていただけるとありがたいです。例えば800点問題1問解くのは400点問題4問解くのと同じくらい大変ってことですか？

**Comment by amylase** [comment]
https://twitter.com/pepsin_amylase/status/1350707199056642048
このツイートで定義した tourist-equivalent effort は @fairy-lettuce さんのほしかった指標に近い気がしています。
実際に使った時間より遥かに短い値が指標になってしまうのはもったいないような気もしますけど。

基準になる人のレートを 400 とかにしてバーゲンセールするほうがいいのかなとも思います。tourist も仮想のレーティング 400 の人もわかりやすさはあまり変わらないので。でも tourist-equivalent はインパクトあるんですよね。

**Comment by amylase** [comment]
あと tourist も人間で年を取るので、将来あらたなトッププレイヤーが現れたときに更新する必要がある定義を採用するのはちょっとためらわれます。top-player equivalent ということにして 4000 固定にするとレーティングインフレ以外には耐えられそう。

**Comment by fairy-lettuce** [comment]
top player-equivalent effort いいですね。二乗和は「より難しい問題を解いたら多く反映される」という性質だけを考えた意味のない数値ですが、この指標は総和にしても意味ある数値でベターだと思います。
