### ISSUE TITLE
バグ報告です。「Hide Completed Contest」をチェックした場合に、E, Fが表示されないです。

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#851]
https://twitter.com/maspy_stars/status/1353445185548521472

> バグ報告です。「Hide Completed Contest」をチェックした場合に、E, Fが表示されないです。
>
> すべてのユーザーでそうなるわけではないっぽいです。
> どころか、他のユーザー名を試しても、私以外でこうなるパターンを今のところ見つけていません。

**Comment by netyo715** [comment]
「表示する行（コンテスト）の問題数」の最大値が列数になってしまうことが原因です。
maspyさんは6問のARC（ARC104～）を全てACし、4問のARCだけが残っている状態なので、問題数の最大値が4になりDまでしか表示されません。

原因がわかっているので直せると思いますが、どんな感じになるのが良いですか？
①「Hide Completed Contest」をチェックしたかどうかで列数は変わらない
②Dまでしかないコンテストだけを表示するとき、列数は4になりEFを表示しない

**Comment by kenkoooo** [comment]
ちゃんと実装を確認してないのでもしかしたら違うかもしれないですが、列数を変えないようにするのが楽ですかね？直感的にも正しい動作のような気がします。
