### ISSUE TITLE
コンテスト終了時刻ちょうどのACがコンテスト中AC扱いになっている

### ISSUE THREAD

**Issue by iilj** [kenkoooo/AtCoderProblems#855]
たとえば ABC でコンテスト開始 100 分時点の提出が AC になったとき，AtCoder 上ではコンテスト終了後の提出として扱われる．
![image](https://user-images.githubusercontent.com/59337901/106375340-9d653300-63ce-11eb-9cde-393d751d80a7.png)

![image](https://user-images.githubusercontent.com/59337901/106375385-dac9c080-63ce-11eb-8603-077a046428d7.png)

https://kenkoooo.com/atcoder/#/table/hal_goldfish
https://twitter.com/kyopro_goldfish/status/1355726969288093697

**Comment by kenkoooo** [comment]
メチャクチャかわいそうだ……
