### ISSUE TITLE
Upgrade sqlx to 0.4 

### ISSUE THREAD

**Issue by magurotuna** [kenkoooo/AtCoderProblems#861]
現時点で sqlx 0.4.2 が最新版となっています。
https://crates.io/crates/sqlx
まだあまり詳しくは見ていないのですが、アップグレードすると sql-client で今よりスマートなコードが書けるようになる可能性があるため、とりあえず最新版にあげることができれば嬉しいなと思います。

**Comment by magurotuna** [comment]
追記: 0.5.1 にあがっていました。進化スピードがすごい。

**Comment by kenkoooo** [comment]
ひえ〜〜〜
