### ISSUE TITLE
Refactor Recommendations

### ISSUE THREAD

**Issue by MatsuTaku** [kenkoooo/AtCoderProblems#867]
現状かなり複雑なコンポーネントになっているのでリファクタリングしましょう．

- [x] 可読性をあげる (#868)
- [ ] filter更新と問題選択更新の分離：依存関係が独立しているので，分離しましょう．
- [ ] filterロジックの分離：フィルタ項目を更新するたびにデータフィールドをすべて作り直すのはやりすぎに見えます．最小限の更新になるようにしましょう
- [ ] 選択問題管理方法の見直し(#866 後)：Setオブジェクトのコピーに対して更新してから元のオブジェクトへ上書きする用になっています．良いソリューションがあるなら直しましょう

**Comment by MatsuTaku** [comment]
- [x] 可読性を挙げる
233a3c5 で良くなりました

- [ ] filter更新と問題選択(selection)更新の分離：依存関係が独立しているので，分離しましょう．
  - filter <= selection
    テーブルと選択問題を管理するオブジェクト関連を1つのコンポーネントにまとめることで解消できます．
  - filter => selection
    selectionのオブジェクト数はユーザ操作で増える程度なので，あまり気にしなくても良いでしょう．

**Comment by MatsuTaku** [comment]
Userページの重さの最大の原因は
`UserPage/index.tsx`が
- 各タブページのオブジェクトの管理を担い過ぎ
- APIからオブジェクト生成する過程で，各APIのレスポンスが帰ってくるたびにindex.tsxのレンダリングが呼び出され，何度もオブジェクトを再生成している

ことだと思います．
なのでレンダリング時間改善を目指すならこれを優先した方がよさそう

**Comment by kenkoooo** [comment]
Userページの表示の重さを感じていないのですが、具体的にどのような操作をすると重く感じますか？

**Comment by MatsuTaku** [comment]
重いから早くしようというよりは，上述したように**Userページが複雑なのでリファクタリングするならこちらを優先した方が良さそう**という主張です．
（レンダリングは遅くても1秒程度なので許容範囲ではあるかもしれません．ただ，Recommendationsのようにオブジェクト生成が重いページを表示した状態でリロードをすると，上述の2つめの理由により3,4回レンダリングしてしまう弊害が重くなるという状況は存在します．）

多くのコントリビューターが触る箇所ですので，**単純で可読性が高く**，**かつ処理の無駄を省く**ようなファクタリングがよいでしょう．
とりあえず以下のような作業をするだけでも良くなると思います．
- 一部の子コンポーネントのみで使われるオブジェクトの生成は子に委託する
- 加えて，子コンポーネントを`React.memo`でメモし，ソースオブジェクトの更新に対してのみコンポーネントの更新を行う．

**Comment by kenkoooo** [comment]
大きいコンポーネントを切り分けて可読性を上げた方が良いのはそのとおりだと思います。再レンダリングも気になる人が多ければ減らしたほうがいいと思います。`useMemo` である程度以上の効果を得られるケースはかなり限られるので、使いどころが難しそうです。

**Comment by MatsuTaku** [comment]
`React.memo`の意図について
そもそもUserでオブジェクト生成を行うようになっている原因は，**最初に親でオブジェクトを生成することで，タブ切り替えの時の無駄なオブジェクト再生成を無くすこと，が目的の一つになっているから**だと思われます．
つまり，単純にオブジェクト生成を子コンポーネントに委託しただけでは，子コンポーネントのレンダリングの度に無駄なオブジェクト生成を繰り返すようになってしまいます．
これを防ぐために，**子への委託**と併せて`React.memo`を用いる必要があるということです．

余談ですが，
`React.memo`, `React.useMemo`は用途が異なるので，簡単に整理します．
- `memo`: 任意のpropsに基づくコンポーネントの生成のメモ化
- `useMemo`: 値(オブジェクト)の計算(生成)のメモ化

これを踏まえて，`memo`ではなく`useMemo`を使うリファクタリング案として，
**各子コンポーネント内でのオブジェクト生成を`useMemo`で管理する**
というものも考えられます．
完全に処理の重複を省くという目的ならこちらが適切ですが，初見の方にコードの意図の理解が難しくなると思われるので，今回のリファクタリングの方法としてはあまり適していないと思います．

**Comment by kenkoooo** [comment]
>  そもそもUserでオブジェクト生成を行うようになっている原因は，最初に親でオブジェクトを生成することで，タブ切り替えの時の無駄なオブジェクト再生成を無くすこと，が目的の一つになっているからだと思われます．

もともとは全ての項目が1ページに表示されていたのですが、項目が多くなりすぎて下の方にある Recommendation に気づかないユーザーが増えたりしたため、タブ化されたという歴史的経緯によるものです。特に再生成を減らしたいという意図はないので気にしなくて大丈夫です。

**Comment by MatsuTaku** [comment]
Userページ全体を考慮するリファクタリングは題意を超えてきたので，別Issueにしようと思います．

また，上記によって
- 前提状況が変わること
- 本Issueの緊急性の低さ
から，本Issueは一旦閉じることにします．
