### ISSUE TITLE
開始前のバーチャルコンテストでは、Estimated Performanceを非表示にする

### ISSUE THREAD

**Issue by polyester-CTRL** [kenkoooo/AtCoderProblems#874]
開始前のバーチャルコンテストでも、Estimated Performanceの数値が表示されてしまいます。
コンテストの開始時刻より前では、「0」または「-」とするのが適切ではないでしょうか。

**Comment by kenkoooo** [comment]
@morioprog さんにお願いすることにしました。

**Comment by kenkoooo** [comment]
`showEstimatedPerformances` という Estimated Performance を表示するかどうかの boolean があるので、ここに「現在時刻がバチャ開始後か？」の情報 `start < now` みたいなのを盛り込めばいいんじゃないかと思います。

https://github.com/kenkoooo/AtCoderProblems/blob/3b2e066c359b80bed5ec140f160925f6af6b4fee/atcoder-problems-frontend/src/pages/Internal/VirtualContest/ShowContest/ContestTable.tsx#L116-L117

**Comment by kenkoooo** [comment]
@morioprog わからないことは何でも聞いてください（ここで言う「何でも」は本当に何でもで、例えばリポジトリをコピーするにはどのボタンを押せば良いか分からない、みたいなものも、じゃんじゃん聞いてください）

**Comment by morioprog** [comment]
ありがとうございます！ 試行錯誤してみます！

**Comment by polyester-CTRL** [comment]
修正ありがとうございました！
