### ISSUE TITLE
AWS のコストを減らそう！

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#878]
そろそろヤバイぜ！！！

- [x] バックエンドのログを減らす。
  - INFOログ、障害時にメチャクチャ役立つので積極的に出したいが、一方で sqlx とか surt とかが出してるやつや、tide の logging を入れているやつは流石に多すぎるかもしれない。
- [ ] 短時間バッチ類を Lambda に移行する。
- [ ] クローラーを減らす

**Comment by southball** [comment]
バックエンドのログに関して、環境変数の `RUST_LOG` を適当に設定したら sqlx と surt のログがなくなると思いますが、どうですか。

**Comment by kenkoooo** [comment]
調べてないですが、多分そうだと思います
