### ISSUE TITLE
Difficulty PiesにもNon-ACをつける

### ISSUE THREAD

**Issue by cpcznksutbeoa** [kenkoooo/AtCoderProblems#879]
現在、AtCoder Pie ChartsではNon-ACの枠がありますが、Difficulty PiesではNon-ACの枠がないので、作っていただきたいです。

**Comment by t-mangoe** [comment]
簡単に実装してみました。こんな感じでしょうか？

![スクリーンショット 2021-04-03 14 34 17](https://user-images.githubusercontent.com/22494246/113469621-efd3d600-9489-11eb-96a6-7b12ce4cb4a0.png)

**Comment by cpcznksutbeoa** [comment]
はい、Non-ACの個数も確認できるようにしてほしいです

**Comment by t-mangoe** [comment]
内訳の個数を拡張してみました。左から、AC、Non-AC、NonSub、の順番です。
また、各グラフの表すものが分かりやすいように、「Rating 〇〇」とタイトルをつけてみました。
![スクリーンショット 2021-04-10 21 45 39](https://user-images.githubusercontent.com/22494246/114270308-9bf75d00-9a46-11eb-9071-1d7523fec75f.png)

**Comment by MatsuTaku** [comment]
> 内訳の個数を拡張してみました。左から、AC、Non-AC、NonSub、の順番です。
> また、各グラフの表すものが分かりやすいように、「Rating 〇〇」とタイトルをつけてみました。
> ![スクリーンショット 2021-04-10 21 45 39](https://user-images.githubusercontent.com/22494246/114270308-9bf75d00-9a46-11eb-9071-1d7523fec75f.png)

グラフタイトルはDifficultyで表す（800-1199）のが適切な気がします．
`List/Difficulty Status`似合わせるのでも良いと思います．

**Comment by t-mangoe** [comment]
グラフタイトルを修正してみました。こんな感じでどうでしょうか？
![スクリーンショット 2021-04-17 10 46 55](https://user-images.githubusercontent.com/22494246/115098390-d8591a80-9f6a-11eb-922f-835394e97759.png)

**Comment by cpcznksutbeoa** [comment]
> グラフタイトルを修正してみました。こんな感じでどうでしょうか？
> ![スクリーンショット 2021-04-17 10 46 55](https://user-images.githubusercontent.com/22494246/115098390-d8591a80-9f6a-11eb-922f-835394e97759.png)

暫く確認してませんでした...
おそらく今、
"AC数/Non-AC数/全体の問題数"
の並びになっているのですが、
"AC数/Non-AC数/Nosub数"
の並びの方が適切かと思います。

**Comment by t-mangoe** [comment]
@cpcznksutbeoa 
ご指摘いただき、ありがとうございます。
ACとNon-ACのカウント数を分けたのに、全体の問題数の数をタイトルに出したままでした。
全問題数からACとNon-ACを引いた、Nosubの個数を表示するように変更しました。

**Comment by cpcznksutbeoa** [comment]
ご変更ありがとうございます。
Github使うのが初めてなので、この後どうすればいいのか分からないのですが、どうすればいいですか？

**Comment by t-mangoe** [comment]
私の方でプルリクを作成して、出してみようと思います。
しばらくお待ちください。
