### ISSUE TITLE
Possible security issue: all files in atcoder-problems-frontend/ are visible

### ISSUE THREAD

**Issue by kmyk** [kenkoooo/AtCoderProblems#88]
https://kenkoooo.com/atcoder/ でディレクトリ `atcoder-problems-frontend/` の内容がすべて生で公開されていることに気付きました。
例えば以下のようなファイルが見えています:

-   https://kenkoooo.com/atcoder/package.json
-   https://kenkoooo.com/atcoder/node_modules/uglify-js/node_modules/commander/typings/index.d.ts

これはすぐには問題にはならないでしょうが、諸々のセキュリティ上の問題に繋がる可能性があります。例えばもしうっかり何かのパスワードやトークンが書かれたファイルをディレクトリ内に置いてしまうと意図せず見られて悪用されるでしょう。
必要なファイルだけを選んで公開することをおすすめしておきます。

(サーバの設定の問題であり今このレポジトリで管理されているファイルに関する問題ではないですが、ここで報告するのが妥当に思えるのでここで報告しました)

**Comment by kenkoooo** [comment]
ありがとうございます。パーミッションをちゃんと設定しました。
