### ISSUE TITLE
Accepted Count for each language のAPIで各言語の1000位以下が取得できない

### ISSUE THREAD

**Issue by uesugi6111** [kenkoooo/AtCoderProblems#882]
容量制限を受けてのデータ量削減で1000位以下を送信しないよう変更があり、完全なデータの取得ができなくなった。
https://greasyfork.org/ja/scripts/415894-atcoder-standings-lang 等のユーザスクリプトは完全なデータが帰ってくる前提のため、何らかの手段で取得できる方法が欲しい。
検討いただけないでしょうか。

**Comment by kenkoooo** [comment]
全て返していた時はかなり通信コストがかかっていたので、（少なくとも今の状況では）同じ情報量を返すAPIを作るモチベーションはありません。すみません。

**Comment by kenkoooo** [comment]
#945 によって部分的に解決できるかも知れません。
