### ISSUE TITLE
レコメンデーションのshow experimentalの設定を保存したい

### ISSUE THREAD

**Issue by erbowl** [kenkoooo/AtCoderProblems#884]
Recommendationでshow experimentalのオン・オフを選べますが、現在はページを開く度に設定する必要があると思ってます。（少なくとも私は毎回やっています。同じような人がいるのではないかと推測。）

一旦、experimental以外から埋めたい人からすると選択結果を他のオプションと同様にlocalstorageに保存するのが良いかなと思ってますがいかがでしょう？

**Comment by kenkoooo** [comment]
良いと思います！

**Comment by fukatani** [comment]
このissueはクローズしてよさそうかもです。
