### ISSUE TITLE
Feature Request: Add Contest Type "AtCoder Heuristic Contest"

### ISSUE THREAD

**Issue by Early0v0** [kenkoooo/AtCoderProblems#887]
Atcoder will create a new contest type ([AtCoder Heuristic Contest](https://atcoder.jp/contests/ahc001)).

I hope it will be in <https://kenkoooo.com/atcoder#/table/> soon.:smile:

**Comment by kenkoooo** [comment]
Thank you for your suggestion. Let's have a new type or put AHCs into the "Marathon" section.
