### ISSUE TITLE
問題カテゴリ別の達成度を表示する

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#909]
この表をみたいなやつを作りたい
https://twitter.com/maspy_stars/status/1380724492004040704

# 実装の方針

UserPage にタブの1つとして作ります。各タブがどのように UserPage からいけるようになっているかは [UserPage/index.tsx](https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-frontend/src/pages/UserPage/index.tsx) を参照してください。最初のステップとして、無を表示するページを作り、それを UserPage のタブの一つとして表示するのが良いと思います。

# フロントエンドの開発環境をセットアップする方法
https://github.com/kenkoooo/AtCoderProblems/tree/master/atcoder-problems-frontend
1. yarn をインストールする
2. yarn する
3. yarn start する

**Comment by holeguma** [comment]
@kenkoooo とりあえず上記の実装方針を目安にしてやってみようと思います。何か分からないことがあったらここに追記します！

**Comment by kenkoooo** [comment]
@holeguma お願いします！

**Comment by kenkoooo** [comment]
@holeguma ローカルで実行できましたか？

**Comment by holeguma** [comment]
@kenkoooo ローカルで実行でてます！今少し忙しくて取り掛かれるのが2、3日後になってしまいそうなのですが大丈夫ですか？

**Comment by kenkoooo** [comment]
@holeguma 全然大丈夫です！

**Comment by kenkoooo** [comment]
@holeguma 忙しそうなので一旦 unassign しておきますが、またやりたくなったらいつでも言ってください！

**Comment by holeguma** [comment]
@kenkoooo すみません😢 またお願いします

**Comment by penicillin0** [comment]
@kenkoooo 
こちらのisuueやってみても良いでしょうか？
- ローカルで実行
- ローカルでログイン

まで出来てるので開発に入れる状態です。

**Comment by kenkoooo** [comment]
@penicillin0 お願いします！

**Comment by penicillin0** [comment]
@kenkoooo 

問題のカテゴリについて相談したいです。
Pieチャートなどでは、`contest_id`からABC, ARC, AGCなどを判断していると思います。
同様のやり方でカテゴリを判断しようとした場合に、以下のカテゴリ分けはできそうです。
- abc
- arc
- agc
- joi
- jag
	
	
	ahc

**Comment by penicillin0** [comment]
@kenkoooo 

問題のカテゴリについて相談したいです。
Pieチャートなどでは、`contest_id`からABC, ARC, AGCなどを判断していると思います。
同様のやり方でカテゴリを判断しようとした場合に、以下のカテゴリ分けはできそうです。
- abc
- arc
- agc
- past
- joi
- jag
- ahc

しかし、企業コンテストやマラソンはidからそのカテゴリを判断することが難しいです。
(例: https://atcoder.jp/contests/jsc2021)

対応策として
- https://atcoder.jp/contests/archive?ratedType=1&category=0&keyword= からスクレイピング(あまり健康的ではなさそう)
- other contestとして集約してしまう
などを考えました。

ご意見伺いたいですmm

**Comment by kenkoooo** [comment]
Table と同じようにしていただいて良いですか？

**Comment by penicillin0** [comment]
@kenkoooo 
[Tableページ](https://kenkoooo.com/atcoder/#/table/)はこのような分類になっていたんですね、気が付かずにすみません...
https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-frontend/src/pages/TablePage/ContestClassifier.ts を流用して実現できそうです！

ありがとうございます!!!

**Comment by kenkoooo** [comment]
:pray:

**Comment by penicillin0** [comment]
@kenkoooo 

カテゴリ別の解答率を出すところまでできたのですが、データの表示形式は[AtCoder Pie Charts](https://kenkoooo.com/atcoder/#/user/penicillin0?userPageTab=AtCoder+Pie+Charts)を真似る感じで大丈夫ですか？？？

**Comment by kenkoooo** [comment]
そうですね、Pie Chart にしましょうか。

**Comment by penicillin0** [comment]
@kenkoooo 

Pie Chartで表示するところまで作ってみました。
確認よろしくお願いします。
#992
