### ISSUE TITLE
ログインしてない状態でバチャのページを開くとログインしてからバチャのページに戻れない

### ISSUE THREAD

**Issue by wakuwinmail** [kenkoooo/AtCoderProblems#912]
https://twitter.com/wakuwinmail/status/1369941817156726786

**Comment by kenkoooo** [comment]
server-side で GitHub API を叩いてトークンを入手したあとのリダイレクト先を動的に変えられるようにするとできます。

**Comment by n4o847** [comment]
これについて、以下のような方針での実装を考えていますがいかがでしょう？

- バックエンド側で /internal-api/authorize にリダイレクト先を渡せるようにする。(例えば `redirect_to` のような名前のパラメータ)
  このとき悪意のある URL にリダイレクトされないように前方一致で validate する。あるいは `#` 以降のみを指定するようにしても良いかも知れない。
- フロントエンド側でログイン先を

  ```typescript
  const CLIENT_ID = `xxx`;
  const redirectUri = `https://kenkoooo.com/internal-api/authorize?redirect_to=${decodeURIComponent(currentUrl)}`;
  const loginLink = `https://github.com/login/oauth/authorize?client_id=${CLIENT_ID}&redirect_uri=${decodeURIComponent(redirectUri)}`;
  ```

  のようなリンクにする。
