### ISSUE TITLE
APIやリソースへアクセスしようとすると403 Forbiddenが返される

### ISSUE THREAD

**Issue by sono8stream** [kenkoooo/AtCoderProblems#920]
- Windows環境でcurlを用いてAPIにアクセスしようとすると，403 Forbiddenが返されました

```
> curl -I https://kenkoooo.com/atcoder/atcoder-api/results?user=MiuraMiuMiu
HTTP/1.1 403 Forbidden
Date: Wed, 21 Apr 2021 13:11:33 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
x-amzn-RequestId: 273f3060-747a-4c7a-aee2-b880256ce77d
x-amzn-ErrorType: ForbiddenException
x-amz-apigw-id: eIqk8E_htjMFlow=
```

- その他のリソースにも同様にアクセスできません
- ブラウザからはアクセス可能でした

何か特別な許可や設定等が必要となるのでしょうか？

**Comment by kenkoooo** [comment]
accept-encoding:gzip してみるとどうですか？

**Comment by sono8stream** [comment]
ありがとうございます，できました．

お手数をお掛けしてしまい申し訳ないです．

**Comment by AbdeltwabMF** [comment]
@sono8stream 
what did you do to make it works?

**Comment by kenkoooo** [comment]
@AbdeltwabMF 
Add a http header "accept-encoding:gzip".

**Comment by AbdeltwabMF** [comment]
@kenkoooo 

### command
``
curl -H "Accept-Encoding: gzip" "https://kenkoooo.com/atcoder/atcoder-api/v3/user/submissions?user=AbdeltwabMF&from_second=0"
``
### output i got it
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.

**Comment by kenkoooo** [comment]
@AbdeltwabMF https://www.google.com/search?q=curl+gzip

**Comment by AbdeltwabMF** [comment]
Thank you , it works.
