### ISSUE TITLE
常設コンテストのクロールが全然できていない

### ISSUE THREAD

**Issue by nebocco** [kenkoooo/AtCoderProblems#927]
#916 を受けて #922 を作りましたが、常設コンテストでは各問題のurl形式が通常のコンテストと異なるため正常に追加できていませんでした。
具体的には、通常は

https://atcoder.jp/contests/abc199/tasks/abc199_a

というように

[コンテストID] / tasks / [コンテストID] _ [問題名]

という形式で記述されますが、例えばAtCoder Beginners Selectionでは最初の問題を除き

https://atcoder.jp/contests/abs/tasks/abc087_b

というように出典元のIDが使われており、practice contestでは

https://atcoder.jp/contests/practice/tasks/practice_1

というように問題名が数字になっています。

一度tasksのページに行って各問題へのリンクを取ってくる必要があるかもしれません。

**Comment by kenkoooo** [comment]
これは practice のみの特殊な仕様で、それ以外の常設コンテストはクロールできているように見えます。practice は何故か通常の開催中コンテストと同じ仕様で、参加登録しないと問題が見れませんし、全ての提出も確認できません。これは謎です。

**Comment by nebocco** [comment]
本当ですね
ただABSの方は直せる気がします
![Screenshot_20210426_091313_com android chrome](https://user-images.githubusercontent.com/73807432/116014999-b5b5b880-a672-11eb-82a0-4aba23a879e8.jpg)

**Comment by kenkoooo** [comment]
List に ABS の問題が1問しか無いのは、他の問題が既に別のコンテストで出題されているため重複した問題が取り除かれているためで、コンテスト-問題のペアの以下のJSONを見れば、ABSの問題がちゃんと11問入っていることを確認できます。
https://kenkoooo.com/atcoder/resources/contest-problem.json

**Comment by nebocco** [comment]
じゃあ特にできることはなさそうですね！ありがとうございます
