### ISSUE TITLE
APG4bをどうにかしたい

### ISSUE THREAD

**Issue by nebocco** [kenkoooo/AtCoderProblems#932]
https://twitter.com/maspy_stars/status/1387235905442697219

**Comment by nebocco** [comment]
https://atcoder.jp/contests/APG4b/tasks の tbody の中を見ると提出可能なものと不可能なものが区別できるんですが、problem_crawlerに「提出不可能な問題を削除する」みたいな作業を組み込むとなるとすべてのコンテストに対して無駄にチェックをかけることになるのであまり嬉しくなさそうです

**Comment by nebocco** [comment]
Chrome から見ると五列目に「提出」リンクが見えていたんですが、get_htmlで持ってくると五列目が丸々消えていました
screen のある環境でのみ追加される仕様っぽいのでこの方法では難しそうです

**Comment by kenkoooo** [comment]
表示する分にはビジュアライザは気合の exclude  をしているので、気合でいけるかもしれません。
https://github.com/kenkoooo/AtCoderProblems/blob/0282bbde17f6b5628f3bb366fef2ac8cb2fca5f0/atcoder-problems-frontend/src/utils/BlockList.ts

**Comment by kenkoooo** [comment]
maspy さんは json を使って手元で集計しているので、そういった需要に応えるには、先ほどの気合 exclude  をバックエンド側にもってくると良さそう。

**Comment by nebocco** [comment]
なるほど    block_listを持っておいて problem::scrape がかかるときに弾く感じですね
hidden_contests と同様に .json で持つと各コンテストをクロールするたびにアクセスしてしまうので、constとしてコード中に埋め込んでしまったほうがいいですかね？

**Comment by nebocco** [comment]
あとこれはあまり関係のない話ですが、practice contest も今問題ゼロの状態でコンテスト名だけ表示されてしまっていて気持ち悪いので、同様にblocked_contestsみたいなのをもってはじいてしまってもいいかもしれませんね

**Comment by kenkoooo** [comment]
サイトに表示されるかどうかは JSON contests.json や problems.json に載っているかどうかで決まるので、DBに入っている分には無害ですし、クローラー周りをいじる必要はないと思います。JSONを吐き出しているのは dump_json なので、そこで調整してやればいいと思います。const で埋め込んでもいいと思います。
