### ISSUE TITLE
AtCoder Typical Contest 002のアルファベットがおかしい

### ISSUE THREAD

**Issue by kanra824** [kenkoooo/AtCoderProblems#936]
maspy さんのツイートより
https://twitter.com/maspy_stars/status/1387782048996237319

![image](https://user-images.githubusercontent.com/27503986/116768761-0dd62b80-aa74-11eb-9fe4-82dbe5c96881.png)
ABC007のCとATC002のA（幅優先探索）が同じ問題で、ABC007のアルファベットが表示されています（リンクもABC007の方に飛びます）

**Comment by kenkoooo** [comment]
関連するものとして https://github.com/kenkoooo/AtCoderProblems/issues/412 があります。
