### ISSUE TITLE
APG4bが順番通りになっていない

### ISSUE THREAD

**Issue by cpcznksutbeoa** [kenkoooo/AtCoderProblems#937]
![image](https://user-images.githubusercontent.com/69896277/116805337-ce393d80-ab60-11eb-9ee7-ccc62bde91ab.png)
Other Contestsの下から二番目にAPG4bが載っていると思いますが、その順番が少なくとも僕目線では順番通りにはなっていません。(写真参照)
修正お願いします。

**Comment by kanra824** [comment]
辞書順比較をしているのが原因で、普通はA, B, C ...のように並ぶため問題が起こらない。
APG4bのときだけ最初1文字と後ろ4文字を結合した文字列で辞書順比較などすると正しい順番になりそうです。
https://github.com/kenkoooo/AtCoderProblems/blob/3383873a2fb849d0107c225e943e63dc37d7ce7d/atcoder-problems-frontend/src/pages/TablePage/ContestTable.tsx#L44-L46

**Comment by kanra824** [comment]
この方針で直せることを確認
![image](https://user-images.githubusercontent.com/27503986/117127378-f8943080-add6-11eb-9bc4-327e8be696ae.png)
