### ISSUE TITLE
Contest Problemset を diff 順にソートする

### ISSUE THREAD

**Issue by monkukui** [kenkoooo/AtCoderProblems#954]
<img width="1284" alt="スクリーンショット 2021-05-24 14 46 14" src="https://user-images.githubusercontent.com/47474057/119302289-d4719400-bc9e-11eb-910d-f3ec183279f8.png">

## 背景
- 数え上げ特訓ばちゃを作ろう！
- とりあえず目についた問題を貪欲に登録
- diff 順に並べ替えたいなぁ -> **ボタン一つで並べ替えれると便利**

@kenkoooo いかがでしょうか？フロントエンドで完結するタイプのタスクだと思っています。
go サインを出していただけるなら、僕が実装やってみたいです。
必要なければ、close してください。

**Comment by kenkoooo** [comment]
@monkukui お願いします。

どうするのがいいかは少し考えたいですね。テーブル形式にしてカラムをクリックするとソートできるとかが一番直感的っぽそうですが、

**Comment by monkukui** [comment]
> テーブル形式にしてカラムをクリックするとソートできるとかが一番直感的っぽそうではあります。

AtCoder のコンテストの順位表で、問題のカラムをクリックするとその問題を解いた時間順にソートされるようなイメージですね

![スクリーンショット 2021-05-24 21 15 53](https://user-images.githubusercontent.com/47474057/119346543-4ebd0b00-bcd5-11eb-89cc-71f2f488133c.png)
（図：C 問題を解いた時間順にソートされた順位表）

**Comment by monkukui** [comment]
となると、

- Diff
- Point

の二点が選べるキー（カラム）になりそうですかね。

![スクリーンショット 2021-05-24 21 19 10](https://user-images.githubusercontent.com/47474057/119347054-f1758980-bcd5-11eb-8e28-f98f6f6ec3a2.png)

**Comment by kenkoooo** [comment]
良さそうですね。現状の List みたいなイメージでした。

**Comment by monkukui** [comment]
@kenkoooo デザイン案 1 です。
一番単純に、diff 順にソートするボタンを配置します。

**Comment by monkukui** [comment]
@kenkoooo 
テーブルにするなら、今のデザインを少し変更することになりそうですが、大丈夫でしょうか？

**Comment by monkukui** [comment]
@kenkoooo 
> 良さそうですね。現状の List みたいなイメージでした。

すいません、どこのことでしょうか？

**Comment by monkukui** [comment]
仕様：
`difficulty` の昇順で（`difficulty` が存在しないものについては仮に `0` にして）ソートします。

**Comment by kenkoooo** [comment]
> @kenkoooo
> 
> > 良さそうですね。現状の List みたいなイメージでした。
> 
> すいません、どこのことでしょうか？

![image](https://user-images.githubusercontent.com/9150073/119369109-c3507380-bcee-11eb-9106-15a69a3f73d0.png)
このテーブルを想像していました。現状のバチャ作成画面は結構ゴチャゴチャしているので、そこにボタンを追加するのは微妙な気がしています。

**Comment by monkukui** [comment]
> このテーブルを想像していました。現状のバチャ作成画面は結構ゴチャゴチャしているので、そこにボタンを追加するのは微妙な気がしています。

なるほど、わかりました！
このテーブルを参考に、複数デザイン案を提案してみます。

**Comment by kenkoooo** [comment]
@monkukui :+1: 
とりあえず1個作ってみて、っていうので良いと思います。

**Comment by monkukui** [comment]
@kenkoooo とりあえず 1 個作ってみました。カラムの追加、デザインの修正など、いろいろ変更の余地があります。確認よろしくお願いします。
https://github.com/kenkoooo/AtCoderProblems/pull/959
