### ISSUE TITLE
取得した提出をブラウザに保存するようにする

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#963]
指定したユーザーの指定した時刻以降の提出が取得できるようになった (#948) ので、一度取得した提出をブラウザに保存するようにします。

- [ ] 新しい API を叩いて提出をブラウザ (IndexedDB) に保存するようにする。
  - 1回に500件までしか取得できないので、指定する時刻を更新しながらレスポンスが0件になるまで叩き続ける。
- [ ] 既存の提出取得関数を置き換える。
- [ ] ブラウザに保存されている提出を読み出して、差分のみリクエストするようにする。
  - ユーザー名が更新されていたり結果が更新されていたりするコーナーケースに思いを馳せる必要がある。場合によってはバックエンドも少し更新する必要があるかも。

**Comment by tsutaj** [comment]
可能であれば #948 に引き続き作業してみたいのですが、よろしいでしょうか？

**Comment by kenkoooo** [comment]
ZEHI!

**Comment by tsutaj** [comment]
今日からこれを着手すべく frontend のコードを読んだのですが、いくつか質問があります。

- IndexedDB 周りのコードはどこに書いたら良いですか？
  - ゆくゆくは `userUserSubmission` 関数 (https://github.com/kenkoooo/AtCoderProblems/blob/688258606b4f031c32b95820ae03f9f6772aaaca/atcoder-problems-frontend/src/api/APIClient.ts#L146) を変更することになると思うので、とりあえずこの周辺にコードを書いておいて、ファイルを分けるなら後で移そうかなといまのところは考えています
- IndexedDB に保存されている提出時間のうち最も新しい時間は、どのように取得したら良いですか？
  - `indexedDB.open("submission_db_name")` を毎回叩いて最新の提出の時間を持ってくるでも良いですが、それだと結局時間がかかりそうなので、最も新しい時間だけ別でどこかに持っておきたい気持ちがあります。こういう場合、どのようにしてデータを保持すれば筋が良いでしょうか？

**Comment by kenkoooo** [comment]
ディレクトリ構成は割とガバガバなのでお任せですが、とりあえずsrc/db/みたいなのを作るのが良いですかね。

保存している最新提出の情報をキャッシュして高速化するのは将来的には考えうるのですが、まずは遅くても良いので動くものを作る方針で行きましょう。最終的な実装は以下のようになると予想します。
1. ユーザーがページを開いた時や新しいユーザー名を入力した時、ローカルの提出を全てメモリに読み出す。
2. 足りない提出をAPI経由で取得してメモリに保持する。ついでにローカルに保存する。
3. ページ遷移の際にはメモリに保持した提出を使い回すのでdbには接続しないので遅くならない。

**Comment by kenkoooo** [comment]
@tsutaj おつかれさまでした！
