### ISSUE TITLE
バチャ作成テーブル、カラム順ソートできるかどうかが非自明

### ISSUE THREAD

**Issue by monkukui** [kenkoooo/AtCoderProblems#972]
- https://twitter.com/totori_kpr/status/1402667636610109440?s=20
- https://twitter.com/totori_kpr/status/1402668732233576449?s=20

**Comment by penicillin0** [comment]
@monkukui 
こちらやってみてもよろしいでしょうか？

**Comment by monkukui** [comment]
@penicillin0 お願いします！


@kenkoooo @penicillin0 さんにやってもらいます！

**Comment by fukatani** [comment]
@penicillin0 @monkukui 
このissueはもうクローズしても大丈夫だと思います。
PR立てる時に
https://docs.github.com/ja/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue
のような方法でPRとissueをリンクしてマージ時に自動的にクローズすることができます。

**Comment by monkukui** [comment]
@fukatani ありがとうございます！クローズしちゃいますね！

@penicillin0 お疲れ様でした！
